"""Datos técnicos de 15 modelos de Amoladoras en Argentina."""

from tallerlab_data.catalog_data.common import make_spec
from tallerlab_data.models import (
    CommercialOffer,
    ContradictionRecord,
    KitOption,
    RegionalVariant,
    TechnicalTool,
)

AMOLADORAS_TOOLS = [
    TechnicalTool(
        slug="bosch-gws-770",
        brand="Bosch",
        commercial_name="GWS 770 Professional (115 mm)",
        mpn="06013980E0",
        category="amoladoras",
        summary="Amoladora angular compacta de 770 W para discos de 115 mm con 1,37 kg de peso.",
        primary_use="Corte y desbaste ligero en cerrajería y carpintería metálica",
        power_source="Red eléctrica (220 V)",
        specs={
            "potencia": make_spec("potencia", "Potencia absorbida", "770 W", "W", 770.0, "W", "Nominal", "06013980E0", "Ficha técnica oficial Bosch Brasil", "https://www.bosch-professional.com/br/pt/products/gws-770-06013980E0", "pág. 1", "declarado"),
            "diametro_disco": make_spec("diametro_disco", "Diámetro del disco", "115 mm (4-1/2\")", "mm", 115.0, "mm", "Accesorio admisible", "06013980E0", "Ficha técnica oficial Bosch Brasil", "https://www.bosch-professional.com/br/pt/products/gws-770-06013980E0", "pág. 1", "declarado"),
            "velocidad_vacio": make_spec("velocidad_vacio", "Velocidad de giro en vacío", "12.000 rpm", "rpm", 12000.0, "rpm", "Sin carga a 50/60 Hz", "06013980E0", "Ficha técnica oficial Bosch Brasil", "https://www.bosch-professional.com/br/pt/products/gws-770-06013980E0", "pág. 1", "declarado"),
            "rosca_husillo": make_spec("rosca_husillo", "Rosca del husillo", "M14", "rosca", 0.0, "rosca", "Paso estándar métrico", "06013980E0", "Ficha técnica oficial Bosch Brasil", "https://www.bosch-professional.com/br/pt/products/gws-770-06013980E0", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso según Bosch", "1,37 kg", "kg", 1.37, "kg", "Solo herramienta", "06013980E0", "Ficha técnica oficial Bosch Brasil", "https://www.bosch-professional.com/br/pt/products/gws-770-06013980E0", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("06013980E0", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Variante 220V regional")],
        kits=[KitOption("06013980E0-STD", "GWS 770 con empuñadura auxiliar y guarda de protección", "No aplica", "No aplica", ["Empuñadura auxiliar", "Guarda 115mm", "Llave de brida"])],
        commercial_offers=[CommercialOffer("Tienda Oficial Bosch", "Mercado Libre", "https://meli.la/1GRCAjZ", 129000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Fuente Bosch Brasil para 06013980E0; no confirma por sí sola la variante, el kit ni la garantía de una oferta importada no oficial."],
        primary_sources=[{"label": "Ficha oficial Bosch GWS 770", "url": "https://www.bosch-professional.com/br/pt/products/gws-770-06013980E0"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="bosch-gws-9-115-s",
        brand="Bosch",
        commercial_name="GWS 9-115 S Velocidad Variable",
        mpn="0601396103",
        category="amoladoras",
        summary="Amoladora de 900 W con dial selector de velocidad (2.800 a 11.000 rpm) para amolado, decapado y pulido fino.",
        primary_use="Trabajos en acero inoxidable, decapado y desbaste controlado",
        power_source="Red eléctrica (220 V)",
        specs={
            "potencia": make_spec("potencia", "Potencia absorbida", "900 W", "W", 900.0, "W", "Nominal", "0601396103", "Ficha oficial Bosch España", "https://www.bosch-professional.com/es/es/products/gws-9-115-s-0601396103", "pág. 1", "declarado"),
            "diametro_disco": make_spec("diametro_disco", "Diámetro de disco", "115 mm", "mm", 115.0, "mm", "Accesorios T27 y corte", "0601396103", "Ficha oficial Bosch España", "https://www.bosch-professional.com/es/es/products/gws-9-115-s-0601396103", "pág. 1", "declarado"),
            "velocidad_variable": make_spec("velocidad_variable", "Velocidad de giro en vacío", "2.800–11.000 rpm", "rpm", 11000.0, "rpm", "Dial electrónico con 6 posiciones", "0601396103", "Ficha oficial Bosch España", "https://www.bosch-professional.com/es/es/products/gws-9-115-s-0601396103", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso publicado", "1,9 kg", "kg", 1.9, "kg", "Balanza", "0601396103", "Ficha oficial Bosch España", "https://www.bosch-professional.com/es/es/products/gws-9-115-s-0601396103", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("0601396103", "Argentina / España", "220-240 V / 50 Hz", "IRAM 2073", "Velocidad variable")],
        kits=[KitOption("0601396103-STD", "GWS 9-115 S con empuñadura antivibración y tuerca M14", "No aplica", "No aplica", ["Empuñadura", "Guarda", "Brida M14"])],
        commercial_offers=[CommercialOffer("Distribuidor Bosch", "Mercado Libre", "https://meli.la/2BGWS9115S", 235000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Al trabajar a bajas revoluciones (2.800 rpm) el ventilador refrigera menos el motor; no aplicar sobrecarga continua en baja velocidad."],
        primary_sources=[{"label": "Ficha oficial Bosch GWS 9-115 S", "url": "https://www.bosch-professional.com/es/es/products/gws-9-115-s-0601396103"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="bosch-gws-850",
        brand="Bosch",
        commercial_name="GWS 850 Professional (115 mm)",
        mpn="06013775H0",
        category="amoladoras",
        summary="Amoladora angular de 850 W con 11.000 rpm y motor optimizado para uso continuo en taller.",
        primary_use="Corte de caños, perfiles y desbaste de soldadura",
        power_source="Red eléctrica (220 V)",
        specs={
            "potencia": make_spec("potencia", "Potencia absorbida", "850 W", "W", 850.0, "W", "Nominal", "06013775H0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gws-850-06013775H0", "pág. 1", "declarado"),
            "diametro_disco": make_spec("diametro_disco", "Diámetro de disco", "115 mm (4-1/2\")", "mm", 115.0, "mm", "Accesorios 115 mm", "06013775H0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gws-850-06013775H0", "pág. 1", "declarado"),
            "velocidad_vacio": make_spec("velocidad_vacio", "Velocidad en vacío", "11.000 rpm", "rpm", 11000.0, "rpm", "Nominal", "06013775H0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gws-850-06013775H0", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso neto", "1,7 kg", "kg", 1.7, "kg", "Balanza", "06013775H0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gws-850-06013775H0", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("06013775H0", "Argentina", "220 V / 50 Hz", "IRAM 2073", "850W")],
        kits=[KitOption("06013775H0-STD", "GWS 850 con llave de ajuste y cubierta protectora", "No aplica", "No aplica", ["Cubierta protectora", "Empuñadura", "Brida"])],
        commercial_offers=[CommercialOffer("Distribuidor Bosch", "Mercado Libre", "https://meli.la/2BGWS850", 169000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["No cuenta con protección contra rearranque tras corte de luz como los modelos de mayor gama."],
        primary_sources=[{"label": "Ficha oficial Bosch GWS 850", "url": "https://www.bosch-professional.com/ar/es/products/gws-850-06013775H0"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="bosch-gws-25-180-lvi-r",
        brand="Bosch",
        commercial_name="GWS 25-180 LVI R (180 mm)",
        mpn="06018F71H1",
        category="amoladoras",
        summary="Amoladora angular grande de 2500 W para disco de 180 mm con KickBack Control y empuñadura Vibration Control.",
        primary_use="Corte pesado en perfiles estructurales e industria pesada",
        power_source="Red eléctrica (220 V)",
        specs={
            "potencia": make_spec("potencia", "Potencia absorbida", "2500 W", "W", 2500.0, "W", "Nominal", "06018F71H1", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gws-25-180-lvi-r-06018F71H1", "pág. 1", "declarado"),
            "diametro_disco": make_spec("diametro_disco", "Diámetro de disco", "180 mm (7\")", "mm", 180.0, "mm", "Accesorios 180 mm", "06018F71H1", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gws-25-180-lvi-r-06018F71H1", "pág. 1", "declarado"),
            "velocidad_vacio": make_spec("velocidad_vacio", "Velocidad en vacío", "8.500 rpm", "rpm", 8500.0, "rpm", "Nominal", "06018F71H1", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gws-25-180-lvi-r-06018F71H1", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso neto", "No consta en recorte", "kg", None, "kg", "No informado en la ficha consultada", "06018F71H1", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gws-25-180-lvi-r-06018F71H1", "pág. 1", "no_encontrado", notes="El peso no aparece en la ficha citada y no se completa por similitud."),
            "seguridad": make_spec("seguridad", "Sistemas de seguridad activos", "KickBack Control + Soft Start", "sistema", 0.0, "sistema", "Freno electrónico por atasco y arranque suave", "06018F71H1", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gws-25-180-lvi-r-06018F71H1", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("06018F71H1", "Argentina", "220 V / 50 Hz", "IRAM 2073", "GWS 25-180 LVI R")],
        kits=[KitOption("06018F71H1-STD", "GWS 25-180 LVI R con empuñadura Vibration Control", "No aplica", "No aplica", ["Empuñadura Vibration Control", "Guarda 180mm", "Brida"])],
        commercial_offers=[CommercialOffer("Distribuidor Bosch", "Mercado Libre", "https://meli.la/2BGWS180", 615000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["La velocidad de 8.500 rpm está calibrada para disco de 180 mm; nunca montar discos de 230 mm en una máquina de 180 mm."],
        primary_sources=[{"label": "Ficha oficial Bosch GWS 25-180 LVI R", "url": "https://www.bosch-professional.com/ar/es/products/gws-25-180-lvi-r-06018F71H1"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="bosch-gws-25-230",
        brand="Bosch",
        commercial_name="GWS 25-230 Professional (230 mm)",
        mpn="06018F41H0",
        category="amoladoras",
        summary="Amoladora angular pesada de 2500 W para disco de 230 mm (9\") y 6.500 rpm.",
        primary_use="Corte de vigas IPN, perfiles pesados, losas y hormigón",
        power_source="Red eléctrica (220 V)",
        specs={
            "potencia": make_spec("potencia", "Potencia absorbida", "2500 W", "W", 2500.0, "W", "Nominal", "06018F41H0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gws-25-180-06018F41H0", "pág. 1", "declarado"),
            "diametro_disco": make_spec("diametro_disco", "Diámetro de disco", "230 mm (9\")", "mm", 230.0, "mm", "Accesorios 230 mm", "06018F41H0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gws-25-180-06018F41H0", "pág. 1", "declarado"),
            "velocidad_vacio": make_spec("velocidad_vacio", "Velocidad en vacío", "6.500 rpm", "rpm", 6500.0, "rpm", "Nominal", "06018F41H0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gws-25-180-06018F41H0", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso neto", "5,9 kg", "kg", 5.9, "kg", "Balanza", "06018F41H0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gws-25-180-06018F41H0", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("06018F41H0", "Argentina", "220 V / 50 Hz", "IRAM 2073", "230 mm")],
        kits=[KitOption("06018F41H0-STD", "GWS 25-230 con guarda de protección y empuñadura auxiliar", "No aplica", "No aplica", ["Guarda de 230mm", "Empuñadura", "Llave"])],
        commercial_offers=[CommercialOffer("Distribuidor Bosch", "Mercado Libre", "https://meli.la/24LpMmr", 489000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Máquina pesada de 5,9 kg; exige sujeción a dos manos y desconexión segura en cambio de disco."],
        primary_sources=[{"label": "Ficha oficial Bosch GWS 25-230", "url": "https://www.bosch-professional.com/ar/es/products/gws-25-180-06018F41H0"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="dewalt-dwe4010",
        brand="DeWalt",
        commercial_name="DeWalt DWE4010 (115 mm)",
        mpn="DWE4010",
        category="amoladoras",
        summary="Amoladora angular compacta de 750 W con 12.000 rpm y cuerpo estilizado para mayor comodidad.",
        primary_use="Taller y cerrajería ligera",
        power_source="Red eléctrica (220 V)",
        specs={
            "potencia": make_spec("potencia", "Potencia", "750 W", "W", 750.0, "W", "Nominal", "DWE4010", "Ficha técnica DeWalt Argentina", "https://ar.dewalt.global/producto/dwe4010-ar/esmeriladora-angular-de-4-12-115-mm", "pág. 1", "declarado"),
            "diametro_disco": make_spec("diametro_disco", "Diámetro de disco", "115 mm (4-1/2\")", "mm", 115.0, "mm", "Accesorios 115 mm", "DWE4010", "Ficha técnica DeWalt Argentina", "https://ar.dewalt.global/producto/dwe4010-ar/esmeriladora-angular-de-4-12-115-mm", "pág. 1", "declarado"),
            "velocidad_vacio": make_spec("velocidad_vacio", "Velocidad sin carga", "12.000 rpm", "rpm", 12000.0, "rpm", "Nominal", "DWE4010", "Ficha técnica DeWalt Argentina", "https://ar.dewalt.global/producto/dwe4010-ar/esmeriladora-angular-de-4-12-115-mm", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso", "1,8 kg", "kg", 1.8, "kg", "Neto", "DWE4010", "Ficha técnica DeWalt Argentina", "https://ar.dewalt.global/producto/dwe4010-ar/esmeriladora-angular-de-4-12-115-mm", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("DWE4010-AR", "Argentina", "220 V / 50 Hz", "IRAM 2073", "750W")],
        kits=[KitOption("DWE4010-STD", "DWE4010 con llave y guarda protectora", "No aplica", "No aplica", ["Guarda", "Empuñadura", "Llave"])],
        commercial_offers=[CommercialOffer("Distribuidor DeWalt", "Mercado Libre", "https://meli.la/2DWE4010", 139000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Interruptor deslizante con bloqueo; verificar desbloqueo antes de conectar a la red."],
        primary_sources=[{"label": "Ficha oficial DeWalt DWE4010", "url": "https://ar.dewalt.global/producto/dwe4010-ar/esmeriladora-angular-de-4-12-115-mm"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="dewalt-dwe4120",
        brand="DeWalt",
        commercial_name="DeWalt DWE4120 Paleta (115 mm)",
        mpn="DWE4120",
        category="amoladoras",
        summary="Amoladora de 900 W con interruptor tipo paleta (paddle switch) para mayor seguridad en uso industrial.",
        primary_use="Corte industrial y desbaste continuo",
        power_source="Red eléctrica (220 V)",
        specs={
            "potencia": make_spec("potencia", "Potencia", "900 W", "W", 900.0, "W", "Nominal", "DWE4120", "Ficha técnica DeWalt Argentina", "https://ar.dewalt.global/producto/dwe4120-ar/esmeriladora-angular-de-4-12-115-mm-con-interruptor-tipo-paleta", "pág. 1", "declarado"),
            "velocidad_vacio": make_spec("velocidad_vacio", "Velocidad sin carga", "12.000 rpm", "rpm", 12000.0, "rpm", "Nominal", "DWE4120", "Ficha técnica DeWalt Argentina", "https://ar.dewalt.global/producto/dwe4120-ar/esmeriladora-angular-de-4-12-115-mm-con-interruptor-tipo-paleta", "pág. 1", "declarado"),
            "interruptor": make_spec("interruptor", "Tipo de interruptor", "Paleta con bloqueo de seguridad", "tipo", 0.0, "tipo", "Se apaga automáticamente al soltar", "DWE4120", "Ficha técnica DeWalt Argentina", "https://ar.dewalt.global/producto/dwe4120-ar/esmeriladora-angular-de-4-12-115-mm-con-interruptor-tipo-paleta", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("DWE4120-AR", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Interruptor paleta")],
        kits=[KitOption("DWE4120-STD", "DWE4120 con guarda de ajuste rápido One-Touch", "No aplica", "No aplica", ["Guarda One-Touch", "Empuñadura lateral", "Llave"])],
        commercial_offers=[CommercialOffer("Distribuidor DeWalt", "Mercado Libre", "https://meli.la/2DWE4120", 185000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["El gatillo paleta previene accidentes pero puede resultar fatigoso en tareas prolongadas de pulido estático."],
        primary_sources=[{"label": "Ficha oficial DeWalt DWE4120", "url": "https://ar.dewalt.global/producto/dwe4120-ar/esmeriladora-angular-de-4-12-115-mm-con-interruptor-tipo-paleta"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="dewalt-dcg412",
        brand="DeWalt",
        commercial_name="DeWalt DCG412B Inalámbrica 20V",
        mpn="DCG412B",
        category="amoladoras",
        summary="Amoladora angular a batería de 20V MAX con 8.000 rpm y embrague de seguridad Quick-Change.",
        primary_use="Trabajos en altura, cortes de emergencia y mantenimiento sin red",
        power_source="Batería 20 V MAX Li-Ion",
        specs={
            "diametro_disco": make_spec("diametro_disco", "Diámetro de disco", "115 / 125 mm", "mm", 125.0, "mm", "Acepta guardas de 4-1/2 y 5\"", "DCG412B", "Ficha oficial DeWalt", "https://ar.dewalt.global/producto/dcg412b/esmeriladora-angular-de-4-12-a-5-115-mm-a-125-mm-20v-max", "pág. 1", "declarado"),
            "velocidad_vacio": make_spec("velocidad_vacio", "Velocidad en vacío", "8.000 rpm", "rpm", 8000.0, "rpm", "Nominal", "DCG412B", "Ficha oficial DeWalt", "https://ar.dewalt.global/producto/dcg412b/esmeriladora-angular-de-4-12-a-5-115-mm-a-125-mm-20v-max", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso sin batería", "1,9 kg", "kg", 1.9, "kg", "Balanza", "DCG412B", "Ficha oficial DeWalt", "https://ar.dewalt.global/producto/dcg412b/esmeriladora-angular-de-4-12-a-5-115-mm-a-125-mm-20v-max", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("DCG412B", "Argentina", "20 V MAX", "DeWalt 20V MAX", "Solo")],
        kits=[KitOption("DCG412B-SOLO", "Herramienta sola con tuerca de cambio rápido y llave", "No incluye", "No incluye", ["Empuñadura de 2 posiciones", "Llave"])],
        commercial_offers=[CommercialOffer("Distribuidor DeWalt", "Mercado Libre", "https://meli.la/2DCG412", 295000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Amolar o desbastar metal consume rápidamente la batería; se sugiere usar paquetes de 5.0 Ah o superior."],
        primary_sources=[{"label": "Ficha oficial DeWalt DCG412B", "url": "https://ar.dewalt.global/producto/dcg412b/esmeriladora-angular-de-4-12-a-5-115-mm-a-125-mm-20v-max"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="makita-ga4530",
        brand="Makita",
        commercial_name="Makita GA4530 (115 mm)",
        mpn="GA4530",
        category="amoladoras",
        summary="Amoladora angular de 720 W con cuerpo ultra delgado de 56 mm de diámetro para máxima maniobrabilidad.",
        primary_use="Cerrajería, herrería y mecanizado ligero",
        power_source="Red eléctrica (220 V)",
        specs={
            "potencia": make_spec("potencia", "Potencia", "720 W", "W", 720.0, "W", "Nominal", "GA4530", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 36", "declarado"),
            "diametro_disco": make_spec("diametro_disco", "Diámetro de disco", "115 mm (4-1/2\")", "mm", 115.0, "mm", "Accesorios 115 mm", "GA4530", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 36", "declarado"),
            "velocidad_vacio": make_spec("velocidad_vacio", "Velocidad en vacío", "11.000 rpm", "rpm", 11000.0, "rpm", "Nominal", "GA4530", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 36", "declarado"),
            "peso": make_spec("peso", "Peso neto", "1,8 kg", "kg", 1.8, "kg", "Balanza", "GA4530", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 36", "declarado"),
        },
        variants=[RegionalVariant("GA4530", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Cuerpo 56 mm")],
        kits=[KitOption("GA4530-STD", "GA4530 con guarda de protección y disco abrasivo", "No aplica", "No aplica", ["Guarda", "Empuñadura", "Llave", "Disco desbaste"])],
        commercial_offers=[CommercialOffer("Distribuidor Makita", "Mercado Libre", "https://meli.la/2MGA4530", 175000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Carcasa de reductora metálica orientable a 90 grados para zurdos."],
        primary_sources=[{"label": "Catálogo Makita Argentina 2025", "url": "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="makita-m0901",
        brand="Makita",
        commercial_name="Makita MT M0901B (115 mm)",
        mpn="M0901B",
        category="amoladoras",
        summary="Amoladora de la serie Makita MT de 540 W orientada a tareas estándar de taller.",
        primary_use="Hogar y corte ligero",
        power_source="Red eléctrica (220 V)",
        specs={
            "potencia": make_spec("potencia", "Potencia", "540 W", "W", 540.0, "W", "Nominal", "M0901B", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 38", "declarado"),
            "diametro_disco": make_spec("diametro_disco", "Diámetro de disco", "115 mm", "mm", 115.0, "mm", "Accesorios 115 mm", "M0901B", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 38", "declarado"),
            "velocidad_vacio": make_spec("velocidad_vacio", "Velocidad en vacío", "12.000 rpm", "rpm", 12000.0, "rpm", "Nominal", "M0901B", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 38", "declarado"),
            "peso": make_spec("peso", "Peso neto", "1,7 kg", "kg", 1.7, "kg", "Balanza", "M0901B", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 38", "declarado"),
        },
        variants=[RegionalVariant("M0901B", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Línea MT")],
        kits=[KitOption("M0901B-STD", "Amoladora MT con llave y empuñadura", "No aplica", "No aplica", ["Guarda", "Llave", "Empuñadura"])],
        commercial_offers=[CommercialOffer("Distribuidor Makita", "Mercado Libre", "https://meli.la/2MM0901", 119000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Línea MT simplificada con motor de 540 W; menor reserva de potencia ante aprietes bruscos."],
        primary_sources=[{"label": "Catálogo Makita Argentina 2025", "url": "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="makita-gb801",
        brand="Makita",
        commercial_name="Makita GB801 de Banco (205 mm)",
        mpn="GB801",
        category="amoladoras",
        summary="Amoladora de banco de 550 W con dos piedras de 205 mm (8\") y visores protectores con lupa.",
        primary_use="Afilado de herramientas, desbaste de piezas y pulido en banco",
        power_source="Red eléctrica (220 V)",
        specs={
            "potencia": make_spec("potencia", "Potencia", "550 W", "W", 550.0, "W", "Inducción", "GB801", "Catálogo Makita Argentina 2025 (pág. 49)", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025.pdf", "pág. 49", "declarado"),
            "diametro_disco": make_spec("diametro_disco", "Diámetro de piedras", "205 mm (8\")", "mm", 205.0, "mm", "Espesor 19 mm / Eje 15,88 mm", "GB801", "Catálogo Makita Argentina 2025 (pág. 49)", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025.pdf", "pág. 49", "declarado"),
            "velocidad_vacio": make_spec("velocidad_vacio", "Velocidad sin carga", "2.850 / 3.450 rpm", "rpm", 2850.0, "rpm", "2850 rpm a 50 Hz en Argentina", "GB801", "Catálogo Makita Argentina 2025 (pág. 49)", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025.pdf", "pág. 49", "declarado"),
            "peso": make_spec("peso", "Peso neto", "19,8 kg", "kg", 19.8, "kg", "Balanza", "GB801", "Catálogo Makita Argentina 2025 (pág. 49)", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025.pdf", "pág. 49", "declarado"),
        },
        variants=[RegionalVariant("GB801", "Argentina", "220 V / 50 Hz", "IRAM 2073", "De banco")],
        kits=[KitOption("GB801-STD", "Amoladora de banco con 2 muelas (grano 36 y 60) y visores con luz", "No aplica", "No aplica", ["Muela grano 36", "Muela grano 60", "Protectores oculares con lupa"])],
        commercial_offers=[CommercialOffer("Distribuidor Makita", "Mercado Libre", "https://meli.la/2MGB801", 495000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["En Argentina (red 50 Hz) la velocidad real de sincronismo es de 2.850 rpm; las 3.450 rpm corresponden a redes de 60 Hz."],
        primary_sources=[{"label": "Catálogo Makita Argentina 2025 (pág. 49)", "url": "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025.pdf"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="skil-9002ar",
        brand="Skil",
        commercial_name="Skil 9002AR (115 mm)",
        mpn="9002AR",
        category="amoladoras",
        summary="Amoladora angular con contradicción documentada de potencia entre ediciones de manual oficial (700 W vs 600 W).",
        primary_use="Hogar y bricolaje",
        power_source="Red eléctrica (220 V)",
        specs={
            "potencia": make_spec("potencia", "Potencia declarada", "700 W (ed. 2015) / 600 W (ed. 2009)", "W", 700.0, "W", "Discrepancia entre ediciones de manuales oficiales Skil", "9002AR", "Manual SKIL 1 600 A00 9XF (feb 2015)", "https://cdn.homedepot.com.mx/productos/704443/704443-m.pdf", "pág. 12", "contradictorio", notes="Manual de feb 2015 declara 700 W; manual F 000 622 318 de 2009 declara 600 W."),
            "diametro_disco": make_spec("diametro_disco", "Diámetro de disco", "115 mm", "mm", 115.0, "mm", "Accesorios 115 mm", "9002AR", "Manual SKIL 1 600 A00 9XF (feb 2015)", "https://cdn.homedepot.com.mx/productos/704443/704443-m.pdf", "pág. 12", "declarado"),
            "velocidad_vacio": make_spec("velocidad_vacio", "Velocidad en vacío", "11.000 rpm", "rpm", 11000.0, "rpm", "Nominal", "9002AR", "Manual SKIL 1 600 A00 9XF (feb 2015)", "https://cdn.homedepot.com.mx/productos/704443/704443-m.pdf", "pág. 12", "declarado"),
            "peso": make_spec("peso", "Peso publicado", "1,7 kg en ed. 2015 / 2,4 kg en ed. 2009", "kg", 1.7, "kg", "Discrepancia entre manuales", "9002AR", "Manual SKIL 1 600 A00 9XF (feb 2015)", "https://cdn.homedepot.com.mx/productos/704443/704443-m.pdf", "pág. 12", "contradictorio"),
        },
        variants=[RegionalVariant("9002AR", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Sufijo AR")],
        kits=[KitOption("9002AR-STD", "Amoladora Skil con llave y brida", "No aplica", "No aplica", ["Guarda", "Llave"])],
        commercial_offers=[CommercialOffer("Distribuidor Skil", "Mercado Libre", "https://meli.la/2SKIL9002", 99000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[
            ContradictionRecord(
                spec_key="potencia",
                field_name="Potencia nominal del motor",
                source_a_name="Manual Skil 2015 (pág. 12)",
                source_a_value="700 W",
                source_a_url="https://cdn.homedepot.com.mx/productos/704443/704443-m.pdf",
                source_b_name="Manual Skil 2009 (pág. 19)",
                source_b_value="600 W",
                source_b_url="https://cdn.leroymerlin.com.br/medias/document-89382741-user-manual-esmerilhadeira-angular-4-1-2--115mm--700w-9002-127v--110v--100percent-rolamentada-skil.pdf",
                editorial_note="Conservamos ambas fuentes oficiales documentadas; la versión actual comercializada en Argentina declara 700 W en placa metálica."
            )
        ],
        limits_and_warnings=["Discrepancia histórica entre manuales; verificar placa del lote importado."],
        primary_sources=[
            {"label": "Manual Skil 2015 oficial", "url": "https://cdn.homedepot.com.mx/productos/704443/704443-m.pdf"},
            {"label": "Manual Skil 2009 oficial", "url": "https://cdn.leroymerlin.com.br/medias/document-89382741-user-manual-esmerilhadeira-angular-4-1-2--115mm--700w-9002-127v--110v--100percent-rolamentada-skil.pdf"}
        ],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="gamma-g1910kar",
        brand="Gamma",
        commercial_name="Gamma G1910KAR (750W)",
        mpn="G1910KAR",
        category="amoladoras",
        summary="Amoladora de 750 W con disco de 115 mm en kit con maletín y discos de corte.",
        primary_use="Hogar y bricolaje",
        power_source="Red eléctrica (220 V)",
        specs={
            "potencia": make_spec("potencia", "Potencia declarada", "750 W", "W", 750.0, "W", "Nominal", "G1910KAR", "Ficha comercial Gramabi / Gamma", "https://www.gramabi.com.ar/productos/amoladora-angular-750w-gamma-115mm-kit-g1910kar-caja-discos-celeste-60-hz-vvvco/", "pág. 1", "declarado"),
            "diametro_disco": make_spec("diametro_disco", "Diámetro de disco", "115 mm", "mm", 115.0, "mm", "Accesorios 115 mm", "G1910KAR", "Ficha comercial Gramabi / Gamma", "https://www.gramabi.com.ar/productos/amoladora-angular-750w-gamma-115mm-kit-g1910kar-caja-discos-celeste-60-hz-vvvco/", "pág. 1", "declarado"),
            "velocidad_vacio": make_spec("velocidad_vacio", "Velocidad en vacío", "11.000 rpm", "rpm", 11000.0, "rpm", "Nominal", "G1910KAR", "Ficha comercial Gramabi / Gamma", "https://www.gramabi.com.ar/productos/amoladora-angular-750w-gamma-115mm-kit-g1910kar-caja-discos-celeste-60-hz-vvvco/", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("G1910KAR", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Kit con caja")],
        kits=[KitOption("G1910KAR-KIT", "Kit con caja plástica y discos abrasivos", "No aplica", "No aplica", ["Caja plástica", "Discos abrasivos", "Llave"])],
        commercial_offers=[CommercialOffer("Distribuidor Gamma", "Mercado Libre", "https://meli.la/12aMvrG", 99900.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Configuración del kit de accesorios sujeta a confirmación en el aviso de venta."],
        primary_sources=[{"label": "Ficha Gamma G1910KAR", "url": "https://www.gammaherramientas.com.ar/producto/amoladora-angular-750-w/"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="dowen-pagio-9993220-7",
        brand="Dowen Pagio",
        commercial_name="Dowen Pagio 9993220.7 (900W)",
        mpn="9993220.7",
        category="amoladoras",
        summary="Amoladora angular con cable de 900 W para disco de 115 mm y 12.000 rpm.",
        primary_use="Taller y herrería",
        power_source="Red eléctrica (220 V)",
        specs={
            "potencia": make_spec("potencia", "Potencia", "900 W", "W", 900.0, "W", "220 V / 50 Hz", "9993220.7", "Ficha técnica Frávega / Dowen Pagio", "https://www.fravega.com/p/amoladora-angular-115mm-dowen-pagio-9993220-7-900w-990018584/", "pág. 1", "declarado"),
            "diametro_disco": make_spec("diametro_disco", "Diámetro de disco", "115 mm", "mm", 115.0, "mm", "Accesorios 115 mm", "9993220.7", "Ficha técnica Frávega / Dowen Pagio", "https://www.fravega.com/p/amoladora-angular-115mm-dowen-pagio-9993220-7-900w-990018584/", "pág. 1", "declarado"),
            "velocidad_vacio": make_spec("velocidad_vacio", "Velocidad en vacío", "12.000 rpm", "rpm", 12000.0, "rpm", "Nominal", "9993220.7", "Ficha técnica Frávega / Dowen Pagio", "https://www.fravega.com/p/amoladora-angular-115mm-dowen-pagio-9993220-7-900w-990018584/", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("9993220.7", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Naranja")],
        kits=[KitOption("9993220.7-STD", "Amoladora con empuñadura y protector", "No aplica", "No aplica", ["Empuñadura", "Protector", "Llave"])],
        commercial_offers=[CommercialOffer("Distribuidor Dowen Pagio", "Mercado Libre", "https://meli.la/1QUvfns", 125000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Verificar si el aviso incluye disco de corte o solo la herramienta desnuda."],
        primary_sources=[{"label": "Ficha comercial Dowen Pagio 9993220.7", "url": "https://www.fravega.com/p/amoladora-angular-115mm-dowen-pagio-9993220-7-900w-990018584/"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="stanley-sg7115",
        brand="Stanley",
        commercial_name="Stanley SG7115 Small Angle (750W)",
        mpn="SG7115",
        category="amoladoras",
        summary="Amoladora angular de 750 W con diseño de engranajes helicoidales para menor vibración.",
        primary_use="Bricolaje y taller",
        power_source="Red eléctrica (220 V)",
        specs={
            "potencia": make_spec("potencia", "Potencia", "750 W", "W", 750.0, "W", "Nominal", "SG7115", "Ficha técnica Stanley Argentina", "https://ar.stanleytools.global/producto/sg7115-ar/esmeriladora-angular-de-4-12-115-mm", "pág. 1", "declarado"),
            "diametro_disco": make_spec("diametro_disco", "Diámetro de disco", "115 mm", "mm", 115.0, "mm", "Accesorios 115 mm", "SG7115", "Ficha técnica Stanley Argentina", "https://ar.stanleytools.global/producto/sg7115-ar/esmeriladora-angular-de-4-12-115-mm", "pág. 1", "declarado"),
            "velocidad_vacio": make_spec("velocidad_vacio", "Velocidad en vacío", "12.000 rpm", "rpm", 12000.0, "rpm", "Nominal", "SG7115", "Ficha técnica Stanley Argentina", "https://ar.stanleytools.global/producto/sg7115-ar/esmeriladora-angular-de-4-12-115-mm", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("SG7115-AR", "Argentina", "220 V / 50 Hz", "IRAM 2073", "750W")],
        kits=[KitOption("SG7115-STD", "Amoladora con empuñadura lateral de dos posiciones", "No aplica", "No aplica", ["Empuñadura", "Guarda", "Llave"])],
        commercial_offers=[CommercialOffer("Distribuidor Stanley", "Mercado Libre", "https://meli.la/2STSG7115", 118000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Diseño de ventilación lateral; evitar obstruir las ranuras con guantes gruesos durante el trabajo."],
        primary_sources=[{"label": "Ficha oficial Stanley SG7115", "url": "https://ar.stanleytools.global/producto/sg7115-ar/esmeriladora-angular-de-4-12-115-mm"}],
        last_reviewed="2026-10-01"
    )
]
