"""Datos técnicos de 25 modelos de Compresores de Aire en Argentina."""

from tallerlab_data.catalog_data.common import make_spec
from tallerlab_data.models import (
    CommercialOffer,
    ContradictionRecord,
    KitOption,
    RegionalVariant,
    TechnicalTool,
)

COMPRESORES_TOOLS = [
    TechnicalTool(
        slug="lusqtoff-lc2550b-8",
        brand="Lüsqtoff",
        commercial_name="LC2550B-8 (50 Litros)",
        mpn="LC2550B-8",
        category="compresores",
        summary="Compresor de pistón lubricado por aceite con tanque horizontal de 50 L y motor de 2,5 HP monovoltaje.",
        primary_use="Taller y pintura intermitente",
        power_source="Red eléctrica (220 V)",
        specs={
            "volumen_tanque": make_spec("volumen_tanque", "Volumen del tanque", "50 L", "L", 50.0, "L", "Capacidad geométrica nominal", "LC2550B-8", "Ficha técnica oficial Lüsqtoff", "https://www.lusqtoff.com.ar/productos/compresor-de-aire-o-25-hp-50-lts-lc2550b-8", "pág. 1", "declarado"),
            "potencia_motor": make_spec("potencia_motor", "Potencia declarada", "2,5 HP / 1750 W", "HP", 2.5, "HP", "Potencia eléctrica absorbida nominal", "LC2550B-8", "Ficha técnica oficial Lüsqtoff", "https://www.lusqtoff.com.ar/productos/compresor-de-aire-o-25-hp-50-lts-lc2550b-8", "pág. 1", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión máxima de corte", "115 PSI (8 bar)", "PSI", 8.0, "bar", "Corte por presostato de fábrica", "LC2550B-8", "Ficha técnica oficial Lüsqtoff", "https://www.lusqtoff.com.ar/productos/compresor-de-aire-o-25-hp-50-lts-lc2550b-8", "pág. 1", "declarado"),
            "caudal_aspirado": make_spec("caudal_aspirado", "Caudal de flujo declarado", "206 L/min", "L/min", 206.0, "L/min", "Aspiración teórica; no indica salida a presión de trabajo", "LC2550B-8", "Ficha técnica oficial Lüsqtoff", "https://www.lusqtoff.com.ar/productos/compresor-de-aire-o-25-hp-50-lts-lc2550b-8", "pág. 1", "declarado", notes="La ficha no publica FAD (entrega de aire libre) a 4 bar o 7 bar."),
            "lubricacion": make_spec("lubricacion", "Sistema de lubricación", "Por aceite", "tipo", 0.0, "tipo", "Cárter con visor de nivel", "LC2550B-8", "Ficha técnica oficial Lüsqtoff", "https://www.lusqtoff.com.ar/productos/compresor-de-aire-o-25-hp-50-lts-lc2550b-8", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso neto", "30 kg", "kg", 30.0, "kg", "Equipo sin accesorios de acople", "LC2550B-8", "Ficha técnica oficial Lüsqtoff", "https://www.lusqtoff.com.ar/productos/compresor-de-aire-o-25-hp-50-lts-lc2550b-8", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("LC2550B-8", "Argentina", "220 V / 50 Hz", "IRAM 2073 Tipo I", "Monofásico")],
        kits=[KitOption("LC2550B-8-STD", "Compresor 50L con ruedas de goma, pie antivibratorio y filtro de aire", "No aplica", "No aplica", ["Ruedas", "Pie de goma", "Filtro de aire", "Tapón de aceite"])],
        commercial_offers=[CommercialOffer("Distribuidor Oficial Lüsqtoff", "Mercado Libre", "https://meli.la/2dyFK5e", 274999.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=[
            "El caudal de 206 L/min es aspirado; no debe interpretarse como caudal continuo entregado a 6 o 7 bar.",
            "Requiere control de aceite previo al primer arranque y asentamiento inicial según manual."
        ],
        primary_sources=[{"label": "Ficha oficial Lüsqtoff LC2550B-8", "url": "https://www.lusqtoff.com.ar/productos/compresor-de-aire-o-25-hp-50-lts-lc2550b-8"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="gamma-g2802ar",
        brand="Gamma",
        commercial_name="G2802AR (50 Litros)",
        mpn="G2802AR",
        category="compresores",
        summary="Compresor de aire monofásico con tanque de 50 L, cabezal lubricado y discrepancia documentada de potencia entre manual y catálogo.",
        primary_use="Taller y mantenimiento",
        power_source="Red eléctrica (220 V)",
        specs={
            "volumen_tanque": make_spec("volumen_tanque", "Volumen del tanque", "50 L", "L", 50.0, "L", "Capacidad geométrica", "G2802AR", "Manual Gamma G2802AR", "https://www.gammaherramientas.com.ar/web/wp-content/uploads/compresores_compresor-de-50-litros_G2802AR-102-manual.pdf", "pág. 2", "declarado"),
            "potencia_motor": make_spec("potencia_motor", "Potencia declarada", "2,5 HP en manual / 2,0 HP en web", "HP", 2.5, "HP", "Discrepancia entre manual oficial y web comercial", "G2802AR", "Manual Gamma G2802AR", "https://www.gammaherramientas.com.ar/web/wp-content/uploads/compresores_compresor-de-50-litros_G2802AR-102-manual.pdf", "pág. 2", "contradictorio", notes="El manual de servicio declara 2,5 HP (1,85 kW), mientras que la web oficial imprime 2,0 HP (1,5 kW)."),
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "8 bar (116 PSI)", "bar", 8.0, "bar", "Corte presostato", "G2802AR", "Manual Gamma G2802AR", "https://www.gammaherramientas.com.ar/web/wp-content/uploads/compresores_compresor-de-50-litros_G2802AR-102-manual.pdf", "pág. 2", "declarado"),
            "caudal_desplazado": make_spec("caudal_desplazado", "Desplazamiento teórico", "203 L/min", "L/min", 203.0, "L/min", "Desplazamiento volumétrico teórico; no FAD", "G2802AR", "Manual Gamma G2802AR", "https://www.gammaherramientas.com.ar/web/wp-content/uploads/compresores_compresor-de-50-litros_G2802AR-102-manual.pdf", "pág. 2", "declarado"),
            "aceite_mantenimiento": make_spec("aceite_mantenimiento", "Especificación de aceite", "SAE30 (>10°C) / SAE10 (<10°C)", "tipo", 0.0, "tipo", "L-DAB100 / L-DAB68", "G2802AR", "Manual Gamma G2802AR", "https://www.gammaherramientas.com.ar/web/wp-content/uploads/compresores_compresor-de-50-litros_G2802AR-102-manual.pdf", "pág. 8", "declarado"),
            "peso": make_spec("peso", "Peso neto", "27 kg en web / 29 kg en manual", "kg", 27.0, "kg", "Según web comercial", "G2802AR", "Página Gamma G2802AR", "https://www.gammaherramientas.com.ar/producto/compresor-de-50-litros/", "pág. 1", "contradictorio"),
        },
        variants=[RegionalVariant("G2802AR", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Monofásico")],
        kits=[KitOption("G2802AR-STD", "Equipo base con ruedas y filtro", "No aplica", "No aplica", ["Ruedas", "Manivela de arrastre", "Filtro"])],
        commercial_offers=[CommercialOffer("Distribuidor Gamma", "Mercado Libre", "https://meli.la/2802GMA", 289900.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[
            ContradictionRecord(
                spec_key="potencia_motor",
                field_name="Potencia de motor",
                source_a_name="Manual Gamma G2802AR (PDF oficial)",
                source_a_value="2,5 HP (1850 W)",
                source_a_url="https://www.gammaherramientas.com.ar/web/wp-content/uploads/compresores_compresor-de-50-litros_G2802AR-102-manual.pdf",
                source_b_name="Web de Producto Gamma",
                source_b_value="2,0 HP (1500 W)",
                source_b_url="https://www.gammaherramientas.com.ar/producto/compresor-de-50-litros/",
                editorial_note="Conservamos ambas fuentes sin deducir cuál es correcta. Se aconseja verificar la placa metálica de la unidad física adquirida."
            )
        ],
        limits_and_warnings=[
            "Discrepancia documentada de potencia: confirmar código en la placa antes de dimensionar circuito eléctrico.",
            "Desplazamiento de 203 L/min no equivale a caudal a 6 bar de trabajo."
        ],
        primary_sources=[
            {"label": "Manual Gamma G2802AR", "url": "https://www.gammaherramientas.com.ar/web/wp-content/uploads/compresores_compresor-de-50-litros_G2802AR-102-manual.pdf"},
            {"label": "Web oficial Gamma G2802AR", "url": "https://www.gammaherramientas.com.ar/producto/compresor-de-50-litros/"}
        ],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="einhell-te-ac-270-50-silent",
        brand="Einhell",
        commercial_name="TE-AC 270/50 Silent",
        mpn="4010451",
        category="compresores",
        summary="Compresor silencioso (70 dB(A) LpA) libre de aceite con tanque de 50 L y datos de caudal efectivo a presiones calibradas (4 y 7 bar).",
        primary_use="Taller cerrado, aerografía y aplicaciones de bajo ruido",
        power_source="Red eléctrica (220-240 V)",
        specs={
            "volumen_tanque": make_spec("volumen_tanque", "Volumen del tanque", "50 L", "L", 50.0, "L", "Capacidad geométrica", "4010451", "Ficha técnica oficial Einhell", "https://www.einhell.com.ar/p/4010451-te-ac-270-50-silent/", "pág. 1", "declarado"),
            "potencia_motor": make_spec("potencia_motor", "Potencia absorbida", "1650 W", "W", 1650.0, "W", "2,2 HP máx. S3 50%", "4010451", "Ficha técnica oficial Einhell", "https://www.einhell.com.ar/p/4010451-te-ac-270-50-silent/", "pág. 1", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión máxima de servicio", "10 bar", "bar", 10.0, "bar", "Corte por presostato", "4010451", "Ficha técnica oficial Einhell", "https://www.einhell.com.ar/p/4010451-te-ac-270-50-silent/", "pág. 1", "declarado"),
            "caudal_aspirado": make_spec("caudal_aspirado", "Capacidad de succión", "270 L/min", "L/min", 270.0, "L/min", "Aspiración teórica", "4010451", "Ficha técnica oficial Einhell", "https://www.einhell.com.ar/p/4010451-te-ac-270-50-silent/", "pág. 1", "declarado"),
            "caudal_salida_4bar": make_spec("caudal_salida_4bar", "Caudal de salida a 4 bar", "135 L/min", "L/min", 135.0, "L/min", "Medición efectiva a 4 bar de trabajo", "4010451", "Ficha técnica oficial Einhell", "https://www.einhell.com.ar/p/4010451-te-ac-270-50-silent/", "pág. 1", "declarado"),
            "caudal_salida_7bar": make_spec("caudal_salida_7bar", "Caudal de salida a 7 bar", "98 L/min", "L/min", 98.0, "L/min", "Medición efectiva a 7 bar de trabajo", "4010451", "Ficha técnica oficial Einhell", "https://www.einhell.com.ar/p/4010451-te-ac-270-50-silent/", "pág. 1", "declarado"),
            "nivel_sonoro": make_spec("nivel_sonoro", "Presión acústica declarada", "70 dB(A)", "dB", 70.0, "dB", "LpA según ficha Einhell Argentina", "4010451", "Ficha técnica oficial Einhell", "https://www.einhell.com.ar/p/4010451-te-ac-270-50-silent/", None, "declarado", notes="Ficha Einhell Argentina declara 70 dB(A) LpA; no extrapolar a otro punto de medición."),
            "peso": make_spec("peso", "Peso del producto", "34,45 kg", "kg", 34.45, "kg", "Neto", "4010451", "Ficha técnica oficial Einhell", "https://www.einhell.com.ar/p/4010451-te-ac-270-50-silent/", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("4010451", "Argentina", "220-240 V / 50 Hz", "IRAM 2073", "Garantía oficial 10 años contra corrosión de tanque")],
        kits=[KitOption("4010451-BASE", "Compresor Silent libre de aceite con válvula reductora y 2 manómetros", "No aplica", "No aplica", ["Ruedas de transporte", "Pie con amortiguador", "2 manómetros"])],
        commercial_offers=[CommercialOffer("Tienda Oficial Einhell Argentina", "Mercado Libre", "https://meli.la/2EINH50S", 589000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=[
            "El caudal a 7 bar es de 98 L/min; no debe compararse directamente con herramientas neumáticas que consumen a 6,3 bar sin solicitar la entrega intermedia.",
            "Régimen de motor S3 50% intermitente; no está diseñado para servicio continuo industrial 100% ininterrumpido."
        ],
        primary_sources=[{"label": "Ficha oficial Einhell TE-AC 270/50 Silent", "url": "https://www.einhell.com.ar/p/4010451-te-ac-270-50-silent/"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="lusqtoff-lc2550vs",
        brand="Lüsqtoff",
        commercial_name="LC-2550VS (50L Vertical)",
        mpn="LC-2550VS",
        category="compresores",
        summary="Compresor vertical de 50 L sin aceite pensado para talleres con superficie de suelo reducida.",
        primary_use="Taller compacto y transporte",
        power_source="Red eléctrica (220 V)",
        specs={
            "volumen_tanque": make_spec("volumen_tanque", "Volumen del tanque", "50 L vertical", "L", 50.0, "L", "Geométrica", "LC-2550VS", "Ficha técnica Lüsqtoff", "https://lusqtoff.com.ar/ver-producto/LC-2550VS", "pág. 1", "declarado"),
            "potencia_motor": make_spec("potencia_motor", "Potencia declarada", "2,5 HP (1750 W)", "HP", 2.5, "HP", "Nominal", "LC-2550VS", "Ficha técnica Lüsqtoff", "https://lusqtoff.com.ar/ver-producto/LC-2550VS", "pág. 1", "declarado"),
            "caudal_flujo": make_spec("caudal_flujo", "Caudal anunciado", "230 L/min", "L/min", 230.0, "L/min", "Aspiración sin presión indicada", "LC-2550VS", "Ficha técnica Lüsqtoff", "https://lusqtoff.com.ar/ver-producto/LC-2550VS", "pág. 1", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "8 bar (115 PSI)", "bar", 8.0, "bar", "Corte presostato", "LC-2550VS", "Ficha técnica Lüsqtoff", "https://lusqtoff.com.ar/ver-producto/LC-2550VS", "pág. 1", "declarado"),
            "nivel_sonoro": make_spec("nivel_sonoro", "Nivel de ruido", "72 dB", "dB", 72.0, "dB", "Condiciones acústicas no publicadas", "LC-2550VS", "Ficha técnica Lüsqtoff", "https://lusqtoff.com.ar/ver-producto/LC-2550VS", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("LC-2550VS", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Vertical")],
        kits=[KitOption("LC-2550VS-STD", "Compresor vertical con manillar y ruedas", "No aplica", "No aplica", ["Ruedas", "Manillar"])],
        commercial_offers=[CommercialOffer("Distribuidor Lüsqtoff", "Mercado Libre", "https://meli.la/1Rjz39S", 319000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["El formato vertical ahorra espacio pero eleva el centro de gravedad en traslados."],
        primary_sources=[{"label": "Ficha oficial Lüsqtoff LC-2550VS", "url": "https://lusqtoff.com.ar/ver-producto/LC-2550VS"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="lusqtoff-lcs50-8",
        brand="Lüsqtoff",
        commercial_name="LCS50-8 Silent (50 Litros)",
        mpn="LCS50-8",
        category="compresores",
        summary="Compresor silencioso libre de aceite de 50 L con cabezal de pistones de baja fricción.",
        primary_use="Odontología, laboratorios y talleres silenciosos",
        power_source="Red eléctrica (220 V)",
        specs={
            "volumen_tanque": make_spec("volumen_tanque", "Volumen del tanque", "50 L", "L", 50.0, "L", "Nominal", "LCS50-8", "Ficha oficial Lüsqtoff", "https://lusqtoff.com.ar/productos/compresor-de-aire-sin-aceite-50l", "pág. 1", "declarado"),
            "potencia_motor": make_spec("potencia_motor", "Potencia declarada", "2,0 HP (1600 W)", "HP", 2.0, "HP", "Nominal", "LCS50-8", "Ficha oficial Lüsqtoff", "https://lusqtoff.com.ar/productos/compresor-de-aire-sin-aceite-50l", "pág. 1", "declarado"),
            "caudal_flujo": make_spec("caudal_flujo", "Caudal anunciado", "105 L/min", "L/min", 105.0, "L/min", "Condición no indicada", "LCS50-8", "Ficha oficial Lüsqtoff", "https://lusqtoff.com.ar/productos/compresor-de-aire-sin-aceite-50l", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso neto", "30 kg", "kg", 30.0, "kg", "Sin embalaje", "LCS50-8", "Ficha oficial Lüsqtoff", "https://lusqtoff.com.ar/productos/compresor-de-aire-sin-aceite-50l", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("LCS50-8", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Silent")],
        kits=[KitOption("LCS50-8-STD", "Compresor sin aceite silencioso", "No aplica", "No aplica", ["Filtros silenciosos", "Ruedas"])],
        commercial_offers=[CommercialOffer("Distribuidor Lüsqtoff", "Mercado Libre", "https://meli.la/27nVFRy", 345000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["105 L/min representa un caudal moderado; comprobar consumo de herramienta antes de conectar."],
        primary_sources=[{"label": "Ficha oficial Lüsqtoff LCS50-8", "url": "https://lusqtoff.com.ar/productos/compresor-de-aire-sin-aceite-50l"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="lusqtoff-lc3550bk",
        brand="Lüsqtoff",
        commercial_name="LC-3550BK Bicilíndrico (50L)",
        mpn="LC-3550BK",
        category="compresores",
        summary="Compresor de alta recuperación con cabezal bicilíndrico en V de 3,5 HP y tanque de 50 L.",
        primary_use="Pintura y herramientas neumáticas exigentes",
        power_source="Red eléctrica (220 V)",
        specs={
            "volumen_tanque": make_spec("volumen_tanque", "Volumen del tanque", "50 L", "L", 50.0, "L", "Nominal", "LC-3550BK", "Ficha oficial Lüsqtoff", "https://lusqtoff.com.ar/ver-producto/LC-3550BK", "pág. 1", "declarado"),
            "potencia_motor": make_spec("potencia_motor", "Potencia declarada", "3,5 HP", "HP", 3.5, "HP", "Bicilíndrico en V", "LC-3550BK", "Ficha oficial Lüsqtoff", "https://lusqtoff.com.ar/ver-producto/LC-3550BK", "pág. 1", "declarado"),
            "caudal_anunciado": make_spec("caudal_anunciado", "Caudal de flujo", "300 L/min", "L/min", 300.0, "L/min", "Condición no precisada en ficha", "LC-3550BK", "Ficha oficial Lüsqtoff", "https://lusqtoff.com.ar/ver-producto/LC-3550BK", "pág. 1", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "8 bar (115 PSI)", "bar", 8.0, "bar", "Corte presostato", "LC-3550BK", "Ficha oficial Lüsqtoff", "https://lusqtoff.com.ar/ver-producto/LC-3550BK", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("LC-3550BK", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Bicilíndrico")],
        kits=[KitOption("LC-3550BK-KIT", "Compresor bicilíndrico con kit de manguera espiralada", "No aplica", "No aplica", ["Manguera espiralada 5m", "Ruedas"])],
        commercial_offers=[CommercialOffer("Distribuidor Oficial", "Mercado Libre", "https://meli.la/21xNVUN", 389000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Mayor corriente de arranque por cabezal bicilíndrico; requiere instalación eléctrica adecuada sin cables alargadores finos."],
        primary_sources=[{"label": "Ficha oficial Lüsqtoff LC-3550BK", "url": "https://lusqtoff.com.ar/ver-producto/LC-3550BK"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="lusqtoff-lc0122",
        brand="Lüsqtoff",
        commercial_name="LC-0122 (24 Litros)",
        mpn="LC-0122",
        category="compresores",
        summary="Compresor compacto de 24 L y 1,5 HP para inflado, soplado y clavado intermitente.",
        primary_use="Hogar y bricolaje",
        power_source="Red eléctrica (220 V)",
        specs={
            "volumen_tanque": make_spec("volumen_tanque", "Volumen del tanque", "24 L", "L", 24.0, "L", "Nominal", "LC-0122", "Manual oficial Lüsqtoff LC-0122", "https://www.lusqtoff.com.ar/2023/uploads/Productos/16.%20COMPRESORES/LC-0122/MANUAL/LC-0122.pdf", "pág. 1", "declarado"),
            "potencia_motor": make_spec("potencia_motor", "Potencia declarada", "1,5 HP (1100 W)", "HP", 1.5, "HP", "Nominal", "LC-0122", "Manual oficial Lüsqtoff LC-0122", "https://www.lusqtoff.com.ar/2023/uploads/Productos/16.%20COMPRESORES/LC-0122/MANUAL/LC-0122.pdf", "pág. 1", "declarado"),
            "caudal_flujo": make_spec("caudal_flujo", "Caudal anunciado", "140 L/min", "L/min", 140.0, "L/min", "Aspiración teórica", "LC-0122", "Manual oficial Lüsqtoff LC-0122", "https://www.lusqtoff.com.ar/2023/uploads/Productos/16.%20COMPRESORES/LC-0122/MANUAL/LC-0122.pdf", "pág. 1", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "8 bar (115 PSI)", "bar", 8.0, "bar", "Corte presostato", "LC-0122", "Manual oficial Lüsqtoff LC-0122", "https://www.lusqtoff.com.ar/2023/uploads/Productos/16.%20COMPRESORES/LC-0122/MANUAL/LC-0122.pdf", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("LC-0122", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Monofásico")],
        kits=[KitOption("LC-0122-STD", "Compresor 24L con ruedas y tapón", "No aplica", "No aplica", ["Ruedas", "Filtro"])],
        commercial_offers=[CommercialOffer("Distribuidor Lüsqtoff", "Mercado Libre", "https://meli.la/19aFAKp", 199999.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["El tanque de 24 L se agota rápidamente en soplado continuo o pistolas de pintura de alto consumo."],
        primary_sources=[{"label": "Manual oficial Lüsqtoff LC-0122", "url": "https://www.lusqtoff.com.ar/2023/uploads/Productos/16.%20COMPRESORES/LC-0122/MANUAL/LC-0122.pdf"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="lusqtoff-lc2024b",
        brand="Lüsqtoff",
        commercial_name="LC2024B (24 Litros)",
        mpn="LC2024B",
        category="compresores",
        summary="Compresor de 24 L lubricado con motor de 2,0 HP y mayor capacidad de recuperación.",
        primary_use="Bricolaje avanzado y mantenimiento",
        power_source="Red eléctrica (220 V)",
        specs={
            "volumen_tanque": make_spec("volumen_tanque", "Volumen del tanque", "24 L", "L", 24.0, "L", "Nominal", "LC2024B", "Ficha técnica Lüsqtoff", "https://lusqtoff.com.ar/ver-producto/LC2024B", "pág. 1", "declarado"),
            "potencia_motor": make_spec("potencia_motor", "Potencia declarada", "2,0 HP (1500 W)", "HP", 2.0, "HP", "Nominal", "LC2024B", "Ficha técnica Lüsqtoff", "https://lusqtoff.com.ar/ver-producto/LC2024B", "pág. 1", "declarado"),
            "caudal_flujo": make_spec("caudal_flujo", "Caudal declarado", "150 L/min", "L/min", 150.0, "L/min", "Aspiración", "LC2024B", "Ficha técnica Lüsqtoff", "https://lusqtoff.com.ar/ver-producto/LC2024B", "pág. 1", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión de corte", "8 bar", "bar", 8.0, "bar", "Corte", "LC2024B", "Ficha técnica Lüsqtoff", "https://lusqtoff.com.ar/ver-producto/LC2024B", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("LC2024B", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Monofásico")],
        kits=[KitOption("LC2024B-STD", "Compresor 24L lubricado", "No aplica", "No aplica", ["Ruedas", "Tapón aceite"])],
        commercial_offers=[CommercialOffer("Distribuidor Oficial", "Mercado Libre", "https://meli.la/2024BLQ", 219000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Comprobar nivel de aceite periódicamente antes de cada jornada."],
        primary_sources=[{"label": "Ficha técnica Lüsqtoff LC2024B", "url": "https://lusqtoff.com.ar/ver-producto/LC2024B"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="gamma-g2801ar",
        brand="Gamma",
        commercial_name="G2801AR (24 Litros)",
        mpn="G2801AR",
        category="compresores",
        summary="Compresor monofásico de 24 L lubricado por aceite con 2 HP declarados.",
        primary_use="Hogar y taller ligero",
        power_source="Red eléctrica (220 V)",
        specs={
            "volumen_tanque": make_spec("volumen_tanque", "Volumen del tanque", "24 L", "L", 24.0, "L", "Nominal", "G2801AR", "Ficha oficial Gamma", "https://www.gammaherramientas.com.ar/producto/compresor-de-24-litros/", "pág. 1", "declarado"),
            "potencia_motor": make_spec("potencia_motor", "Potencia declarada", "2,0 HP", "HP", 2.0, "HP", "Nominal", "G2801AR", "Ficha oficial Gamma", "https://www.gammaherramientas.com.ar/producto/compresor-de-24-litros/", "pág. 1", "declarado"),
            "caudal_desplazado": make_spec("caudal_desplazado", "Desplazamiento teórico", "150 L/min", "L/min", 150.0, "L/min", "Desplazamiento volumétrico", "G2801AR", "Ficha oficial Gamma", "https://www.gammaherramientas.com.ar/producto/compresor-de-24-litros/", "pág. 1", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "8 bar", "bar", 8.0, "bar", "Corte", "G2801AR", "Ficha oficial Gamma", "https://www.gammaherramientas.com.ar/producto/compresor-de-24-litros/", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("G2801AR", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Monofásico")],
        kits=[KitOption("G2801AR-STD", "Compresor con ruedas y filtro", "No aplica", "No aplica", ["Ruedas", "Filtro"])],
        commercial_offers=[CommercialOffer("Distribuidor Gamma", "Mercado Libre", "https://meli.la/14tM2Xh", 225000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["El caudal desplazado es un cálculo teórico de cilindrada y rpm; no refleja FAD bajo carga."],
        primary_sources=[{"label": "Ficha oficial Gamma G2801AR", "url": "https://www.gammaherramientas.com.ar/producto/compresor-de-24-litros/"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="einhell-th-ac-240-24",
        brand="Einhell",
        commercial_name="TH-AC 240/24 /1 OF",
        mpn="4020515",
        category="compresores",
        summary="Compresor sin aceite de 24 L compacto con salida a presión calibrada y motor sin mantenimiento de aceite.",
        primary_use="Bricolaje doméstico y clavado",
        power_source="Red eléctrica (220-240 V)",
        specs={
            "volumen_tanque": make_spec("volumen_tanque", "Volumen del tanque", "24 L", "L", 24.0, "L", "Nominal", "4020515", "Ficha técnica Einhell", "https://www.einhell.com.ar/p/4020515-th-ac-240-24-1-of/", "pág. 1", "declarado"),
            "potencia_motor": make_spec("potencia_motor", "Potencia", "1500 W", "W", 1500.0, "W", "S3 25%", "4020515", "Ficha técnica Einhell", "https://www.einhell.com.ar/p/4020515-th-ac-240-24-1-of/", "pág. 1", "declarado"),
            "caudal_aspirado": make_spec("caudal_aspirado", "Capacidad de succión", "240 L/min", "L/min", 240.0, "L/min", "Aspiración", "4020515", "Ficha técnica Einhell", "https://www.einhell.com.ar/p/4020515-th-ac-240-24-1-of/", "pág. 1", "declarado"),
            "caudal_salida_4bar": make_spec("caudal_salida_4bar", "Caudal de salida a 4 bar", "110 L/min", "L/min", 110.0, "L/min", "Medición a 4 bar", "4020515", "Ficha técnica Einhell", "https://www.einhell.com.ar/p/4020515-th-ac-240-24-1-of/", "pág. 1", "declarado"),
            "caudal_salida_7bar": make_spec("caudal_salida_7bar", "Caudal de salida a 7 bar", "75 L/min", "L/min", 75.0, "L/min", "Medición a 7 bar", "4020515", "Ficha técnica Einhell", "https://www.einhell.com.ar/p/4020515-th-ac-240-24-1-of/", "pág. 1", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "8 bar", "bar", 8.0, "bar", "Corte", "4020515", "Ficha técnica Einhell", "https://www.einhell.com.ar/p/4020515-th-ac-240-24-1-of/", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("4020515", "Argentina", "220-240 V / 50 Hz", "IRAM 2073", "Sin aceite")],
        kits=[KitOption("4020515-STD", "Compresor vertical/horizontal sin aceite", "No aplica", "No aplica", ["Ruedas", "Manómetro"])],
        commercial_offers=[CommercialOffer("Tienda Oficial Einhell", "Mercado Libre", "https://meli.la/2NsPCBP", 259000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Régimen S3 25% exige ciclos de pausa para evitar sobrecalentamiento en trabajos continuados."],
        primary_sources=[{"label": "Ficha oficial Einhell TH-AC 240/24 /1 OF", "url": "https://www.einhell.com.ar/p/4020515-th-ac-240-24-1-of/"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="bta-25-litros",
        brand="BTA",
        commercial_name="BTA 25 Litros Monofásico",
        mpn="823125",
        category="compresores",
        summary="Compresor de 25 L lubricado con 2,0 HP para taller liviano.",
        primary_use="Bricolaje y taller",
        power_source="Red eléctrica (220 V)",
        specs={
            "volumen_tanque": make_spec("volumen_tanque", "Volumen del tanque", "25 L", "L", 25.0, "L", "Nominal", "823125", "Catálogo BTA Tools", "https://www.btatools.com.ar/productos/compresores", "pág. 1", "declarado"),
            "potencia_motor": make_spec("potencia_motor", "Potencia", "2,0 HP (1500 W)", "HP", 2.0, "HP", "Nominal", "823125", "Catálogo BTA Tools", "https://www.btatools.com.ar/productos/compresores", "pág. 1", "declarado"),
            "caudal_desplazado": make_spec("caudal_desplazado", "Caudal de aire", "145 L/min", "L/min", 145.0, "L/min", "Aspirado", "823125", "Catálogo BTA Tools", "https://www.btatools.com.ar/productos/compresores", "pág. 1", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "8 bar (115 PSI)", "bar", 8.0, "bar", "Corte", "823125", "Catálogo BTA Tools", "https://www.btatools.com.ar/productos/compresores", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("823125", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Monofásico")],
        kits=[KitOption("823125-STD", "Compresor 25L con ruedas", "No aplica", "No aplica", ["Ruedas", "Tapón"])],
        commercial_offers=[CommercialOffer("Distribuidor BTA", "Mercado Libre", "https://meli.la/14USeGB", 215000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["145 L/min aspirado no representa entrega continua a presión de lijado o pintura."],
        primary_sources=[{"label": "Catálogo BTA Compresores", "url": "https://www.btatools.com.ar/productos/compresores"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="bta-24-oilfree",
        brand="BTA",
        commercial_name="BTA 24 Litros Oil-Free Silent",
        mpn="823124",
        category="compresores",
        summary="Compresor sin aceite de 24 L con bajo nivel de ruido.",
        primary_use="Aplicaciones limpias y bajo ruido",
        power_source="Red eléctrica (220 V)",
        specs={
            "volumen_tanque": make_spec("volumen_tanque", "Volumen del tanque", "24 L", "L", 24.0, "L", "Nominal", "823124", "Catálogo BTA Tools", "https://www.btatools.com.ar/productos/compresores", "pág. 1", "declarado"),
            "potencia_motor": make_spec("potencia_motor", "Potencia", "1,5 HP (1100 W)", "HP", 1.5, "HP", "Nominal", "823124", "Catálogo BTA Tools", "https://www.btatools.com.ar/productos/compresores", "pág. 1", "declarado"),
            "caudal_desplazado": make_spec("caudal_desplazado", "Caudal declarado", "120 L/min", "L/min", 120.0, "L/min", "Aspirado", "823124", "Catálogo BTA Tools", "https://www.btatools.com.ar/productos/compresores", "pág. 1", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "8 bar", "bar", 8.0, "bar", "Corte", "823124", "Catálogo BTA Tools", "https://www.btatools.com.ar/productos/compresores", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("823124", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Sin aceite")],
        kits=[KitOption("823124-STD", "Compresor sin aceite con filtros acústicos", "No aplica", "No aplica", ["Ruedas", "Filtro"])],
        commercial_offers=[CommercialOffer("Distribuidor BTA", "Mercado Libre", "https://meli.la/2kTMPof", 265000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Baja producción de aire; indicado para grapas, clavos o inflado."],
        primary_sources=[{"label": "Catálogo BTA Compresores", "url": "https://www.btatools.com.ar/productos/compresores"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="bta-50-litros",
        brand="BTA",
        commercial_name="BTA 50 Litros Monofásico",
        mpn="823150",
        category="compresores",
        summary="Compresor de 50 L con motor de 2,5 HP para pintura y soplado en taller.",
        primary_use="Taller y pintura",
        power_source="Red eléctrica (220 V)",
        specs={
            "volumen_tanque": make_spec("volumen_tanque", "Volumen del tanque", "50 L", "L", 50.0, "L", "Nominal", "823150", "Catálogo BTA Tools", "https://www.btatools.com.ar/productos/compresores", "pág. 1", "declarado"),
            "potencia_motor": make_spec("potencia_motor", "Potencia", "2,5 HP", "HP", 2.5, "HP", "Nominal", "823150", "Catálogo BTA Tools", "https://www.btatools.com.ar/productos/compresores", "pág. 1", "declarado"),
            "caudal_desplazado": make_spec("caudal_desplazado", "Caudal declarado", "195 L/min", "L/min", 195.0, "L/min", "Aspirado", "823150", "Catálogo BTA Tools", "https://www.btatools.com.ar/productos/compresores", "pág. 1", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "8 bar", "bar", 8.0, "bar", "Corte", "823150", "Catálogo BTA Tools", "https://www.btatools.com.ar/productos/compresores", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("823150", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Monofásico")],
        kits=[KitOption("823150-STD", "Compresor 50L lubricado con ruedas", "No aplica", "No aplica", ["Ruedas", "Manómetro doble"])],
        commercial_offers=[CommercialOffer("Distribuidor BTA", "Mercado Libre", "https://meli.la/1nobM6T", 285000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Duplicar el tanque de 25 a 50 L amplía la reserva inicial, pero la bomba repone al ritmo de 195 L/min aspirados."],
        primary_sources=[{"label": "Catálogo BTA Compresores", "url": "https://www.btatools.com.ar/productos/compresores"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="lusqtoff-lc30100",
        brand="Lüsqtoff",
        commercial_name="LC-30100 a Correa (100 Litros)",
        mpn="LC-30100",
        category="compresores",
        summary="Compresor a correa con cabezal de 2 cilindros en línea, tanque de 100 L y motor de 3 HP.",
        primary_use="Taller mecánico y gomería",
        power_source="Red eléctrica (220 V)",
        specs={
            "volumen_tanque": make_spec("volumen_tanque", "Volumen del tanque", "100 L", "L", 100.0, "L", "Nominal", "LC-30100", "Manual oficial Lüsqtoff LC-30100", "https://lusqtoff.com.ar/2023/uploads/Productos/16.%20COMPRESORES/LC-30100/MANUAL/LC-30100.pdf", "pág. 1", "declarado"),
            "potencia_motor": make_spec("potencia_motor", "Potencia", "3,0 HP (2200 W)", "HP", 3.0, "HP", "Nominal", "LC-30100", "Manual oficial Lüsqtoff LC-30100", "https://lusqtoff.com.ar/2023/uploads/Productos/16.%20COMPRESORES/LC-30100/MANUAL/LC-30100.pdf", "pág. 1", "declarado"),
            "caudal_flujo": make_spec("caudal_flujo", "Caudal de aire", "335 L/min", "L/min", 335.0, "L/min", "Desplazamiento; condición no indicada", "LC-30100", "Manual oficial Lüsqtoff LC-30100", "https://lusqtoff.com.ar/2023/uploads/Productos/16.%20COMPRESORES/LC-30100/MANUAL/LC-30100.pdf", "pág. 1", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "8 bar (115 PSI)", "bar", 8.0, "bar", "Corte", "LC-30100", "Manual oficial Lüsqtoff LC-30100", "https://lusqtoff.com.ar/2023/uploads/Productos/16.%20COMPRESORES/LC-30100/MANUAL/LC-30100.pdf", "pág. 1", "declarado"),
            "transmision": make_spec("transmision", "Tipo de transmisión", "A correa con poleas", "tipo", 0.0, "tipo", "Baja velocidad de giro en cabezal", "LC-30100", "Manual oficial Lüsqtoff LC-30100", "https://lusqtoff.com.ar/2023/uploads/Productos/16.%20COMPRESORES/LC-30100/MANUAL/LC-30100.pdf", "pág. 2", "declarado"),
        },
        variants=[RegionalVariant("LC-30100", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Monofásico a correa")],
        kits=[KitOption("LC-30100-STD", "Compresor a correa con protector de polea metálico y ruedas", "No aplica", "No aplica", ["Ruedas reforzadas", "Reja de protección de polea"])],
        commercial_offers=[CommercialOffer("Distribuidor Oficial", "Mercado Libre", "https://meli.la/2r6QkaT", 649000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Mando a correa reduce rpm del cabezal y temperatura de trabajo, pero requiere tensión periódica de correa."],
        primary_sources=[{"label": "Manual oficial Lüsqtoff LC-30100", "url": "https://lusqtoff.com.ar/2023/uploads/Productos/16.%20COMPRESORES/LC-30100/MANUAL/LC-30100.pdf"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="lusqtoff-lc40100-8",
        brand="Lüsqtoff",
        commercial_name="LC40100-8 Directo (100 Litros)",
        mpn="LC40100-8",
        category="compresores",
        summary="Compresor de 100 L con mando directo bicilíndrico de 4 HP para rápida recuperación.",
        primary_use="Taller exigente",
        power_source="Red eléctrica (220 V)",
        specs={
            "volumen_tanque": make_spec("volumen_tanque", "Volumen del tanque", "100 L", "L", 100.0, "L", "Nominal", "LC40100-8", "Ficha técnica Lüsqtoff", "https://lusqtoff.com.ar/productos/LC40100-8", "pág. 1", "declarado"),
            "potencia_motor": make_spec("potencia_motor", "Potencia", "4,0 HP (3000 W)", "HP", 4.0, "HP", "Nominal", "LC40100-8", "Ficha técnica Lüsqtoff", "https://lusqtoff.com.ar/productos/LC40100-8", "pág. 1", "declarado"),
            "caudal_flujo": make_spec("caudal_flujo", "Caudal declarado", "356 L/min", "L/min", 356.0, "L/min", "Aspirado; no FAD", "LC40100-8", "Ficha técnica Lüsqtoff", "https://lusqtoff.com.ar/productos/LC40100-8", "pág. 1", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión de corte", "8 bar", "bar", 8.0, "bar", "Corte", "LC40100-8", "Ficha técnica Lüsqtoff", "https://lusqtoff.com.ar/productos/LC40100-8", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso neto", "76 kg", "kg", 76.0, "kg", "Neto", "LC40100-8", "Ficha técnica Lüsqtoff", "https://lusqtoff.com.ar/productos/LC40100-8", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("LC40100-8", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Monofásico directo 4 HP")],
        kits=[KitOption("LC40100-8-STD", "Compresor bicilíndrico 100L", "No aplica", "No aplica", ["Ruedas", "Manillar"])],
        commercial_offers=[CommercialOffer("Distribuidor Oficial", "Mercado Libre", "https://meli.la/1GRiWbV", 675000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Elevado consumo en arranque (motor 4 HP monofásico); exige línea independiente de 20 A."],
        primary_sources=[{"label": "Ficha oficial Lüsqtoff LC40100-8", "url": "https://lusqtoff.com.ar/productos/LC40100-8"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="lusqtoff-lcs100-8",
        brand="Lüsqtoff",
        commercial_name="LCS100-8 Silent (100 Litros)",
        mpn="LCS100-8",
        category="compresores",
        summary="Compresor de 100 L sin aceite con 3 motores silenciosos independientes (3 x 1280 W).",
        primary_use="Laboratorios, clínicas y talleres de precisión",
        power_source="Red eléctrica (220 V)",
        specs={
            "volumen_tanque": make_spec("volumen_tanque", "Volumen del tanque", "100 L", "L", 100.0, "L", "Nominal", "LCS100-8", "Ficha oficial Lüsqtoff", "https://lusqtoff.com.ar/productos/LCS100-8", "pág. 1", "declarado"),
            "potencia_motor": make_spec("potencia_motor", "Potencia total", "3840 W (3 x 1280 W)", "W", 3840.0, "W", "Tres motores independientes", "LCS100-8", "Ficha oficial Lüsqtoff", "https://lusqtoff.com.ar/productos/LCS100-8", "pág. 1", "declarado"),
            "caudal_flujo": make_spec("caudal_flujo", "Caudal anunciado", "255 L/min", "L/min", 255.0, "L/min", "Condición no indicada", "LCS100-8", "Ficha oficial Lüsqtoff", "https://lusqtoff.com.ar/productos/LCS100-8", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso neto", "50,5 kg", "kg", 50.5, "kg", "Neto", "LCS100-8", "Ficha oficial Lüsqtoff", "https://lusqtoff.com.ar/productos/LCS100-8", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("LCS100-8", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Silent tri-motor")],
        kits=[KitOption("LCS100-8-STD", "Compresor tri-motor con 3 filtros de aire de bajo ruido", "No aplica", "No aplica", ["3 filtros silenciosos", "Ruedas"])],
        commercial_offers=[CommercialOffer("Distribuidor Oficial", "Mercado Libre", "https://meli.la/21fBeVj", 720000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Los 3 motores arrancan secuencialmente; comprobar que la tensión de red no caiga por debajo de 205 V en carga."],
        primary_sources=[{"label": "Ficha oficial Lüsqtoff LCS100-8", "url": "https://lusqtoff.com.ar/productos/LCS100-8"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="einhell-te-ac-430-90-10",
        brand="Einhell",
        commercial_name="TE-AC 430/90/10 a Correa (90L)",
        mpn="4010800",
        category="compresores",
        summary="Compresor a correa con tanque de 90 L, 10 bar de presión máxima y caudal de salida de 200 L/min a 7 bar.",
        primary_use="Pintura profesional y talleres automotrices",
        power_source="Red eléctrica (220-240 V)",
        specs={
            "volumen_tanque": make_spec("volumen_tanque", "Volumen del tanque", "90 L", "L", 90.0, "L", "Nominal", "4010800", "Ficha técnica oficial Einhell", "https://www.einhell.com.ar/p/4010800-te-ac-430-90-10/", "pág. 1", "declarado"),
            "potencia_motor": make_spec("potencia_motor", "Potencia", "3000 W", "W", 3000.0, "W", "Nominal", "4010800", "Ficha técnica oficial Einhell", "https://www.einhell.com.ar/p/4010800-te-ac-430-90-10/", "pág. 1", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "10 bar", "bar", 10.0, "bar", "Corte", "4010800", "Ficha técnica oficial Einhell", "https://www.einhell.com.ar/p/4010800-te-ac-430-90-10/", "pág. 1", "declarado"),
            "caudal_aspirado": make_spec("caudal_aspirado", "Capacidad de succión", "430 L/min", "L/min", 430.0, "L/min", "Aspiración", "4010800", "Ficha técnica oficial Einhell", "https://www.einhell.com.ar/p/4010800-te-ac-430-90-10/", "pág. 1", "declarado"),
            "caudal_salida_4bar": make_spec("caudal_salida_4bar", "Caudal de salida a 4 bar", "210 L/min", "L/min", 210.0, "L/min", "Medición a 4 bar", "4010800", "Ficha técnica oficial Einhell", "https://www.einhell.com.ar/p/4010800-te-ac-430-90-10/", "pág. 1", "declarado"),
            "caudal_salida_7bar": make_spec("caudal_salida_7bar", "Caudal de salida a 7 bar", "200 L/min", "L/min", 200.0, "L/min", "Medición a 7 bar", "4010800", "Ficha técnica oficial Einhell", "https://www.einhell.com.ar/p/4010800-te-ac-430-90-10/", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso neto", "68,35 kg", "kg", 68.35, "kg", "Neto", "4010800", "Ficha técnica oficial Einhell", "https://www.einhell.com.ar/p/4010800-te-ac-430-90-10/", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("4010800", "Argentina", "220-240 V / 50 Hz", "IRAM 2073", "A correa bicilíndrico")],
        kits=[KitOption("4010800-STD", "Compresor 90L a correa con ruedas grandes y manillar", "No aplica", "No aplica", ["Ruedas de goma", "Manillar de arrastre", "Doble manómetro"])],
        commercial_offers=[CommercialOffer("Tienda Oficial Einhell", "Mercado Libre", "https://meli.la/2EINH90", 895000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Salida de 200 L/min a 7 bar valida pistolas de pintura HVLP de consumo medio/alto, pero requiere verificar ciclo y diámetro de manguera (mínimo 9 mm ID)."],
        primary_sources=[{"label": "Ficha oficial Einhell TE-AC 430/90/10", "url": "https://www.einhell.com.ar/p/4010800-te-ac-430-90-10/"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="lusqtoff-lc30200-8",
        brand="Lüsqtoff",
        commercial_name="LC30200-8 Monofásico (200 Litros)",
        mpn="LC30200-8",
        category="compresores",
        summary="Compresor a correa con reserva de 200 L y motor monofásico de 3 HP.",
        primary_use="Taller industrial y procesos continuos",
        power_source="Red eléctrica (220 V)",
        specs={
            "volumen_tanque": make_spec("volumen_tanque", "Volumen del tanque", "200 L", "L", 200.0, "L", "Nominal", "LC30200-8", "Ficha oficial Lüsqtoff", "https://lusqtoff.com.ar/productos/LC30200-8", "pág. 1", "declarado"),
            "potencia_motor": make_spec("potencia_motor", "Potencia", "3,0 HP (2200 W)", "HP", 3.0, "HP", "Nominal", "LC30200-8", "Ficha oficial Lüsqtoff", "https://lusqtoff.com.ar/productos/LC30200-8", "pág. 1", "declarado"),
            "caudal_flujo": make_spec("caudal_flujo", "Caudal de aire", "335 L/min", "L/min", 335.0, "L/min", "Desplazamiento", "LC30200-8", "Ficha oficial Lüsqtoff", "https://lusqtoff.com.ar/productos/LC30200-8", "pág. 1", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "8 bar (115 PSI)", "bar", 8.0, "bar", "Corte", "LC30200-8", "Ficha oficial Lüsqtoff", "https://lusqtoff.com.ar/productos/LC30200-8", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("LC30200-8", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Monofásico")],
        kits=[KitOption("LC30200-8-STD", "Compresor 200L con 4 ruedas de maniobra", "No aplica", "No aplica", ["Ruedas", "Manillar"])],
        commercial_offers=[CommercialOffer("Distribuidor Oficial", "Mercado Libre", "https://meli.la/2vfnWE7", 890000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Misma bomba de 335 L/min que el LC-30100 pero con 200 L de tanque: el tiempo de carga completa desde cero es el doble."],
        primary_sources=[{"label": "Ficha oficial Lüsqtoff LC30200-8", "url": "https://lusqtoff.com.ar/productos/LC30200-8"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="lusqtoff-lc40200-8",
        brand="Lüsqtoff",
        commercial_name="LC40200-8 Trifásico (200 Litros)",
        mpn="LC40200-8",
        category="compresores",
        summary="Compresor industrial tricilíndrico a correa con tanque de 200 L y motor trifásico de 4 HP.",
        primary_use="Industria y talleres con red trifásica",
        power_source="Red eléctrica trifásica (380 V)",
        specs={
            "volumen_tanque": make_spec("volumen_tanque", "Volumen del tanque", "200 L", "L", 200.0, "L", "Nominal", "LC40200-8", "Ficha oficial Lüsqtoff", "https://lusqtoff.com.ar/productos/LC40200-8", "pág. 1", "declarado"),
            "potencia_motor": make_spec("potencia_motor", "Potencia", "4,0 HP (3000 W)", "HP", 4.0, "HP", "Trifásico 380 V", "LC40200-8", "Ficha oficial Lüsqtoff", "https://lusqtoff.com.ar/productos/LC40200-8", "pág. 1", "declarado"),
            "caudal_flujo": make_spec("caudal_flujo", "Caudal de aire", "458 L/min", "L/min", 458.0, "L/min", "Cálculo de ficha actual", "LC40200-8", "Ficha oficial Lüsqtoff", "https://lusqtoff.com.ar/productos/LC40200-8", "pág. 1", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "8 bar (115 PSI)", "bar", 8.0, "bar", "Corte", "LC40200-8", "Ficha oficial Lüsqtoff", "https://lusqtoff.com.ar/productos/LC40200-8", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso neto", "130 kg", "kg", 130.0, "kg", "Neto", "LC40200-8", "Ficha oficial Lüsqtoff", "https://lusqtoff.com.ar/productos/LC40200-8", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("LC40200-8", "Argentina", "380 V / 50 Hz", "IEC 60309 trifásico", "Requiere acometida trifásica")],
        kits=[KitOption("LC40200-8-STD", "Compresor tricilíndrico trifásico 200L", "No aplica", "No aplica", ["Ruedas industriales"])],
        commercial_offers=[CommercialOffer("Distribuidor Industrial", "Mercado Libre", "https://meli.la/200TRIF", 1150000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["No funciona con instalación monofásica estándar 220 V. Exige verificar rotación de fases en conexionado."],
        primary_sources=[{"label": "Ficha oficial Lüsqtoff LC40200-8", "url": "https://lusqtoff.com.ar/productos/LC40200-8"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="einhell-pressito-18-25",
        brand="Einhell",
        commercial_name="Pressito 18/25 Inalámbrico",
        mpn="4020420",
        category="compresores",
        summary="Compresor híbrido portátil de batería 18V Power X-Change con bombas independientes de alta y baja presión.",
        primary_use="Inflado portátil, neumáticos, balones y colchonetas",
        power_source="Batería 18 V Li-Ion (Power X-Change)",
        specs={
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "11 bar", "bar", 11.0, "bar", "Bomba alta presión con corte digital", "4020420", "Ficha técnica Einhell Pressito 18/25", "https://www.einhell.com.ar/p/4020420-pressito-18-25/", "pág. 1", "declarado"),
            "caudal_salida_4bar": make_spec("caudal_salida_4bar", "Caudal a 4 bar", "11 L/min", "L/min", 11.0, "L/min", "Medición alta presión", "4020420", "Ficha técnica Einhell Pressito 18/25", "https://www.einhell.com.ar/p/4020420-pressito-18-25/", "pág. 1", "declarado"),
            "caudal_salida_7bar": make_spec("caudal_salida_7bar", "Caudal a 7 bar", "9 L/min", "L/min", 9.0, "L/min", "Medición alta presión", "4020420", "Ficha técnica Einhell Pressito 18/25", "https://www.einhell.com.ar/p/4020420-pressito-18-25/", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso sin batería", "2,28 kg", "kg", 2.28, "kg", "Balanza", "4020420", "Ficha técnica Einhell Pressito 18/25", "https://www.einhell.com.ar/p/4020420-pressito-18-25/", "pág. 1", "declarado"),
            "ciclo_manual": make_spec("ciclo_manual", "Régimen de uso en manual", "5 min uso / 5 min pausa", "tiempo", 5.0, "min", "Manual de instrucciones oficial", "4020420", "Manual Einhell Pressito 18/25", "https://www.einhell.com.ar/p/4020420-pressito-18-25/", "pág. 8", "declarado"),
        },
        variants=[RegionalVariant("4020420", "Argentina", "18 V CC", "Power X-Change", "Herramienta sola (Solo)")],
        kits=[KitOption("4020420-SOLO", "Inflador con manguera de alta presión y manguera de baja presión para inflables", "No incluye (herramienta sola)", "No incluye", ["Manguera alta presión", "Manguera baja presión", "3 adaptadores"])],
        commercial_offers=[CommercialOffer("Tienda Oficial Einhell", "Mercado Libre", "https://meli.la/14u7fCt", 119999.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["No apto para herramientas neumáticas ni pintura continua; diseñado para inflado."],
        primary_sources=[{"label": "Ficha oficial Einhell Pressito 18/25", "url": "https://www.einhell.com.ar/p/4020420-pressito-18-25/"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="einhell-pressito-18-21",
        brand="Einhell",
        commercial_name="Pressito 18/21 Inalámbrico",
        mpn="4020467",
        category="compresores",
        summary="Versión de 10,5 bar de la línea Pressito a batería 18V para inflado en carretera y hogar.",
        primary_use="Inflado portátil",
        power_source="Batería 18 V Li-Ion",
        specs={
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "10,5 bar", "bar", 10.5, "bar", "Corte digital", "4020467", "Ficha técnica Einhell Pressito 18/21", "https://www.einhell.com.ar/p/4020467-pressito-18-21/", "pág. 1", "declarado"),
            "caudal_salida_4bar": make_spec("caudal_salida_4bar", "Caudal a 4 bar", "9 L/min", "L/min", 9.0, "L/min", "Medición alta presión", "4020467", "Ficha técnica Einhell Pressito 18/21", "https://www.einhell.com.ar/p/4020467-pressito-18-21/", "pág. 1", "declarado"),
            "caudal_salida_7bar": make_spec("caudal_salida_7bar", "Caudal a 7 bar", "6 L/min", "L/min", 6.0, "L/min", "Medición alta presión", "4020467", "Ficha técnica Einhell Pressito 18/21", "https://www.einhell.com.ar/p/4020467-pressito-18-21/", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("4020467", "Argentina", "18 V CC", "Power X-Change", "Solo")],
        kits=[KitOption("4020467-SOLO", "Inflador sin batería ni cargador con pantalla digital", "No incluye", "No incluye", ["Adaptadores de boquilla"])],
        commercial_offers=[CommercialOffer("Tienda Oficial Einhell", "Mercado Libre", "https://meli.la/1iNDq73", 99999.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Caudal moderado para inflado ocasional; no sustituye compresor de taller."],
        primary_sources=[{"label": "Ficha oficial Einhell Pressito 18/21", "url": "https://www.einhell.com.ar/p/4020467-pressito-18-21/"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="makita-dmp180",
        brand="Makita",
        commercial_name="DMP180 Inalámbrico 18V",
        mpn="DMP180",
        category="compresores",
        summary="Inflador compacto a batería Makita 18V LXT con parada automática a la presión fijada en pantalla.",
        primary_use="Inflado de neumáticos de auto y bicicleta",
        power_source="Batería 18 V Li-Ion (Makita LXT)",
        specs={
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "830 kPa (8,3 bar)", "bar", 8.3, "bar", "Corte por sensor digital", "DMP180", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 52", "declarado"),
            "caudal_700kpa": make_spec("caudal_700kpa", "Caudal a 700 kPa", "8 L/min", "L/min", 8.0, "L/min", "A 7 bar en catálogo oficial", "DMP180", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 52", "declarado"),
            "longitud_manguera": make_spec("longitud_manguera", "Largo de manguera", "65 cm", "cm", 65.0, "cm", "Con racor de acople", "DMP180", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 52", "declarado"),
            "peso": make_spec("peso", "Peso con batería", "1,7 kg", "kg", 1.7, "kg", "Con batería BL1860B", "DMP180", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 52", "declarado"),
        },
        variants=[RegionalVariant("DMP180Z", "Argentina", "18 V CC", "Makita LXT", "Herramienta sola sin batería")],
        kits=[KitOption("DMP180Z", "Inflador DMP180 con adaptadores para válvulas Presta/Schrader", "No incluye", "No incluye", ["Adaptador bicicleta", "Aguja pelota", "Adaptador cónico"])],
        commercial_offers=[CommercialOffer("Distribuidor Makita", "Mercado Libre", "https://meli.la/2uRPKYD", 145000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["No cuenta con modo de succión para desinflado rápido como otros modelos con bomba de bajo volumen."],
        primary_sources=[{"label": "Catálogo Makita Argentina 2025", "url": "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="lusqtoff-mcl150-8",
        brand="Lüsqtoff",
        commercial_name="MCL150-8 Digital (12V)",
        mpn="MCL150-8",
        category="compresores",
        summary="Compresor de 12 V para toma de encendedor de auto o pinzas a batería con manómetro digital y corte automático.",
        primary_use="Auxilio mecánico y neumáticos de automóvil",
        power_source="12 V CC (automóvil)",
        specs={
            "presion_maxima": make_spec("presion_maxima", "Presión máxima anunciada", "150 PSI", "PSI", 10.3, "bar", "Corte digital", "MCL150-8", "Ficha oficial Lüsqtoff MCL150-8", "https://lusqtoff.com.ar/ver-producto/MCL150-8", "pág. 1", "declarado"),
            "caudal_anunciado": make_spec("caudal_anunciado", "Caudal anunciado", "60 L/min", "L/min", 60.0, "L/min", "Sin presión asociada en ficha", "MCL150-8", "Ficha oficial Lüsqtoff MCL150-8", "https://lusqtoff.com.ar/ver-producto/MCL150-8", "pág. 1", "declarado"),
            "potencia": make_spec("potencia", "Potencia", "275 W", "W", 275.0, "W", "12 V", "MCL150-8", "Ficha oficial Lüsqtoff MCL150-8", "https://lusqtoff.com.ar/ver-producto/MCL150-8", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso neto", "2,63 kg", "kg", 2.63, "kg", "Neto", "MCL150-8", "Ficha oficial Lüsqtoff MCL150-8", "https://lusqtoff.com.ar/ver-producto/MCL150-8", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("MCL150-8", "Argentina", "12 V CC", "Toma 12V / Pinzas cocodrilo", "Portátil para vehículo")],
        kits=[KitOption("MCL150-8-KIT", "Compresor con estuche, pinzas de batería y manguera espiralada de 5m", "No aplica", "No aplica", ["Pinzas cocodrilo", "Manguera 5m", "Picos adaptadores", "Bolso"])],
        commercial_offers=[CommercialOffer("Distribuidor Oficial", "Mercado Libre", "https://meli.la/2r8uZXD", 69900.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Los 60 L/min son sin carga; el tiempo de inflado de un neumático de camioneta cambia notablemente con la contrapresión."],
        primary_sources=[{"label": "Ficha oficial Lüsqtoff MCL150-8", "url": "https://lusqtoff.com.ar/ver-producto/MCL150-8"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="gadnic-av37",
        brand="Gadnic",
        commercial_name="Gadnic AV37 Doble Pistón (12V)",
        mpn="AV37-TY",
        category="compresores",
        summary="Compresor de 12 V con doble cilindro, pantalla digital de corte y linterna LED incorporada.",
        primary_use="Neumáticos de camioneta y auxilio 4x4",
        power_source="12 V CC (batería de auto)",
        specs={
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "150 PSI", "PSI", 10.3, "bar", "Digital", "AV37-TY", "Ficha técnica Gadnic AV37", "https://www.gadnic.com.ar/infladores-y-compresores/compresor-12v-doble-cilindro-gadnic-av37-ty-digital-auto-linterna", "pág. 1", "declarado"),
            "caudal_desplazado": make_spec("caudal_desplazado", "Caudal anunciado", "35 L/min", "L/min", 35.0, "L/min", "Sin presión indicada", "AV37-TY", "Ficha técnica Gadnic AV37", "https://www.gadnic.com.ar/infladores-y-compresores/compresor-12v-doble-cilindro-gadnic-av37-ty-digital-auto-linterna", "pág. 1", "declarado"),
            "cable_alimentacion": make_spec("cable_alimentacion", "Largo de cable", "2,6 m", "m", 2.6, "m", "Conector 12 V", "AV37-TY", "Ficha técnica Gadnic AV37", "https://www.gadnic.com.ar/infladores-y-compresores/compresor-12v-doble-cilindro-gadnic-av37-ty-digital-auto-linterna", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("AV37-TY", "Argentina", "12 V CC", "Toma 12 V / Pinzas", "Doble pistón")],
        kits=[KitOption("AV37-TY-STD", "Compresor doble cilindro con manguera de extensión y bolso", "No aplica", "No aplica", ["Manguera espiralada", "Bolso", "Adaptadores"])],
        commercial_offers=[CommercialOffer("Tienda Oficial Gadnic", "Mercado Libre", "https://meli.la/2aSkmx1", 62900.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Tener dos pistones no garantiza mayor caudal que un solo pistón de mayor diámetro si el motor tiene la misma potencia eléctrica."],
        primary_sources=[{"label": "Ficha oficial Gadnic AV37", "url": "https://www.gadnic.com.ar/infladores-y-compresores/compresor-12v-doble-cilindro-gadnic-av37-ty-digital-auto-linterna"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="fengda-as-186",
        brand="Fengda",
        commercial_name="AS-186 para Aerógrafo",
        mpn="AS-186",
        category="compresores",
        summary="Compresor de pistón seco libre de aceite con calderín de 3 L, regulador y filtro de humedad para aerografía.",
        primary_use="Aerografía, modelismo y decoración",
        power_source="Red eléctrica (220-240 V)",
        specs={
            "volumen_tanque": make_spec("volumen_tanque", "Volumen del calderín", "3 L", "L", 3.0, "L", "Depósito antivibración de pulso", "AS-186", "Ficha técnica oficial Fengda AS-186", "https://www.airbrush-fengda.de/Hobby-Kompressor-mit-dem-Druckbehaelter-Fengda-AS-186", "pág. 1", "declarado"),
            "caudal_sin_carga": make_spec("caudal_sin_carga", "Caudal sin carga", "20–23 L/min", "L/min", 21.5, "L/min", "Salida libre a 0 bar", "AS-186", "Ficha técnica oficial Fengda AS-186", "https://www.airbrush-fengda.de/Hobby-Kompressor-mit-dem-Druckbehaelter-Fengda-AS-186", "pág. 1", "declarado"),
            "presion_trabajo": make_spec("presion_trabajo", "Control automático de presión", "3 a 4 bar", "bar", 4.0, "bar", "Arranque a 3 bar / parada a 4 bar", "AS-186", "Ficha técnica oficial Fengda AS-186", "https://www.airbrush-fengda.de/Hobby-Kompressor-mit-dem-Druckbehaelter-Fengda-AS-186", "pág. 1", "declarado"),
            "nivel_sonoro": make_spec("nivel_sonoro", "Nivel de ruido", "47 dB(A)", "dB", 47.0, "dB", "A 1 metro", "AS-186", "Ficha técnica oficial Fengda AS-186", "https://www.airbrush-fengda.de/Hobby-Kompressor-mit-dem-Druckbehaelter-Fengda-AS-186", "pág. 1", "declarado"),
            "rosca_salida": make_spec("rosca_salida", "Rosca de conexión", "G 1/8 macho", "rosca", 0.0, "rosca", "Estándar de mangueras de aerógrafo", "AS-186", "Ficha técnica oficial Fengda AS-186", "https://www.airbrush-fengda.de/Hobby-Kompressor-mit-dem-Druckbehaelter-Fengda-AS-186", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("AS-186", "Argentina", "220-240 V / 50 Hz", "IRAM 2073", "Variante europea importada confirmada 50Hz")],
        kits=[KitOption("AS-186-BASE", "Compresor AS-186 con manómetro, trampa de agua y regulador de presión", "No aplica", "No aplica", ["Manómetro", "Filtro trampa de condensado", "Soporte de aerógrafo"])],
        commercial_offers=[CommercialOffer("Distribuidor Aerografía Argentina", "Mercado Libre", "https://meli.la/2AERO186", 185000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=[
            "No apto para pistolas de pintura de automoción ni clavadoras; caudal diseñado exclusivamente para aerógrafos de boquilla 0,2 a 0,5 mm.",
            "El fabricante excluye el uso continuo industrial sin pausas térmicas."
        ],
        primary_sources=[{"label": "Ficha oficial Fengda AS-186", "url": "https://www.airbrush-fengda.de/Hobby-Kompressor-mit-dem-Druckbehaelter-Fengda-AS-186"}],
        last_reviewed="2026-10-01"
    )
]
