"""Datos técnicos de 25 modelos de Hidrolavadoras en Argentina."""

from tallerlab_data.catalog_data.common import make_spec
from tallerlab_data.models import (
    CommercialOffer,
    ContradictionRecord,
    KitOption,
    RegionalVariant,
    TechnicalTool,
)

HIDROLAVADORAS_TOOLS = [
    TechnicalTool(
        slug="karcher-k2-basic",
        brand="Kärcher",
        commercial_name="K2 Basic Car",
        mpn="1.600-008.0",
        category="hidrolavadoras",
        summary="Hidrolavadora de entrada para limpieza ligera de bicicletas, veredas y muebles de jardín.",
        primary_use="Hogar y limpieza ocasional",
        power_source="Red eléctrica (220 V)",
        specs={
            "presion_maxima": make_spec("presion_maxima", "Presión máxima admisible", "110 bar (11 MPa)", "bar", 110.0, "bar", "Presión pico de corte", "1.600-008.0", "Ficha técnica Kärcher Argentina", "https://www.kaercher.com/ar/home-garden/hidrolavadora/k-2-basic.html", "pág. 1", "declarado"),
            "caudal_maximo": make_spec("caudal_maximo", "Caudal máximo", "360 L/h (6 L/min)", "L/h", 360.0, "L/h", "Bajo norma EN 60335-2-79", "1.600-008.0", "Ficha técnica Kärcher Argentina", "https://www.kaercher.com/ar/home-garden/hidrolavadora/k-2-basic.html", "pág. 1", "declarado"),
            "potencia": make_spec("potencia", "Potencia de conexión", "1400 W", "W", 1400.0, "W", "Motor universal con escobillas", "1.600-008.0", "Ficha técnica Kärcher Argentina", "https://www.kaercher.com/ar/home-garden/hidrolavadora/k-2-basic.html", "pág. 1", "declarado"),
            "manguera_alta_presion": make_spec("manguera_alta_presion", "Longitud de manguera", "3 m", "m", 3.0, "m", "Conexión Quick Connect", "1.600-008.0", "Ficha técnica Kärcher Argentina", "https://www.kaercher.com/ar/home-garden/hidrolavadora/k-2-basic.html", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso sin accesorios", "4,0 kg", "kg", 4.0, "kg", "Balanza", "1.600-008.0", "Ficha técnica Kärcher Argentina", "https://www.kaercher.com/ar/home-garden/hidrolavadora/k-2-basic.html", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("1.600-008.0", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Bomba de polímero N-Cor")],
        kits=[KitOption("K2-BASIC-CAR", "Equipo K2 con pistola, lanza simple y boquilla turbo", "No aplica", "No aplica", ["Pistola G 120 Q", "Lanza turbo", "Filtro de agua"])],
        commercial_offers=[CommercialOffer("Tienda Kärcher Oficial", "Mercado Libre", "https://meli.la/2izv76H", 185000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Manguera de 3 metros limita el radio de acción en vehículos grandes sin mover la máquina."],
        primary_sources=[{"label": "Ficha Kärcher K2", "url": "https://www.kaercher.com/ar/home-garden/hidrolavadora/k-2-basic.html"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="karcher-k3-black-edition",
        brand="Kärcher",
        commercial_name="K3 Black Edition",
        mpn="9.398-355.0",
        category="hidrolavadoras",
        summary="Hidrolavadora de 120 bar con ruedas de transporte y manguera de mayor alcance para patios.",
        primary_use="Hogar y lavado de autos",
        power_source="Red eléctrica (220 V)",
        specs={
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "120 bar (12 MPa)", "bar", 120.0, "bar", "Corte presostato", "9.398-355.0", "Ficha oficial Kärcher Argentina", "https://www.kaercher.com/ar/home-garden/hidrolavadora/k-3-black-edition-93983550.html", "pág. 1", "declarado"),
            "caudal_maximo": make_spec("caudal_maximo", "Caudal máximo", "330 L/h", "L/h", 330.0, "L/h", "Declarado en ficha oficial", "9.398-355.0", "Ficha oficial Kärcher Argentina", "https://www.kaercher.com/ar/home-garden/hidrolavadora/k-3-black-edition-93983550.html", "pág. 1", "declarado"),
            "potencia": make_spec("potencia", "Potencia", "1600 W", "W", 1600.0, "W", "Nominal", "9.398-355.0", "Ficha oficial Kärcher Argentina", "https://www.kaercher.com/ar/home-garden/hidrolavadora/k-3-black-edition-93983550.html", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso sin accesorios", "7,3 kg", "kg", 7.3, "kg", "Neto", "9.398-355.0", "Ficha oficial Kärcher Argentina", "https://www.kaercher.com/ar/home-garden/hidrolavadora/k-3-black-edition-93983550.html", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("9.398-355.0", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Edición Black")],
        kits=[KitOption("9.398-355.0-STD", "K3 con lanza Vario Power y boquilla turbo", "No aplica", "No aplica", ["Lanza Vario Power", "Boquilla turbo", "Pistola"])],
        commercial_offers=[CommercialOffer("Distribuidor Kärcher", "Mercado Libre", "https://meli.la/1LYmDeG", 265000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["El caudal es de 330 L/h; menor que otras variantes de la serie K2 pero con mayor presión pico."],
        primary_sources=[{"label": "Ficha oficial Kärcher K3 Black Edition", "url": "https://www.kaercher.com/ar/home-garden/hidrolavadora/k-3-black-edition-93983550.html"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="karcher-k4-power-control",
        brand="Kärcher",
        commercial_name="K4 Power Control",
        mpn="1.603-402.0",
        category="hidrolavadoras",
        summary="Hidrolavadora de 130 bar con motor de inducción refrigerado por agua y lanza con regulación en gatillo.",
        primary_use="Patios, vehículos y fachadas",
        power_source="Red eléctrica (220 V)",
        specs={
            "presion_trabajo": make_spec("presion_trabajo", "Presión de trabajo ajustable", "20 a 130 bar", "bar", 130.0, "bar", "Regulación Vario Power", "1.603-402.0", "Ficha técnica oficial Kärcher", "https://www.kaercher.com/ar/home-garden/hidrolavadora/k-4-power-control-16034020.html", "pág. 1", "declarado"),
            "caudal_maximo": make_spec("caudal_maximo", "Caudal máximo", "420 L/h (7 L/min)", "L/h", 420.0, "L/h", "Máximo según fabricante", "1.603-402.0", "Ficha técnica oficial Kärcher", "https://www.kaercher.com/ar/home-garden/hidrolavadora/k-4-power-control-16034020.html", "pág. 1", "declarado"),
            "potencia": make_spec("potencia", "Potencia del motor", "1800 W", "W", 1800.0, "W", "Motor de inducción refrigerado por agua (WCM)", "1.603-402.0", "Ficha técnica oficial Kärcher", "https://www.kaercher.com/ar/home-garden/hidrolavadora/k-4-power-control-16034020.html", "pág. 1", "declarado"),
            "manguera_alta_presion": make_spec("manguera_alta_presion", "Longitud de manguera", "8 m", "m", 8.0, "m", "Reforzada", "1.603-402.0", "Ficha técnica oficial Kärcher", "https://www.kaercher.com/ar/home-garden/hidrolavadora/k-4-power-control-16034020.html", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso sin accesorios", "11,5 kg", "kg", 11.5, "kg", "Neto", "1.603-402.0", "Ficha técnica oficial Kärcher", "https://www.kaercher.com/ar/home-garden/hidrolavadora/k-4-power-control-16034020.html", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("1.603-402.0", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Motor refrigerado por agua")],
        kits=[KitOption("1.603-402.0-STD", "K4 Power Control con pistola G 160 Q y manguera 8m", "No aplica", "No aplica", ["Pistola Power Control", "Lanza Vario Power", "Boquilla turbo"])],
        commercial_offers=[CommercialOffer("Tienda Kärcher Oficial", "Mercado Libre", "https://meli.la/149NjG2", 489000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["No equivale al código K4 estándar 9.398-294.0: cambian motor, manguera y bomba."],
        primary_sources=[{"label": "Ficha técnica oficial Kärcher K4 Power Control", "url": "https://www.kaercher.com/ar/home-garden/hidrolavadora/k-4-power-control-16034020.html"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="karcher-k4-standard",
        brand="Kärcher",
        commercial_name="K4 Standard 9.398-294.0",
        mpn="9.398-294.0",
        category="hidrolavadoras",
        summary="Versión K4 de inducción con manguera de 6 m y 1885 PSI publicados para el mercado argentino.",
        primary_use="Lavado doméstico intensivo",
        power_source="Red eléctrica (220 V)",
        specs={
            "presion_publicada": make_spec("presion_publicada", "Presión publicada", "1885 PSI (≈130 bar)", "PSI", 130.0, "bar", "Conversión oficial", "9.398-294.0", "Ficha oficial Kärcher Argentina", "https://www.kaercher.com/ar/home-garden/hidrolavadora/k4-93982940.html", "pág. 1", "declarado"),
            "caudal_maximo": make_spec("caudal_maximo", "Caudal publicado", "360 L/h", "L/h", 360.0, "L/h", "Declarado en ficha", "9.398-294.0", "Ficha oficial Kärcher Argentina", "https://www.kaercher.com/ar/home-garden/hidrolavadora/k4-93982940.html", "pág. 1", "declarado"),
            "potencia": make_spec("potencia", "Potencia", "1700 W", "W", 1700.0, "W", "Inducción", "9.398-294.0", "Ficha oficial Kärcher Argentina", "https://www.kaercher.com/ar/home-garden/hidrolavadora/k4-93982940.html", "pág. 1", "declarado"),
            "manguera": make_spec("manguera", "Largo de manguera", "6 m", "m", 6.0, "m", "Quick Connect", "9.398-294.0", "Ficha oficial Kärcher Argentina", "https://www.kaercher.com/ar/home-garden/hidrolavadora/k4-93982940.html", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("9.398-294.0", "Argentina", "220 V / 50 Hz", "IRAM 2073", "K4 base sin Power Control")],
        kits=[KitOption("9.398-294.0-STD", "K4 con manguera 6m y lanza rotativa", "No aplica", "No aplica", ["Manguera 6m", "Pistola estándar"])],
        commercial_offers=[CommercialOffer("Distribuidor Kärcher", "Mercado Libre", "https://meli.la/2SvkJCm", 419000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Tiene 6 metros de manguera frente a 8 m del Power Control y caudal de 360 L/h vs 420 L/h."],
        primary_sources=[{"label": "Ficha oficial Kärcher K4 9.398-294.0", "url": "https://www.kaercher.com/ar/home-garden/hidrolavadora/k4-93982940.html"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="karcher-k5-power-control",
        brand="Kärcher",
        commercial_name="K5 Power Control",
        mpn="1.603-501.0",
        category="hidrolavadoras",
        summary="Hidrolavadora de 145 bar con motor de 2100 W y 500 L/h de caudal para suciedad adherida severa.",
        primary_use="Lavado intensivo, muros y grandes superficies",
        power_source="Red eléctrica (220 V)",
        specs={
            "presion_trabajo": make_spec("presion_trabajo", "Presión ajustable", "20 a 145 bar", "bar", 145.0, "bar", "Vario Power", "1.603-501.0", "Ficha técnica Kärcher", "https://puntogardenia.com.ar/productos/hidrolavadora-k-5-power-control-ar-karcher-1-603-501-0/", "pág. 1", "declarado"),
            "caudal_maximo": make_spec("caudal_maximo", "Caudal máximo", "480–500 L/h", "L/h", 500.0, "L/h", "Variación entre fichas consultadas", "1.603-501.0", "Ficha técnica Kärcher", "https://puntogardenia.com.ar/productos/hidrolavadora-k-5-power-control-ar-karcher-1-603-501-0/", "pág. 1", "declarado"),
            "potencia": make_spec("potencia", "Potencia", "2100 W", "W", 2100.0, "W", "Motor de inducción refrigerado por agua", "1.603-501.0", "Ficha técnica Kärcher", "https://puntogardenia.com.ar/productos/hidrolavadora-k-5-power-control-ar-karcher-1-603-501-0/", "pág. 1", "declarado"),
            "manguera_alta_presion": make_spec("manguera_alta_presion", "Manguera de presión", "10 m", "m", 10.0, "m", "Manguera de 10 metros reforzada", "1.603-501.0", "Ficha técnica Kärcher", "https://puntogardenia.com.ar/productos/hidrolavadora-k-5-power-control-ar-karcher-1-603-501-0/", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("1.603-501.0", "Argentina", "220 V / 50 Hz", "IRAM 2073", "K5 Power Control")],
        kits=[KitOption("1.603-501.0-STD", "K5 con manguera 10m y sistema Plug 'n' Clean", "No aplica", "No aplica", ["Pistola G 160 Q", "Manguera 10m", "Lanza turbo", "Lanza Vario"])],
        commercial_offers=[CommercialOffer("Tienda Kärcher Oficial", "Mercado Libre", "https://meli.la/1wCKV4R", 689000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Peso cercano a 13 kg; se recomienda transportar siempre sobre sus ruedas."],
        primary_sources=[{"label": "Ficha Kärcher K5 Power Control AR", "url": "https://puntogardenia.com.ar/productos/hidrolavadora-k-5-power-control-ar-karcher-1-603-501-0/"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="karcher-k5-base",
        brand="Kärcher",
        commercial_name="K5 Standard 9.398-295.0",
        mpn="9.398-295.0",
        category="hidrolavadoras",
        summary="Versión estándar de K5 con manguera de 6 m y 2100 PSI publicados.",
        primary_use="Lavado doméstico intensivo",
        power_source="Red eléctrica (220 V)",
        specs={
            "presion_publicada": make_spec("presion_publicada", "Presión publicada", "2100 PSI (≈145 bar)", "PSI", 145.0, "bar", "Conversión oficial", "9.398-295.0", "Ficha oficial Kärcher Argentina", "https://www.kaercher.com/ar/home-garden/hidrolavadora/k-5-93982950.html", "pág. 1", "declarado"),
            "caudal_publicado": make_spec("caudal_publicado", "Caudal publicado", "420 L/h", "L/h", 420.0, "L/h", "Ficha Kärcher", "9.398-295.0", "Ficha oficial Kärcher Argentina", "https://www.kaercher.com/ar/home-garden/hidrolavadora/k-5-93982950.html", "pág. 1", "declarado"),
            "manguera": make_spec("manguera", "Largo de manguera", "6 m", "m", 6.0, "m", "Quick Connect", "9.398-295.0", "Ficha oficial Kärcher Argentina", "https://www.kaercher.com/ar/home-garden/hidrolavadora/k-5-93982950.html", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("9.398-295.0", "Argentina", "220 V / 50 Hz", "IRAM 2073", "K5 base")],
        kits=[KitOption("9.398-295.0-STD", "K5 base con manguera 6m", "No aplica", "No aplica", ["Manguera 6m", "Pistola"])],
        commercial_offers=[CommercialOffer("Distribuidor Kärcher", "Mercado Libre", "https://meli.la/2K5BASE", 579000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Manguera de 6m frente a 10m de la Power Control; confirmar código exacto antes de adquirir."],
        primary_sources=[{"label": "Ficha oficial Kärcher K5 9.398-295.0", "url": "https://www.kaercher.com/ar/home-garden/hidrolavadora/k-5-93982950.html"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="bosch-ghp-180",
        brand="Bosch",
        commercial_name="GHP 180 Professional",
        mpn="0600910CH0",
        category="hidrolavadoras",
        summary="Hidrolavadora profesional compacta con valores de presión de trabajo y nominal explícitamente separados.",
        primary_use="Limpieza profesional ligera y talleres",
        power_source="Red eléctrica (220 V)",
        specs={
            "presion_trabajo": make_spec("presion_trabajo", "Presión de trabajo", "83 bar", "bar", 83.0, "bar", "Sostenida en boquilla", "0600910CH0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/ghp-180-0600910CH0", "pág. 1", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "124,5 bar", "bar", 124.5, "bar", "Corte presostato", "0600910CH0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/ghp-180-0600910CH0", "pág. 1", "declarado"),
            "caudal_nominal": make_spec("caudal_nominal", "Caudal nominal", "4,0 L/min (240 L/h)", "L/min", 4.0, "L/min", "Flujo de trabajo continuo", "0600910CH0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/ghp-180-0600910CH0", "pág. 1", "declarado"),
            "caudal_maximo": make_spec("caudal_maximo", "Caudal máximo", "5,6 L/min (336 L/h)", "L/min", 5.6, "L/min", "Pico sin contrapresión", "0600910CH0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/ghp-180-0600910CH0", "pág. 1", "declarado"),
            "potencia": make_spec("potencia", "Potencia absorbida", "1500 W", "W", 1500.0, "W", "220 V", "0600910CH0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/ghp-180-0600910CH0", "pág. 1", "declarado"),
            "manguera": make_spec("manguera", "Largo de manguera", "5 m PVC", "m", 5.0, "m", "Con aplicador de 450 ml", "0600910CH0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/ghp-180-0600910CH0", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("0600910CH0", "Argentina", "220 V / 50 Hz", "IRAM 2073", "GHP 180")],
        kits=[KitOption("0600910CH0-STD", "GHP 180 con lanza rotativa, lanza abanico y aplicador de detergente", "No aplica", "No aplica", ["Lanza rotativa", "Lanza abanico", "Depósito detergente"])],
        commercial_offers=[CommercialOffer("Distribuidor Bosch", "Mercado Libre", "https://meli.la/1wNMwSL", 310000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Bosch separa rigurosamente 83 bar de trabajo de 124,5 bar máximos; no comparar el valor máximo de Bosch con el valor de trabajo de otra marca."],
        primary_sources=[{"label": "Ficha oficial Bosch GHP 180", "url": "https://www.bosch-professional.com/ar/es/products/ghp-180-0600910CH0"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="bosch-ghp-200",
        brand="Bosch",
        commercial_name="GHP 200 Professional",
        mpn="0600910DH0",
        category="hidrolavadoras",
        summary="Hidrolavadora profesional de 92 bar de trabajo con manguera de 6 m y 2000 W.",
        primary_use="Lavado profesional de flotas y talleres",
        power_source="Red eléctrica (220 V)",
        specs={
            "presion_trabajo": make_spec("presion_trabajo", "Presión de trabajo", "92 bar", "bar", 92.0, "bar", "Trabajo continuo", "0600910DH0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/ghp-200-0600910DH0", "pág. 1", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "138 bar", "bar", 138.0, "bar", "Pico", "0600910DH0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/ghp-200-0600910DH0", "pág. 1", "declarado"),
            "caudal_nominal": make_spec("caudal_nominal", "Caudal nominal", "5,1 L/min (306 L/h)", "L/min", 5.1, "L/min", "Nominal continuo", "0600910DH0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/ghp-200-0600910DH0", "pág. 1", "declarado"),
            "caudal_maximo": make_spec("caudal_maximo", "Caudal máximo", "7,7 L/min (462 L/h)", "L/min", 7.7, "L/min", "Máximo", "0600910DH0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/ghp-200-0600910DH0", "pág. 1", "declarado"),
            "potencia": make_spec("potencia", "Potencia absorbida", "2000 W", "W", 2000.0, "W", "220 V", "0600910DH0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/ghp-200-0600910DH0", "pág. 1", "declarado"),
            "manguera": make_spec("manguera", "Largo de manguera", "6 m PVC", "m", 6.0, "m", "Reforzada", "0600910DH0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/ghp-200-0600910DH0", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("0600910DH0", "Argentina", "220 V / 50 Hz", "IRAM 2073", "GHP 200")],
        kits=[KitOption("0600910DH0-STD", "GHP 200 con aplicador de detergente 450 ml y 2 lanzas", "No aplica", "No aplica", ["Lanzas de presión", "Aplicador"])],
        commercial_offers=[CommercialOffer("Distribuidor Bosch", "Mercado Libre", "https://meli.la/1zrcYor", 395000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["La presión de 92 bar es la referencia de trabajo; los 138 bar corresponden a la válvula de descarga."],
        primary_sources=[{"label": "Ficha oficial Bosch GHP 200", "url": "https://www.bosch-professional.com/ar/es/products/ghp-200-0600910DH0"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="bosch-ghp-220",
        brand="Bosch",
        commercial_name="GHP 220 Professional",
        mpn="0600910EH0",
        category="hidrolavadoras",
        summary="Hidrolavadora con motor de inducción, 101,2 bar de trabajo, 6,1 L/min nominales y manguera de 8 m.",
        primary_use="Trabajos de obra, patios y uso profesional continuado",
        power_source="Red eléctrica (220 V)",
        specs={
            "presion_trabajo": make_spec("presion_trabajo", "Presión de trabajo", "101,2 bar", "bar", 101.2, "bar", "Trabajo continuo", "0600910EH0", "Manual Bosch GHP 220 (pág. 14)", "https://www.bosch-professional.com/ar/es/products/ghp-220-0600910EH0", "pág. 14", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "151,8 bar", "bar", 151.8, "bar", "Corte", "0600910EH0", "Manual Bosch GHP 220 (pág. 14)", "https://www.bosch-professional.com/ar/es/products/ghp-220-0600910EH0", "pág. 14", "declarado"),
            "caudal_nominal": make_spec("caudal_nominal", "Caudal nominal", "6,1 L/min (366 L/h)", "L/min", 6.1, "L/min", "Flujo continuo", "0600910EH0", "Manual Bosch GHP 220 (pág. 14)", "https://www.bosch-professional.com/ar/es/products/ghp-220-0600910EH0", "pág. 14", "declarado"),
            "caudal_maximo": make_spec("caudal_maximo", "Caudal máximo", "7,4 L/min (444 L/h)", "L/min", 7.4, "L/min", "Pico", "0600910EH0", "Manual Bosch GHP 220 (pág. 14)", "https://www.bosch-professional.com/ar/es/products/ghp-220-0600910EH0", "pág. 14", "declarado"),
            "potencia": make_spec("potencia", "Potencia del motor", "2200 W", "W", 2200.0, "W", "Motor de inducción", "0600910EH0", "Manual Bosch GHP 220 (pág. 14)", "https://www.bosch-professional.com/ar/es/products/ghp-220-0600910EH0", "pág. 14", "declarado"),
            "manguera": make_spec("manguera", "Largo de manguera", "8 m PVC reforzado", "m", 8.0, "m", "Con enrollador", "0600910EH0", "Manual Bosch GHP 220 (pág. 14)", "https://www.bosch-professional.com/ar/es/products/ghp-220-0600910EH0", "pág. 14", "declarado"),
        },
        variants=[RegionalVariant("0600910EH0", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Motor de inducción")],
        kits=[KitOption("0600910EH0-STD", "GHP 220 con manguera 8m, lanza rotativa y boquilla abanico", "No aplica", "No aplica", ["Lanza rotativa", "Lanza abanico", "Manguera 8m"])],
        commercial_offers=[CommercialOffer("Distribuidor Oficial Bosch", "Mercado Libre", "https://meli.la/2BGHP220", 529000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Motor de inducción requiere al menos 10 A de línea sin caída de tensión."],
        primary_sources=[
            {"label": "Ficha oficial Bosch GHP 220", "url": "https://www.bosch-professional.com/ar/es/products/ghp-220-0600910EH0"},
            {"label": "Manual Bosch GHP 220", "url": "https://www.bosch-professional.com/binary/manualsmedia/o424644v21_bosch_ghp_220.pdf"}
        ],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="bosch-ghp-4-50",
        brand="Bosch",
        commercial_name="GHP 4-50 Professional",
        mpn="0600910FH0",
        category="hidrolavadoras",
        summary="Hidrolavadora de alto rendimiento con bomba de cuatro pistones y 115,5 bar de trabajo continuo.",
        primary_use="Lavaderos profesionales, industria y agricultura",
        power_source="Red eléctrica (220 V)",
        specs={
            "presion_trabajo": make_spec("presion_trabajo", "Presión de trabajo", "115,5 bar", "bar", 115.5, "bar", "Sostenida", "0600910FH0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/ghp-4-50-0600910FH0", "pág. 1", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "173,2 bar", "bar", 173.2, "bar", "Máxima admisible", "0600910FH0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/ghp-4-50-0600910FH0", "pág. 1", "declarado"),
            "caudal_nominal": make_spec("caudal_nominal", "Caudal nominal y máximo", "7,3 L/min (438 L/h)", "L/min", 7.3, "L/min", "Bomba 4 pistones", "0600910FH0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/ghp-4-50-0600910FH0", "pág. 1", "declarado"),
            "potencia": make_spec("potencia", "Potencia", "2400 W", "W", 2400.0, "W", "Inducción", "0600910FH0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/ghp-4-50-0600910FH0", "pág. 1", "declarado"),
            "manguera": make_spec("manguera", "Largo de manguera", "9 m con refuerzo de acero", "m", 9.0, "m", "Refuerzo metálico", "0600910FH0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/ghp-4-50-0600910FH0", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("0600910FH0", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Bomba cuadripistón")],
        kits=[KitOption("0600910FH0-STD", "GHP 4-50 con manguera 9m de malla de acero", "No aplica", "No aplica", ["Manguera reforzada 9m", "Lanza 3 en 1"])],
        commercial_offers=[CommercialOffer("Distribuidor Bosch", "Mercado Libre", "https://meli.la/2BGHP450", 790000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Manguera con malla de acero y bomba pesada; equipo destinado a puesto fijo o arrastre por ruedas reforzadas."],
        primary_sources=[{"label": "Ficha oficial Bosch GHP 4-50", "url": "https://www.bosch-professional.com/ar/es/products/ghp-4-50-0600910FH0"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="bosch-universalaquatak-36v-100",
        brand="Bosch",
        commercial_name="UniversalAquatak 36V-100",
        mpn="06008C7002",
        category="hidrolavadoras",
        summary="Hidrolavadora a batería de 36V con modos ECO y High para limpieza sin tomas de corriente.",
        primary_use="Lavado móvil y autosucción",
        power_source="Batería 36 V Li-Ion (POWER FOR ALL)",
        specs={
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "100 bar", "bar", 100.0, "bar", "Modo High; trabajo no separado", "06008C7002", "Ficha técnica Bosch", "https://www.bosch-diy.com/de/de/p/universalaquatak-36v-100-06008c7002", "pág. 1", "declarado"),
            "caudal_maximo": make_spec("caudal_maximo", "Caudal máximo", "3,1 L/min (186 L/h)", "L/min", 3.1, "L/min", "Modo High", "06008C7002", "Ficha técnica Bosch", "https://www.bosch-diy.com/de/de/p/universalaquatak-36v-100-06008c7002", "pág. 1", "declarado"),
            "autosuccion": make_spec("autosuccion", "Altura de autosucción", "0,5 m", "m", 0.5, "m", "Desde balde o bidón", "06008C7002", "Ficha técnica Bosch", "https://www.bosch-diy.com/de/de/p/universalaquatak-36v-100-06008c7002", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("06008C7002", "Argentina", "36 V CC", "POWER FOR ALL 36V", "Inalámbrica")],
        kits=[KitOption("06008C7002-KIT", "Incluye batería 36V 4.0Ah y cargador", "1x 36V 4.0 Ah", "AL 36V-20", ["Manguera 4m", "Pistola"])],
        commercial_offers=[CommercialOffer("Distribuidor Bosch", "Mercado Libre", "https://meli.la/1YbCQgP", 495000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Autonomía limitada por carga de batería; para lavado completo de camioneta se aconseja disponer de dos baterías."],
        primary_sources=[{"label": "Ficha oficial Bosch UniversalAquatak 36V-100", "url": "https://www.bosch-diy.com/de/de/p/universalaquatak-36v-100-06008c7002"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="lusqtoff-hl100-7",
        brand="Lüsqtoff",
        commercial_name="HL100-7 Compacta (100 bar)",
        mpn="HL100-7",
        category="hidrolavadoras",
        summary="Hidrolavadora de 1200 W con 70 bar nominales y 100 bar máximos para lavado ocasional.",
        primary_use="Hogar y veredas",
        power_source="Red eléctrica (220 V)",
        specs={
            "presion_trabajo": make_spec("presion_trabajo", "Presión de trabajo", "70 bar", "bar", 70.0, "bar", "Nominal declarada", "HL100-7", "Ficha oficial Lüsqtoff HL100-7", "https://www.lusqtoff.com.ar/ver-producto/HL100-7", "pág. 1", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "100 bar", "bar", 100.0, "bar", "Corte", "HL100-7", "Ficha oficial Lüsqtoff HL100-7", "https://www.lusqtoff.com.ar/ver-producto/HL100-7", "pág. 1", "declarado"),
            "caudal_flujo": make_spec("caudal_flujo", "Caudal de flujo", "5,5 L/min", "L/min", 5.5, "L/min", "Condición no precisada", "HL100-7", "Ficha oficial Lüsqtoff HL100-7", "https://www.lusqtoff.com.ar/ver-producto/HL100-7", "pág. 1", "declarado"),
            "potencia": make_spec("potencia", "Potencia", "1200 W", "W", 1200.0, "W", "220 V / 50 Hz", "HL100-7", "Ficha oficial Lüsqtoff HL100-7", "https://www.lusqtoff.com.ar/ver-producto/HL100-7", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("HL100-7", "Argentina", "220 V / 50 Hz", "IRAM 2073", "HL100-7")],
        kits=[KitOption("HL100-7-STD", "Equipo con manguera 3m y lanza ajustable", "No aplica", "No aplica", ["Lanza", "Manguera 3m"])],
        commercial_offers=[CommercialOffer("Distribuidor Lüsqtoff", "Mercado Libre", "https://meli.la/1cZXqxL", 119999.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["HL100-7 tiene ficha propia y no hereda datos del HL100-8; motor de 1200 W frente a 2000 W del -8."],
        primary_sources=[{"label": "Ficha oficial Lüsqtoff HL100-7", "url": "https://www.lusqtoff.com.ar/ver-producto/HL100-7"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="lusqtoff-hl100-8",
        brand="Lüsqtoff",
        commercial_name="HL100-8 (150 bar máx.)",
        mpn="HL100-8",
        category="hidrolavadoras",
        summary="Hidrolavadora de 2000 W con 100 bar de trabajo continuo y 150 bar máximos permitidos en manual.",
        primary_use="Lavado doméstico exigente",
        power_source="Red eléctrica (220 V)",
        specs={
            "presion_trabajo": make_spec("presion_trabajo", "Presión de trabajo", "100 bar", "bar", 100.0, "bar", "Manual oficial Lüsqtoff HL100-8", "HL100-8", "Manual oficial Lüsqtoff HL100-8", "https://lusqtoff.com.ar/2023/uploads/Productos/4.%20HIDROLAVADORAS/HL100-8/MANUAL/Manual%20HL100-8-pdf%20curvas_compressed.pdf", "pág. 2", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión máxima permitida", "150 bar", "bar", 150.0, "bar", "Corte por presostato", "HL100-8", "Manual oficial Lüsqtoff HL100-8", "https://lusqtoff.com.ar/2023/uploads/Productos/4.%20HIDROLAVADORAS/HL100-8/MANUAL/Manual%20HL100-8-pdf%20curvas_compressed.pdf", "pág. 2", "declarado"),
            "caudal_trabajo": make_spec("caudal_trabajo", "Caudal de trabajo", "6,0 L/min", "L/min", 6.0, "L/min", "Continuo", "HL100-8", "Manual oficial Lüsqtoff HL100-8", "https://lusqtoff.com.ar/2023/uploads/Productos/4.%20HIDROLAVADORAS/HL100-8/MANUAL/Manual%20HL100-8-pdf%20curvas_compressed.pdf", "pág. 2", "declarado"),
            "caudal_maximo": make_spec("caudal_maximo", "Caudal máximo", "7,5 L/min", "L/min", 7.5, "L/min", "Sin contrapresión", "HL100-8", "Manual oficial Lüsqtoff HL100-8", "https://lusqtoff.com.ar/2023/uploads/Productos/4.%20HIDROLAVADORAS/HL100-8/MANUAL/Manual%20HL100-8-pdf%20curvas_compressed.pdf", "pág. 2", "declarado"),
            "potencia": make_spec("potencia", "Potencia", "2000 W", "W", 2000.0, "W", "220 V / 50 Hz", "HL100-8", "Manual oficial Lüsqtoff HL100-8", "https://lusqtoff.com.ar/2023/uploads/Productos/4.%20HIDROLAVADORAS/HL100-8/MANUAL/Manual%20HL100-8-pdf%20curvas_compressed.pdf", "pág. 2", "declarado"),
        },
        variants=[RegionalVariant("HL100-8", "Argentina", "220 V / 50 Hz", "IRAM 2073", "HL100-8")],
        kits=[KitOption("HL100-8-STD", "Equipo HL100-8 con manguera 5m y lanza rotativa", "No aplica", "No aplica", ["Lanza rotativa", "Manguera 5m"])],
        commercial_offers=[CommercialOffer("Distribuidor Oficial", "Mercado Libre", "https://meli.la/2HL1008", 189000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["No equivale al HL-150: el sufijo -8 tiene despiece y curvas propias en el manual oficial."],
        primary_sources=[{"label": "Manual oficial Lüsqtoff HL100-8", "url": "https://lusqtoff.com.ar/2023/uploads/Productos/4.%20HIDROLAVADORAS/HL100-8/MANUAL/Manual%20HL100-8-pdf%20curvas_compressed.pdf"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="lusqtoff-hl-120",
        brand="Lüsqtoff",
        commercial_name="HL-120 (105 bar máx.)",
        mpn="HL-120",
        category="hidrolavadoras",
        summary="Hidrolavadora intermedia de 1600 W con 70 bar de trabajo y 105 bar máximos permitidos.",
        primary_use="Lavado doméstico",
        power_source="Red eléctrica (220 V)",
        specs={
            "presion_trabajo": make_spec("presion_trabajo", "Presión de trabajo", "70 bar", "bar", 70.0, "bar", "Nominal", "HL-120", "Ficha técnica Lüsqtoff HL-120", "https://www.lusqtoff.com.ar/ver-producto/HL-120", "pág. 1", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión permitida", "105 bar", "bar", 105.0, "bar", "Corte", "HL-120", "Ficha técnica Lüsqtoff HL-120", "https://www.lusqtoff.com.ar/ver-producto/HL-120", "pág. 1", "declarado"),
            "caudal_trabajo": make_spec("caudal_trabajo", "Caudal de trabajo", "5,5 L/min", "L/min", 5.5, "L/min", "Continuo", "HL-120", "Ficha técnica Lüsqtoff HL-120", "https://www.lusqtoff.com.ar/ver-producto/HL-120", "pág. 1", "declarado"),
            "caudal_maximo": make_spec("caudal_maximo", "Caudal máximo", "6,8 L/min", "L/min", 6.8, "L/min", "Máximo", "HL-120", "Ficha técnica Lüsqtoff HL-120", "https://www.lusqtoff.com.ar/ver-producto/HL-120", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso", "5,2 kg", "kg", 5.2, "kg", "Neto", "HL-120", "Ficha técnica Lüsqtoff HL-120", "https://www.lusqtoff.com.ar/ver-producto/HL-120", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("HL-120", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Monofásica")],
        kits=[KitOption("HL-120-STD", "HL-120 con lanza y manguera 5m", "No aplica", "No aplica", ["Lanza", "Manguera 5m"])],
        commercial_offers=[CommercialOffer("Distribuidor Oficial", "Mercado Libre", "https://meli.la/1qPbvWX", 145000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Verificar manguera y kit; publicaciones pueden incluir dosificador de espuma o lanza básica."],
        primary_sources=[{"label": "Ficha oficial Lüsqtoff HL-120", "url": "https://www.lusqtoff.com.ar/ver-producto/HL-120"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="lusqtoff-hl-150",
        brand="Lüsqtoff",
        commercial_name="HL-150 (150 bar máx.)",
        mpn="HL-150",
        category="hidrolavadoras",
        summary="Hidrolavadora de 2000 W con ruedas de transporte y 100 bar de trabajo continuo.",
        primary_use="Lavado doméstico intensivo",
        power_source="Red eléctrica (220 V)",
        specs={
            "presion_trabajo": make_spec("presion_trabajo", "Presión de trabajo", "100 bar", "bar", 100.0, "bar", "Continuo", "HL-150", "Ficha oficial Lüsqtoff HL-150", "https://lusqtoff.com.ar/productos/HL-150", "pág. 1", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "150 bar", "bar", 150.0, "bar", "Corte", "HL-150", "Ficha oficial Lüsqtoff HL-150", "https://lusqtoff.com.ar/productos/HL-150", "pág. 1", "declarado"),
            "caudal_trabajo": make_spec("caudal_trabajo", "Caudal de trabajo", "6,0 L/min", "L/min", 6.0, "L/min", "Continuo", "HL-150", "Ficha oficial Lüsqtoff HL-150", "https://lusqtoff.com.ar/productos/HL-150", "pág. 1", "declarado"),
            "caudal_maximo": make_spec("caudal_maximo", "Caudal máximo", "7,5 L/min", "L/min", 7.5, "L/min", "Pico", "HL-150", "Ficha oficial Lüsqtoff HL-150", "https://lusqtoff.com.ar/productos/HL-150", "pág. 1", "declarado"),
            "potencia": make_spec("potencia", "Potencia", "2000 W", "W", 2000.0, "W", "220 V / 50 Hz", "HL-150", "Ficha oficial Lüsqtoff HL-150", "https://lusqtoff.com.ar/productos/HL-150", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("HL-150", "Argentina", "220 V / 50 Hz", "IRAM 2073", "HL-150")],
        kits=[KitOption("HL-150-STD", "HL-150 con ruedas y manguera 5m", "No aplica", "No aplica", ["Lanza", "Manguera 5m", "Ruedas"])],
        commercial_offers=[CommercialOffer("Distribuidor Oficial", "Mercado Libre", "https://meli.la/1X9cSf1", 209000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["150 bar es el valor máximo permitido de descarga; el trabajo sostenido es de 100 bar."],
        primary_sources=[{"label": "Ficha oficial Lüsqtoff HL-150", "url": "https://lusqtoff.com.ar/productos/HL-150"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="gamma-130-elite",
        brand="Gamma",
        commercial_name="130 Elite G2513AR",
        mpn="G2513AR",
        category="hidrolavadoras",
        summary="Hidrolavadora de 1600 W con 90 bar de servicio y 130 bar de presión admisible.",
        primary_use="Hogar y lavado de autos",
        power_source="Red eléctrica (220 V)",
        specs={
            "presion_servicio": make_spec("presion_servicio", "Presión de servicio", "90 bar (9 MPa)", "bar", 90.0, "bar", "Trabajo nominal", "G2513AR", "Ficha oficial Gamma 130 Elite", "https://www.gammaherramientas.com.ar/producto/hidrolavadora-130-elite/", "pág. 1", "declarado"),
            "presion_admisible": make_spec("presion_admisible", "Presión admisible", "130 bar (13 MPa)", "bar", 130.0, "bar", "Máxima", "G2513AR", "Ficha oficial Gamma 130 Elite", "https://www.gammaherramientas.com.ar/producto/hidrolavadora-130-elite/", "pág. 1", "declarado"),
            "caudal_publicado": make_spec("caudal_publicado", "Caudal publicado", "360 L/h (6 L/min)", "L/h", 360.0, "L/h", "Ficha Gamma", "G2513AR", "Ficha oficial Gamma 130 Elite", "https://www.gammaherramientas.com.ar/producto/hidrolavadora-130-elite/", "pág. 1", "declarado"),
            "potencia": make_spec("potencia", "Potencia", "1600 W", "W", 1600.0, "W", "220 V / 50 Hz", "G2513AR", "Ficha oficial Gamma 130 Elite", "https://www.gammaherramientas.com.ar/producto/hidrolavadora-130-elite/", "pág. 1", "declarado"),
            "manguera": make_spec("manguera", "Largo de manguera", "5 m", "m", 5.0, "m", "Alta presión", "G2513AR", "Ficha oficial Gamma 130 Elite", "https://www.gammaherramientas.com.ar/producto/hidrolavadora-130-elite/", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("G2513AR", "Argentina", "220 V / 50 Hz", "IRAM 2073", "130 Elite")],
        kits=[KitOption("G2513AR-STD", "Hidrolavadora con pistola, lanza y manguera 5m", "No aplica", "No aplica", ["Pistola", "Lanza", "Manguera 5m"])],
        commercial_offers=[CommercialOffer("Distribuidor Gamma", "Mercado Libre", "https://meli.la/2SuGMdL", 175000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Presión admisible de 130 bar no debe interpretarse como presión continua de lavado."],
        primary_sources=[{"label": "Ficha oficial Gamma 130 Elite", "url": "https://www.gammaherramientas.com.ar/producto/hidrolavadora-130-elite/"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="gamma-150-elite",
        brand="Gamma",
        commercial_name="150 Elite G2514AR",
        mpn="G2514AR",
        category="hidrolavadoras",
        summary="Hidrolavadora de 1800 W con 100 bar de servicio y 150 bar de presión admisible.",
        primary_use="Limpieza de muros, terrazas y vehículos",
        power_source="Red eléctrica (220 V)",
        specs={
            "presion_servicio": make_spec("presion_servicio", "Presión de servicio", "100 bar (10 MPa)", "bar", 100.0, "bar", "Trabajo nominal", "G2514AR", "Ficha oficial Gamma 150 Elite", "https://www.gammaherramientas.com.ar/producto/hidrolavadora-150-elite/", "pág. 1", "declarado"),
            "presion_admisible": make_spec("presion_admisible", "Presión admisible", "150 bar (15 MPa)", "bar", 150.0, "bar", "Máxima", "G2514AR", "Ficha oficial Gamma 150 Elite", "https://www.gammaherramientas.com.ar/producto/hidrolavadora-150-elite/", "pág. 1", "declarado"),
            "caudal_publicado": make_spec("caudal_publicado", "Caudal publicado", "400 L/h (6,7 L/min)", "L/h", 400.0, "L/h", "Ficha Gamma", "G2514AR", "Ficha oficial Gamma 150 Elite", "https://www.gammaherramientas.com.ar/producto/hidrolavadora-150-elite/", "pág. 1", "declarado"),
            "potencia": make_spec("potencia", "Potencia", "1800 W", "W", 1800.0, "W", "220 V / 50 Hz", "G2514AR", "Ficha oficial Gamma 150 Elite", "https://www.gammaherramientas.com.ar/producto/hidrolavadora-150-elite/", "pág. 1", "declarado"),
            "manguera": make_spec("manguera", "Largo de manguera", "5 m", "m", 5.0, "m", "Alta presión", "G2514AR", "Ficha oficial Gamma 150 Elite", "https://www.gammaherramientas.com.ar/producto/hidrolavadora-150-elite/", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("G2514AR", "Argentina", "220 V / 50 Hz", "IRAM 2073", "150 Elite")],
        kits=[KitOption("G2514AR-STD", "Equipo 150 Elite con lanza y manguera 5m", "No aplica", "No aplica", ["Pistola", "Lanza", "Manguera 5m"])],
        commercial_offers=[CommercialOffer("Distribuidor Gamma", "Mercado Libre", "https://meli.la/2G150EL", 219000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["No corresponde a Master Wash ni a Premium Wash: verificar código G2514AR en placa."],
        primary_sources=[{"label": "Ficha oficial Gamma 150 Elite", "url": "https://www.gammaherramientas.com.ar/producto/hidrolavadora-150-elite/"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="stihl-re-80-x",
        brand="STIHL",
        commercial_name="STIHL RE 80 X",
        mpn="RE020114539",
        category="hidrolavadoras",
        summary="Hidrolavadora compacta sin ruedas para fácil transporte y almacenamiento.",
        primary_use="Hogar y limpieza ligera",
        power_source="Red eléctrica (220-240 V)",
        specs={
            "presion_trabajo": make_spec("presion_trabajo", "Presión de trabajo", "90 bar", "bar", 90.0, "bar", "Catálogo STIHL Argentina", "RE020114539", "Catálogo STIHL Argentina", "https://www.stihl.com.ar/es/p/hidrolavadoras-re-80-x-141961", "pág. 1", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "120 bar", "bar", 120.0, "bar", "Corte", "RE020114539", "Catálogo STIHL Argentina", "https://www.stihl.com.ar/es/p/hidrolavadoras-re-80-x-141961", "pág. 1", "declarado"),
            "caudal_maximo": make_spec("caudal_maximo", "Caudal máximo", "430 L/h", "L/h", 430.0, "L/h", "Catálogo", "RE020114539", "Catálogo STIHL Argentina", "https://www.stihl.com.ar/es/p/hidrolavadoras-re-80-x-141961", "pág. 1", "declarado"),
            "potencia": make_spec("potencia", "Potencia", "1700 W", "W", 1700.0, "W", "220-240 V", "RE020114539", "Catálogo STIHL Argentina", "https://www.stihl.com.ar/es/p/hidrolavadoras-re-80-x-141961", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso", "7,0 kg", "kg", 7.0, "kg", "Sin ruedas", "RE020114539", "Catálogo STIHL Argentina", "https://www.stihl.com.ar/es/p/hidrolavadoras-re-80-x-141961", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("RE020114539", "Argentina", "220-240 V / 50 Hz", "IRAM 2073", "Compacta sin ruedas")],
        kits=[KitOption("RE020114539-STD", "RE 80 X con boquilla rotativa y boquilla abanico", "No aplica", "No aplica", ["Boquilla rotativa", "Boquilla abanico", "Manguera 5m"])],
        commercial_offers=[CommercialOffer("Distribuidor Oficial STIHL", "Mercado Libre", "https://meli.la/1wzSW2u", 299000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Diseño sin carro de ruedas; debe trasladarse levantándola de la empuñadura integrada."],
        primary_sources=[{"label": "Catálogo STIHL RE 80 X", "url": "https://www.stihl.com.ar/es/p/hidrolavadoras-re-80-x-141961"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="stihl-re-90",
        brand="STIHL",
        commercial_name="STIHL RE 90",
        mpn="RE020114544",
        category="hidrolavadoras",
        summary="Hidrolavadora de 100 bar de trabajo con ruedas de transporte integradas y boquillas de cambio rápido.",
        primary_use="Hogar, vehículos y veredas",
        power_source="Red eléctrica (220-240 V)",
        specs={
            "presion_trabajo": make_spec("presion_trabajo", "Presión de trabajo", "100 bar", "bar", 100.0, "bar", "Catálogo STIHL", "RE020114544", "Catálogo oficial STIHL Argentina", "https://www.stihl.com.ar/es/p/hidrolavadoras-re-90-141963", "pág. 1", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "130 bar", "bar", 130.0, "bar", "Corte", "RE020114544", "Catálogo oficial STIHL Argentina", "https://www.stihl.com.ar/es/p/hidrolavadoras-re-90-141963", "pág. 1", "declarado"),
            "caudal_maximo": make_spec("caudal_maximo", "Caudal máximo", "440 L/h", "L/h", 440.0, "L/h", "Catálogo", "RE020114544", "Catálogo oficial STIHL Argentina", "https://www.stihl.com.ar/es/p/hidrolavadoras-re-90-141963", "pág. 1", "declarado"),
            "manguera": make_spec("manguera", "Largo de manguera", "6 m", "m", 6.0, "m", "Reforzada", "RE020114544", "Catálogo oficial STIHL Argentina", "https://www.stihl.com.ar/es/p/hidrolavadoras-re-90-141963", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("RE020114544", "Argentina", "220-240 V / 50 Hz", "IRAM 2073", "Con ruedas")],
        kits=[KitOption("RE020114544-STD", "RE 90 con carro de transporte y boquilla turbo", "No aplica", "No aplica", ["Carro", "Boquilla rotativa", "Manguera 6m"])],
        commercial_offers=[CommercialOffer("Distribuidor Oficial STIHL", "Mercado Libre", "https://meli.la/2SRE90", 355000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Se toma la variante argentina RE020114544 de 50 Hz; ofertas extranjeras de 60 Hz no son compatibles."],
        primary_sources=[{"label": "Catálogo STIHL RE 90", "url": "https://www.stihl.com.ar/es/p/hidrolavadoras-re-90-141963"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="stihl-re-110",
        brand="STIHL",
        commercial_name="STIHL RE 110",
        mpn="49500114529",
        category="hidrolavadoras",
        summary="Hidrolavadora con motor de inducción silencioso, 110 bar de trabajo y bomba de aluminio.",
        primary_use="Lavado frecuente en hogar y talleres",
        power_source="Red eléctrica (220-240 V)",
        specs={
            "presion_trabajo": make_spec("presion_trabajo", "Presión de trabajo", "110 bar", "bar", 110.0, "bar", "Catálogo STIHL", "49500114529", "Catálogo oficial STIHL Argentina", "https://www.stihl.com.ar/es/ap/re-110-81523", "pág. 1", "declarado"),
            "caudal_maximo": make_spec("caudal_maximo", "Caudal de agua", "440 L/h", "L/h", 440.0, "L/h", "Catálogo", "49500114529", "Catálogo oficial STIHL Argentina", "https://www.stihl.com.ar/es/ap/re-110-81523", "pág. 1", "declarado"),
            "manguera": make_spec("manguera", "Largo de manguera", "7 m", "m", 7.0, "m", "Malla reforzada", "49500114529", "Catálogo oficial STIHL Argentina", "https://www.stihl.com.ar/es/ap/re-110-81523", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso", "17,6 kg", "kg", 17.6, "kg", "Bomba de aluminio", "49500114529", "Catálogo oficial STIHL Argentina", "https://www.stihl.com.ar/es/ap/re-110-81523", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("49500114529", "Argentina", "220-240 V / 50 Hz", "IRAM 2073", "Motor inducción")],
        kits=[KitOption("49500114529-STD", "RE 110 con manguera 7m y compartimento de boquillas", "No aplica", "No aplica", ["Lanza abanico", "Lanza turbo", "Manguera 7m"])],
        commercial_offers=[CommercialOffer("Distribuidor Oficial STIHL", "Mercado Libre", "https://meli.la/2SRE110", 485000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Peso de 17,6 kg por motor de inducción y cabezal de aluminio; mayor durabilidad pero menor portabilidad manual."],
        primary_sources=[{"label": "Catálogo STIHL RE 110", "url": "https://www.stihl.com.ar/es/ap/re-110-81523"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="stihl-re-120",
        brand="STIHL",
        commercial_name="STIHL RE 120",
        mpn="49500114532",
        category="hidrolavadoras",
        summary="Hidrolavadora de 160 bar máximos con motor de inducción y manguera de malla de acero de 8 m.",
        primary_use="Uso doméstico intensivo y pequeñas empresas",
        power_source="Red eléctrica (220-240 V)",
        specs={
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "160 bar", "bar", 160.0, "bar", "Corte presostato", "49500114532", "Catálogo STIHL Argentina", "https://www.stihl.com.ar/es/p/hidrolavadoras-re-120-81512", "pág. 1", "declarado"),
            "caudal_maximo": make_spec("caudal_maximo", "Caudal máximo", "480 L/h", "L/h", 480.0, "L/h", "Catálogo", "49500114532", "Catálogo STIHL Argentina", "https://www.stihl.com.ar/es/p/hidrolavadoras-re-120-81512", "pág. 1", "declarado"),
            "manguera": make_spec("manguera", "Largo de manguera", "8 m malla acero", "m", 8.0, "m", "Acero reforzado", "49500114532", "Catálogo STIHL Argentina", "https://www.stihl.com.ar/es/p/hidrolavadoras-re-120-81512", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso", "20,0 kg", "kg", 20.0, "kg", "Neto", "49500114532", "Catálogo STIHL Argentina", "https://www.stihl.com.ar/es/p/hidrolavadoras-re-120-81512", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("49500114532", "Argentina", "220-240 V / 50 Hz", "IRAM 2073", "Malla de acero")],
        kits=[KitOption("49500114532-STD", "RE 120 con manguera 8m de acero y depósito de detergente dosificable", "No aplica", "No aplica", ["Lanza turbo", "Lanza abanico", "Manguera acero 8m"])],
        commercial_offers=[CommercialOffer("Distribuidor Oficial STIHL", "Mercado Libre", "https://meli.la/2SRE120", 590000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Presión de trabajo nominal no publicada en ficha web de referencia; solo consta el máximo de 160 bar."],
        primary_sources=[{"label": "Catálogo STIHL RE 120", "url": "https://www.stihl.com.ar/es/p/hidrolavadoras-re-120-81512"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="stihl-re-150",
        brand="STIHL",
        commercial_name="STIHL RE 150 Semiprofesional",
        mpn="49500114550",
        category="hidrolavadoras",
        summary="Hidrolavadora semiprofesional con cabezal de latón, pistones cerámicos y 140 bar de trabajo continuo.",
        primary_use="Lavaderos, campo y mantenimiento comercial",
        power_source="Red eléctrica (220-240 V)",
        specs={
            "presion_trabajo": make_spec("presion_trabajo", "Presión de trabajo", "120–140 bar", "bar", 140.0, "bar", "Trabajo continuo", "49500114550", "Catálogo STIHL Argentina", "https://www.stihl.com.ar/es/p/hidrolavadoras-re-150-109158", "pág. 1", "declarado"),
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "180 bar", "bar", 180.0, "bar", "Pico", "49500114550", "Catálogo STIHL Argentina", "https://www.stihl.com.ar/es/p/hidrolavadoras-re-150-109158", "pág. 1", "declarado"),
            "caudal_maximo": make_spec("caudal_maximo", "Caudal de agua", "468–540 L/h", "L/h", 540.0, "L/h", "Nominal continuo", "49500114550", "Catálogo STIHL Argentina", "https://www.stihl.com.ar/es/p/hidrolavadoras-re-150-109158", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso neto", "30,0 kg", "kg", 30.0, "kg", "Cabezal latón", "49500114550", "Catálogo STIHL Argentina", "https://www.stihl.com.ar/es/p/hidrolavadoras-re-150-109158", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("49500114550", "Argentina", "220-240 V / 50 Hz", "IRAM 2073", "Cabezal de latón")],
        kits=[KitOption("49500114550-STD", "RE 150 con chasis reforzado de transporte y manguera de acero", "No aplica", "No aplica", ["Lanza profesional", "Manguera acero", "Carro"])],
        commercial_offers=[CommercialOffer("Distribuidor Oficial STIHL", "Mercado Libre", "https://meli.la/2SRE150", 980000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Equipo de 30 kg; requiere toma eléctrica reforzada de 16 A protegida."],
        primary_sources=[{"label": "Catálogo STIHL RE 150", "url": "https://www.stihl.com.ar/es/p/hidrolavadoras-re-150-109158"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="comet-k-250-10-150",
        brand="Comet",
        commercial_name="Comet K 250 10/150 Classic",
        mpn="C2582AR",
        category="hidrolavadoras",
        summary="Hidrolavadora profesional de agua fría monofásica con bomba de tres pistones cerámicos a 1400 rpm.",
        primary_use="Lavaderos profesionales, talleres mecánicos e industrias",
        power_source="Red eléctrica (230 V monofásica)",
        specs={
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "150 bar", "bar", 150.0, "bar", "Corte", "C2582AR", "Ficha técnica oficial Comet", "https://www.gammaherramientas.com.ar/producto/hidrolavadora-comet-k-250-10-150-classic/", "pág. 1", "declarado"),
            "caudal_maximo": make_spec("caudal_maximo", "Caudal de agua", "10 L/min (600 L/h)", "L/min", 10.0, "L/min", "Bomba 1400 rpm", "C2582AR", "Ficha técnica oficial Comet", "https://www.gammaherramientas.com.ar/producto/hidrolavadora-comet-k-250-10-150-classic/", "pág. 1", "declarado"),
            "velocidad_bomba": make_spec("velocidad_bomba", "Velocidad de giro bomba", "1400 rpm", "rpm", 1400.0, "rpm", "Baja velocidad para trabajo continuo", "C2582AR", "Ficha técnica oficial Comet", "https://www.gammaherramientas.com.ar/producto/hidrolavadora-comet-k-250-10-150-classic/", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("C2582AR", "Argentina", "230 V / 50 Hz", "IRAM 2073 16A", "Bomba cerámica 1400 rpm")],
        kits=[KitOption("C2582AR-STD", "Comet K 250 con pistola profesional y manguera de alta presión", "No aplica", "No aplica", ["Pistola giratoria", "Lanza con regulación", "Manguera 10m"])],
        commercial_offers=[CommercialOffer("Distribuidor Comet Argentina", "Mercado Libre", "https://meli.la/2COMET150", 1450000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["1400 rpm asegura régimen continuo pero requiere suministro continuo de agua de al menos 750 L/h sin burbujas."],
        primary_sources=[{"label": "Ficha oficial Comet K 250 10/150", "url": "https://www.gammaherramientas.com.ar/producto/hidrolavadora-comet-k-250-10-150-classic/"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="comet-k-250-13-190",
        brand="Comet",
        commercial_name="Comet K 250 TSR 13/190 T Classic",
        mpn="C2583AR",
        category="hidrolavadoras",
        summary="Hidrolavadora industrial trifásica de 190 bar con caudal de 13 L/min y sistema Total Stop Retardado.",
        primary_use="Lavado intensivo industrial y agro",
        power_source="Red eléctrica trifásica (400 V)",
        specs={
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "190 bar", "bar", 190.0, "bar", "Máxima admisible", "C2583AR", "Ficha técnica oficial Comet", "https://www.gammaherramientas.com.ar/producto/hidrolavadora-comet-k-250-tsr-13-190-t-classic/", "pág. 1", "declarado"),
            "caudal_maximo": make_spec("caudal_maximo", "Caudal de agua", "13 L/min (780 L/h)", "L/min", 13.0, "L/min", "Nominal continuo", "C2583AR", "Ficha técnica oficial Comet", "https://www.gammaherramientas.com.ar/producto/hidrolavadora-comet-k-250-tsr-13-190-t-classic/", "pág. 1", "declarado"),
            "suministro_minimo": make_spec("suministro_minimo", "Suministro mínimo de red", "970 L/h", "L/h", 970.0, "L/h", "Para evitar cavitación de bomba", "C2583AR", "Ficha técnica oficial Comet", "https://www.gammaherramientas.com.ar/producto/hidrolavadora-comet-k-250-tsr-13-190-t-classic/", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("C2583AR", "Argentina", "400 V / 50 Hz", "IEC trifásico", "Trifásica")],
        kits=[KitOption("C2583AR-STD", "K 250 trifásica con TSR y lanza profesional", "No aplica", "No aplica", ["Lanza regulable", "Manguera 10m", "Pistola TSR"])],
        commercial_offers=[CommercialOffer("Distribuidor Comet Industrial", "Mercado Libre", "https://meli.la/2COMET190", 1850000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Exige conexión trifásica 400 V y suministro mínimo de 970 L/h; no funciona con canillas residenciales estándar."],
        primary_sources=[{"label": "Ficha oficial Comet K 250 13/190 T", "url": "https://www.gammaherramientas.com.ar/producto/hidrolavadora-comet-k-250-tsr-13-190-t-classic/"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="logus-hl-105",
        brand="Logus",
        commercial_name="Logus HL-105 (105 bar)",
        mpn="HL-105",
        category="hidrolavadoras",
        summary="Hidrolavadora compacta de 1200 W con 105 bar declarados para limpieza hogareña.",
        primary_use="Hogar y jardín",
        power_source="Red eléctrica (220 V)",
        specs={
            "presion_maxima": make_spec("presion_maxima", "Presión máxima", "105 bar", "bar", 105.0, "bar", "Declarada por marca", "HL-105", "Ficha técnica Logus HL-105", "https://logus.com.ar/productos/hidrolavadora-105-bar-1200w-hl-105/", "pág. 1", "declarado"),
            "caudal_flujo": make_spec("caudal_flujo", "Caudal de flujo", "6,5 L/min", "L/min", 6.5, "L/min", "Condición no informada", "HL-105", "Ficha técnica Logus HL-105", "https://logus.com.ar/productos/hidrolavadora-105-bar-1200w-hl-105/", "pág. 1", "declarado"),
            "potencia": make_spec("potencia", "Potencia", "1200 W", "W", 1200.0, "W", "220 V", "HL-105", "Ficha técnica Logus HL-105", "https://logus.com.ar/productos/hidrolavadora-105-bar-1200w-hl-105/", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("HL-105", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Monofásica")],
        kits=[KitOption("HL-105-STD", "Logus HL-105 con pistola, lanza y dosificador", "No aplica", "No aplica", ["Lanza", "Manguera", "Dosificador"])],
        commercial_offers=[CommercialOffer("Distribuidor Logus", "Mercado Libre", "https://meli.la/2Rcddpg", 95000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Caudal bajo condición no precisada; los 105 bar representan presión máxima pico sin carga de salida prolongada."],
        primary_sources=[{"label": "Ficha oficial Logus HL-105", "url": "https://logus.com.ar/productos/hidrolavadora-105-bar-1200w-hl-105/"}],
        last_reviewed="2026-10-01"
    )
]
