"""Datos técnicos de 15 modelos de Soldadoras y Generadores en Argentina."""

from tallerlab_data.catalog_data.common import make_spec
from tallerlab_data.models import (
    CommercialOffer,
    ContradictionRecord,
    KitOption,
    RegionalVariant,
    TechnicalTool,
)

SOLDADORAS_GENERADORES_TOOLS = [
    TechnicalTool(
        slug="esab-handyarc-132i",
        brand="ESAB",
        commercial_name="HandyArc 132i Inverter MMA",
        mpn="0409614",
        category="soldadoras",
        summary="Soldadora inverter ultra compacta de 3,5 kg para electrodos revestidos de hasta 2,5 mm.",
        primary_use="Reparaciones ligeras, cerrajería y mantenimiento",
        power_source="Red eléctrica (220 V)",
        specs={
            "corriente_maxima": make_spec("corriente_maxima", "Rango de corriente", "20–130 A", "A", 130.0, "A", "Electrodo MMA", "0409614", "Ficha técnica ESAB HandyArc", "https://esab.com/ar/sam_es/products-solutions/product/welding-equipment/stick-welders-smaw/handyarc-132i-dv-142i-162i/", "pág. 1", "declarado"),
            "ciclo_trabajo_20": make_spec("ciclo_trabajo_20", "Ciclo de trabajo al 20%", "130 A (20%)", "A", 130.0, "A", "A 40°C de temperatura ambiente", "0409614", "Ficha técnica ESAB HandyArc", "https://esab.com/ar/sam_es/products-solutions/product/welding-equipment/stick-welders-smaw/handyarc-132i-dv-142i-162i/", "pág. 1", "declarado"),
            "ciclo_trabajo_100": make_spec("ciclo_trabajo_100", "Ciclo continuo al 100%", "58 A (100%)", "A", 58.0, "A", "Trabajo ininterrumpido", "0409614", "Ficha técnica ESAB HandyArc", "https://esab.com/ar/sam_es/products-solutions/product/welding-equipment/stick-welders-smaw/handyarc-132i-dv-142i-162i/", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso neto", "3,5 kg", "kg", 3.5, "kg", "Solo fuente de poder", "0409614", "Ficha técnica ESAB HandyArc", "https://esab.com/ar/sam_es/products-solutions/product/welding-equipment/stick-welders-smaw/handyarc-132i-dv-142i-162i/", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("0409614", "Argentina", "220 V / 50 Hz", "IRAM 2073", "HandyArc 132i")],
        kits=[KitOption("0409614-STD", "Soldadora con cable de pinza portaelectrodo, pinza de masa y correa de hombro", "No aplica", "No aplica", ["Pinza portaelectrodo 3m", "Pinza de masa 2m", "Correa"])],
        commercial_offers=[CommercialOffer("Distribuidor ESAB", "Mercado Libre", "https://meli.la/2ESAB132", 199000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Ciclo continuo de 58 A; apto para electrodos de 2,0 mm en continuo y 2,5 mm con pausas."],
        primary_sources=[{"label": "Ficha oficial ESAB HandyArc", "url": "https://esab.com/ar/sam_es/products-solutions/product/welding-equipment/stick-welders-smaw/handyarc-132i-dv-142i-162i/"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="esab-handyarc-142i",
        brand="ESAB",
        commercial_name="HandyArc 142i Inverter MMA",
        mpn="0409615",
        category="soldadoras",
        summary="Soldadora inverter de 140 A para electrodos de 2,5 mm continuo y 3,25 mm intermitente.",
        primary_use="Herrería artesanal y reparaciones",
        power_source="Red eléctrica (220 V)",
        specs={
            "corriente_maxima": make_spec("corriente_maxima", "Rango de corriente", "20–140 A", "A", 140.0, "A", "Electrodo MMA", "0409615", "Ficha técnica ESAB HandyArc", "https://esab.com/ar/sam_es/products-solutions/product/welding-equipment/stick-welders-smaw/handyarc-132i-dv-142i-162i/", "pág. 1", "declarado"),
            "ciclo_trabajo_20": make_spec("ciclo_trabajo_20", "Ciclo de trabajo al 20%", "140 A (20%)", "A", 140.0, "A", "A 40°C", "0409615", "Ficha técnica ESAB HandyArc", "https://esab.com/ar/sam_es/products-solutions/product/welding-equipment/stick-welders-smaw/handyarc-132i-dv-142i-162i/", "pág. 1", "declarado"),
            "ciclo_trabajo_100": make_spec("ciclo_trabajo_100", "Ciclo continuo al 100%", "63 A (100%)", "A", 63.0, "A", "Ininterrumpido", "0409615", "Ficha técnica ESAB HandyArc", "https://esab.com/ar/sam_es/products-solutions/product/welding-equipment/stick-welders-smaw/handyarc-132i-dv-142i-162i/", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("0409615", "Argentina", "220 V / 50 Hz", "IRAM 2073", "HandyArc 142i")],
        kits=[KitOption("0409615-STD", "Fuente HandyArc 142i con cables y pinzas", "No aplica", "No aplica", ["Pinzas completas", "Correa"])],
        commercial_offers=[CommercialOffer("Distribuidor ESAB", "Mercado Libre", "https://meli.la/2ESAB142", 225000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Para electrodo 3,25 mm E6013 trabajar en cordones cortos para no disparar la protección térmica."],
        primary_sources=[{"label": "Ficha oficial ESAB HandyArc", "url": "https://esab.com/ar/sam_es/products-solutions/product/welding-equipment/stick-welders-smaw/handyarc-132i-dv-142i-162i/"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="esab-handyarc-162i",
        brand="ESAB",
        commercial_name="HandyArc 162i Inverter MMA",
        mpn="0409616",
        category="soldadoras",
        summary="Soldadora inverter de 160 A para electrodos de hasta 3,25 mm continuos con panel analógico de ajuste preciso.",
        primary_use="Herrería pesada, estructuras y mantenimiento en obra",
        power_source="Red eléctrica (220 V)",
        specs={
            "corriente_maxima": make_spec("corriente_maxima", "Rango de corriente", "20–160 A", "A", 160.0, "A", "Electrodo MMA", "0409616", "Ficha técnica ESAB HandyArc", "https://esab.com/ar/sam_es/products-solutions/product/welding-equipment/stick-welders-smaw/handyarc-132i-dv-142i-162i/", "pág. 1", "declarado"),
            "ciclo_trabajo_20": make_spec("ciclo_trabajo_20", "Ciclo de trabajo al 20%", "160 A (20%)", "A", 160.0, "A", "Norma IEC 60974-1 a 40°C", "0409616", "Ficha técnica ESAB HandyArc", "https://esab.com/ar/sam_es/products-solutions/product/welding-equipment/stick-welders-smaw/handyarc-132i-dv-142i-162i/", "pág. 1", "declarado"),
            "ciclo_trabajo_100": make_spec("ciclo_trabajo_100", "Ciclo continuo al 100%", "72 A (100%)", "A", 72.0, "A", "Continuo a 40°C", "0409616", "Ficha técnica ESAB HandyArc", "https://esab.com/ar/sam_es/products-solutions/product/welding-equipment/stick-welders-smaw/handyarc-132i-dv-142i-162i/", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso neto", "3,7 kg", "kg", 3.7, "kg", "Balanza", "0409616", "Ficha técnica ESAB HandyArc", "https://esab.com/ar/sam_es/products-solutions/product/welding-equipment/stick-welders-smaw/handyarc-132i-dv-142i-162i/", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("0409616", "Argentina", "220 V / 50 Hz", "IRAM 2073", "HandyArc 162i")],
        kits=[KitOption("0409616-STD", "HandyArc 162i con pinza portaelectrodo reforzada, pinza de masa y correa", "No aplica", "No aplica", ["Pinza portaelectrodo 3m", "Pinza masa 2m", "Correa hombro"])],
        commercial_offers=[CommercialOffer("Distribuidor ESAB", "Mercado Libre", "https://meli.la/1mZhwNS", 265000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Corriente máxima (160 A al 20%) y corriente continua (72 A al 100%) son magnitudes distintas; para cordones largos sin interrupción respetar el ciclo al 100%."],
        primary_sources=[{"label": "Ficha oficial ESAB HandyArc 162i", "url": "https://esab.com/ar/sam_es/products-solutions/product/welding-equipment/stick-welders-smaw/handyarc-132i-dv-142i-162i/"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="lusqtoff-iron-100",
        brand="Lüsqtoff",
        commercial_name="MEGAIRON100-8 Inverter",
        mpn="MEGAIRON100-8",
        category="soldadoras",
        summary="Soldadora inverter compacta de entrada con hasta 105 A declarados para electrodos de 1,6 a 2,5 mm.",
        primary_use="Hogar y bricolaje ligero",
        power_source="Red eléctrica (220 V)",
        specs={
            "corriente_maxima": make_spec("corriente_maxima", "Corriente máxima", "105 A al 30% declarado", "A", 105.0, "A", "Ciclo declarado por marca", "MEGAIRON100-8", "Ficha técnica oficial Lüsqtoff", "https://www.lusqtoff.com.ar/ver-producto/MEGAIRON100-8", "pág. 1", "declarado"),
            "proceso": make_spec("proceso", "Proceso de soldadura", "MMA (Electrodo revestido)", "tipo", 0.0, "tipo", "Rutílico E6013", "MEGAIRON100-8", "Ficha técnica oficial Lüsqtoff", "https://www.lusqtoff.com.ar/ver-producto/MEGAIRON100-8", "pág. 1", "declarado"),
            "alimentacion": make_spec("alimentacion", "Tensión de entrada", "220 V / 50 Hz", "V", 220.0, "V", "Monofásica", "MEGAIRON100-8", "Ficha técnica oficial Lüsqtoff", "https://www.lusqtoff.com.ar/ver-producto/MEGAIRON100-8", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("MEGAIRON100-8", "Argentina", "220 V / 50 Hz", "IRAM 2073", "MEGAIRON")],
        kits=[KitOption("MEGAIRON100-8-KIT", "Kit con máscara fotosensible, pinzas y dos escuadras magnéticas", "No aplica", "No aplica", ["Máscara fotosensible", "2 escuadras magnéticas", "Pinzas"])],
        commercial_offers=[CommercialOffer("Distribuidor Lüsqtoff", "Mercado Libre", "https://meli.la/1knTbU1", 139000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["105 A al 30% exige pausas de 7 minutos por cada 3 minutos de soldadura al amperaje máximo."],
        primary_sources=[{"label": "Ficha oficial Lüsqtoff MEGAIRON100-8", "url": "https://www.lusqtoff.com.ar/ver-producto/MEGAIRON100-8"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="lusqtoff-sml120-8dk",
        brand="Lüsqtoff",
        commercial_name="SML120-8DK MIG Flux Multiproceso",
        mpn="SML120-8DK",
        category="soldadoras",
        summary="Soldadora multiproceso (MIG Flux, MMA, Lift TIG) con discrepancia de tensión documentada en ficha web oficial.",
        primary_use="Soldadura sin gas en chapa fina y perfiles livianos",
        power_source="Red eléctrica (220 V nominal / 200 V en ficha)",
        specs={
            "corriente_flux": make_spec("corriente_flux", "Rango corriente FLUX", "20–120 A", "A", 120.0, "A", "Alambre tubular sin gas", "SML120-8DK", "Ficha oficial Lüsqtoff SML120-8DK", "https://lusqtoff.com.ar/ver-producto/SML120-8DK", "pág. 1", "declarado"),
            "corriente_mma_tig": make_spec("corriente_mma_tig", "Rango corriente MMA / Lift TIG", "20–100 A", "A", 100.0, "A", "Electrodo y TIG", "SML120-8DK", "Ficha oficial Lüsqtoff SML120-8DK", "https://lusqtoff.com.ar/ver-producto/SML120-8DK", "pág. 1", "declarado"),
            "tension_alimentacion": make_spec("tension_alimentacion", "Tensión declarada en ficha", "200 V – 50 Hz", "V", 200.0, "V", "Ficha web oficial", "SML120-8DK", "Ficha oficial Lüsqtoff SML120-8DK", "https://lusqtoff.com.ar/ver-producto/SML120-8DK", "pág. 1", "contradictorio", notes="La ficha oficial imprime 200 V - 50 Hz en lugar de los 220 V estándar de la red argentina."),
            "procesos": make_spec("procesos", "Procesos admitidos", "MIG flux / MMA / Lift TIG", "tipo", 0.0, "tipo", "3 en 1", "SML120-8DK", "Ficha oficial Lüsqtoff SML120-8DK", "https://lusqtoff.com.ar/ver-producto/SML120-8DK", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("SML120-8DK", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Multiproceso FLUX")],
        kits=[KitOption("SML120-8DK-KIT", "Kit completo con torcha MIG integrada, máscara, rollo flux y pinzas", "No aplica", "No aplica", ["Torcha MIG fija", "Pinza masa", "Rollo flux 0,8mm", "Máscara"])],
        commercial_offers=[CommercialOffer("Distribuidor Lüsqtoff", "Mercado Libre", "https://meli.la/26RsZRw", 215000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[
            ContradictionRecord(
                spec_key="tension_alimentacion",
                field_name="Tensión de red especificada",
                source_a_name="Ficha web Lüsqtoff SML120-8DK",
                source_a_value="200 V - 50 Hz",
                source_a_url="https://lusqtoff.com.ar/ver-producto/SML120-8DK",
                source_b_name="Estándar IRAM red eléctrica argentina",
                source_b_value="220 V - 50 Hz",
                source_b_url="https://www.enre.gov.ar",
                editorial_note="La ficha declara textualmente 200 V. Confirmar placa metálica de la máquina antes de operar para certificar rango de tolerancia de entrada."
            )
        ],
        limits_and_warnings=[
            "120 A corresponde únicamente al modo FLUX; en electrodo revestido y TIG la corriente máxima es de 100 A.",
            "Torcha MIG incorporada fija al chasis; no cuenta con conector Euroconector extraíble."
        ],
        primary_sources=[{"label": "Ficha oficial Lüsqtoff SML120-8DK", "url": "https://lusqtoff.com.ar/ver-producto/SML120-8DK"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="lusqtoff-iron-250",
        brand="Lüsqtoff",
        commercial_name="Iron 250 Inverter MMA",
        mpn="IRON-250",
        category="soldadoras",
        summary="Soldadora inverter de 200 A con ciclo de trabajo del 60% para electrodos pesados de 3,25 y 4 mm.",
        primary_use="Estructuras metálicas y calderería ligera",
        power_source="Red eléctrica (220 V)",
        specs={
            "corriente_maxima": make_spec("corriente_maxima", "Corriente máxima", "200 A", "A", 200.0, "A", "Electrodo MMA", "IRON-250", "Ficha técnica Lüsqtoff Iron 250", "https://lusqtoff.com.ar/ver-producto/IRON-250", "pág. 1", "declarado"),
            "ciclo_trabajo": make_spec("ciclo_trabajo", "Ciclo de trabajo", "200 A al 60%", "A", 200.0, "A", "A temperatura nominal", "IRON-250", "Ficha técnica Lüsqtoff Iron 250", "https://lusqtoff.com.ar/ver-producto/IRON-250", "pág. 1", "declarado"),
            "display": make_spec("display", "Display digital", "Presente", "tipo", 0.0, "tipo", "Lectura digital de amperaje", "IRON-250", "Ficha técnica Lüsqtoff Iron 250", "https://lusqtoff.com.ar/ver-producto/IRON-250", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("IRON-250", "Argentina", "220 V / 50 Hz", "IRAM 2073 20A", "Heavy Duty")],
        kits=[KitOption("IRON-250-STD", "Soldadora Iron 250 con pinzas profesionales reforzadas", "No aplica", "No aplica", ["Pinza portaelectrodo", "Pinza masa", "Cepillo piqueta"])],
        commercial_offers=[CommercialOffer("Distribuidor Oficial", "Mercado Libre", "https://meli.la/2IRON250", 299000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Exige ficha macho IRAM de 20 A y circuito con termomagnética adecuada en instalación de taller."],
        primary_sources=[{"label": "Ficha oficial Lüsqtoff Iron 250", "url": "https://lusqtoff.com.ar/ver-producto/IRON-250"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="gamma-elite-200",
        brand="Gamma",
        commercial_name="Gamma Elite 200 G2462AR",
        mpn="G2462AR",
        category="soldadoras",
        summary="Inverter para electrodos y TIG Lift con corriente máxima de 180 A al 40% de ciclo.",
        primary_use="Taller y cerrajería",
        power_source="Red eléctrica (220 V)",
        specs={
            "corriente_maxima": make_spec("corriente_maxima", "Corriente máxima", "180 A al 40%", "A", 180.0, "A", "Norma de ensayo Gamma", "G2462AR", "Ficha oficial Gamma G2462AR", "https://www.gammaherramientas.com.ar/producto/soldadora-inverter-elite-200/", "pág. 1", "declarado"),
            "ciclo_trabajo_100": make_spec("ciclo_trabajo_100", "Ciclo al 100%", "114 A (100%)", "A", 114.0, "A", "Continuo", "G2462AR", "Ficha oficial Gamma G2462AR", "https://www.gammaherramientas.com.ar/producto/soldadora-inverter-elite-200/", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso neto", "4,5 kg", "kg", 4.5, "kg", "Balanza", "G2462AR", "Ficha oficial Gamma G2462AR", "https://www.gammaherramientas.com.ar/producto/soldadora-inverter-elite-200/", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("G2462AR", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Elite 200")],
        kits=[KitOption("G2462AR-STD", "Soldadora con pinzas y cables de conexión rápida DINSE", "No aplica", "No aplica", ["Pinzas DINSE", "Cepillo", "Correa"])],
        commercial_offers=[CommercialOffer("Distribuidor Gamma", "Mercado Libre", "https://meli.la/2GELITE200", 279000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["La denominación 'Elite 200' es comercial; la corriente máxima declarada por el fabricante es de 180 A."],
        primary_sources=[{"label": "Ficha oficial Gamma Elite 200", "url": "https://www.gammaherramientas.com.ar/producto/soldadora-inverter-elite-200/"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="lusqtoff-mig-195",
        brand="Lüsqtoff",
        commercial_name="Lüsqtoff MIG-195 Con y Sin Gas",
        mpn="MIG-195",
        category="soldadoras",
        summary="Soldadora MIG/MAG tradicional monofásica de 180 A con euroconector y regulación de 6 puntos.",
        primary_use="Carrocería, chapa de automoción y carpintería metálica",
        power_source="Red eléctrica (220 V)",
        specs={
            "corriente_maxima": make_spec("corriente_maxima", "Corriente máxima", "180 A al 15%", "A", 180.0, "A", "MIG/MAG", "MIG-195", "Ficha técnica Lüsqtoff MIG-195", "https://lusqtoff.com.ar/ver-producto/MIG-195", "pág. 1", "declarado"),
            "bobina_alambre": make_spec("bobina_alambre", "Capacidad de bobina", "Hasta 5 kg (200 mm)", "kg", 5.0, "kg", "Acepta rollos de 1 y 5 kg", "MIG-195", "Ficha técnica Lüsqtoff MIG-195", "https://lusqtoff.com.ar/ver-producto/MIG-195", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso neto", "35 kg", "kg", 35.0, "kg", "Transformador bobinado", "MIG-195", "Ficha técnica Lüsqtoff MIG-195", "https://lusqtoff.com.ar/ver-producto/MIG-195", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("MIG-195", "Argentina", "220 V / 50 Hz", "IRAM 2073 20A", "Con ruedas")],
        kits=[KitOption("MIG-195-STD", "Soldadora MIG con torcha euroconector, manguera de gas y pinza masa", "No aplica", "No aplica", ["Torcha euroconector", "Manguera de gas", "Ruedas"])],
        commercial_offers=[CommercialOffer("Distribuidor Oficial", "Mercado Libre", "https://meli.la/2MIG195", 465000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Equipo electromecánico con transformador tradicional (35 kg); no es tecnología inverter ligera."],
        primary_sources=[{"label": "Ficha oficial Lüsqtoff MIG-195", "url": "https://lusqtoff.com.ar/ver-producto/MIG-195"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="honda-eu22i",
        brand="Honda",
        commercial_name="Honda EU22i Inverter Portátil",
        mpn="EU22i",
        category="generadores",
        summary="Grupo electrógeno inverter ultra insonorizado de 1,8 kVA continuos con motor GXR120 de 4 tiempos.",
        primary_use="Alimentación de electrónica sensible, eventos y camping",
        power_source="Nafta 4 tiempos",
        specs={
            "potencia_nominal": make_spec("potencia_nominal", "Potencia nominal continua", "1,8 kVA (1,8 kW)", "kVA", 1.8, "kVA", "Régimen continuo COP", "EU22i", "Ficha oficial Honda Power Equipment Argentina", "https://pf.honda.com.ar/producto/EU22i", "pág. 1", "declarado"),
            "potencia_maxima": make_spec("potencia_maxima", "Potencia máxima de arranque", "2,2 kVA (2,2 kW)", "kVA", 2.2, "kVA", "Pico transitorio", "EU22i", "Ficha oficial Honda Power Equipment Argentina", "https://pf.honda.com.ar/producto/EU22i", "pág. 1", "declarado"),
            "tipo_generador": make_spec("tipo_generador", "Tecnología de regulación", "Inverter onda senoidal pura", "tipo", 0.0, "tipo", "Distorsión armónica THD < 2,5%", "EU22i", "Ficha oficial Honda Power Equipment Argentina", "https://pf.honda.com.ar/producto/EU22i", "pág. 1", "declarado"),
            "tanque_combustible": make_spec("tanque_combustible", "Capacidad del tanque", "3,6 L", "L", 3.6, "L", "Nafta sin plomo", "EU22i", "Ficha oficial Honda Power Equipment Argentina", "https://pf.honda.com.ar/producto/EU22i", "pág. 1", "declarado"),
            "peso_seco": make_spec("peso_seco", "Peso en seco", "21,1 kg", "kg", 21.1, "kg", "Sin combustible ni aceite", "EU22i", "Ficha oficial Honda Power Equipment Argentina", "https://pf.honda.com.ar/producto/EU22i", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("EU22i", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Inverter 50Hz")],
        kits=[KitOption("EU22i-STD", "Generador con cable para recarga de batería 12V y llave de bujía", "No aplica", "No aplica", ["Cable 12V", "Llave de bujía"])],
        commercial_offers=[CommercialOffer("Distribuidor Oficial Honda", "Mercado Libre", "https://meli.la/2AwxqaH", 1890000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Potencia continua de 1,8 kVA; no conectar motores de inducción con corriente de arranque superior a 2,2 kVA sin calcular pico."],
        primary_sources=[{"label": "Ficha oficial Honda EU22i", "url": "https://pf.honda.com.ar/producto/EU22i"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="honda-eu30is",
        brand="Honda",
        commercial_name="Honda EU30is Inverter Eléctrico",
        mpn="EU30is",
        category="generadores",
        summary="Generador inverter insonorizado de 2,8 kVA continuos con arranque eléctrico y tanque de 13 L.",
        primary_use="Respaldo residencial, motorhomes y laboratorios móviles",
        power_source="Nafta 4 tiempos",
        specs={
            "potencia_nominal": make_spec("potencia_nominal", "Potencia nominal", "2,8 kVA", "kVA", 2.8, "kVA", "Régimen continuo", "EU30is", "Ficha oficial Honda Argentina", "https://pf.honda.com.ar/producto/EU30is", "pág. 1", "declarado"),
            "potencia_maxima": make_spec("potencia_maxima", "Potencia máxima", "3,0 kVA", "kVA", 3.0, "kVA", "Pico", "EU30is", "Ficha oficial Honda Argentina", "https://pf.honda.com.ar/producto/EU30is", "pág. 1", "declarado"),
            "tanque_combustible": make_spec("tanque_combustible", "Capacidad de tanque", "13 L", "L", 13.0, "L", "Autonomía extendida Eco-Throttle", "EU30is", "Ficha oficial Honda Argentina", "https://pf.honda.com.ar/producto/EU30is", "pág. 1", "declarado"),
            "peso_seco": make_spec("peso_seco", "Peso en seco", "59 kg", "kg", 59.0, "kg", "Con batería de arranque", "EU30is", "Ficha oficial Honda Argentina", "https://pf.honda.com.ar/producto/EU30is", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("EU30is", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Arranque eléctrico")],
        kits=[KitOption("EU30is-STD", "Generador con batería 12V incorporada y ruedas de transporte", "No aplica", "No aplica", ["Batería 12V", "Ruedas", "Llave bujía"])],
        commercial_offers=[CommercialOffer("Distribuidor Oficial Honda", "Mercado Libre", "https://meli.la/2X86187", 3250000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Peso de 59 kg en seco; requiere ruedas o dos personas para su transporte."],
        primary_sources=[{"label": "Ficha oficial Honda EU30is", "url": "https://pf.honda.com.ar/producto/EU30is"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="honda-eg6500cxs",
        brand="Honda",
        commercial_name="Honda EG6500CXS D-AVR (5,5 kVA)",
        mpn="EG6500CXS",
        category="generadores",
        summary="Generador profesional de 5,0 kVA continuos con regulador digital D-AVR y motor GX390.",
        primary_use="Obra en construcción, soldadura y respaldo de potencia",
        power_source="Nafta 4 tiempos",
        specs={
            "potencia_nominal": make_spec("potencia_nominal", "Potencia nominal", "5,0 kVA", "kVA", 5.0, "kVA", "Continuo", "EG6500CXS", "Ficha oficial Honda Argentina", "https://pf.honda.com.ar/producto/EG6500CXS", "pág. 1", "declarado"),
            "potencia_maxima": make_spec("potencia_maxima", "Potencia máxima", "5,5 kVA", "kVA", 5.5, "kVA", "Pico", "EG6500CXS", "Ficha oficial Honda Argentina", "https://pf.honda.com.ar/producto/EG6500CXS", "pág. 1", "declarado"),
            "regulador": make_spec("regulador", "Tipo de regulación", "D-AVR (Digital)", "tipo", 0.0, "tipo", "Voltaje estable bajo variación de carga", "EG6500CXS", "Ficha oficial Honda Argentina", "https://pf.honda.com.ar/producto/EG6500CXS", "pág. 1", "declarado"),
            "tanque_combustible": make_spec("tanque_combustible", "Tanque de combustible", "24 L", "L", 24.0, "L", "Autonomía de obra", "EG6500CXS", "Ficha oficial Honda Argentina", "https://pf.honda.com.ar/producto/EG6500CXS", "pág. 1", "declarado"),
            "peso_seco": make_spec("peso_seco", "Peso en seco", "87 kg", "kg", 87.0, "kg", "Chasis tubular de acero", "EG6500CXS", "Ficha oficial Honda Argentina", "https://pf.honda.com.ar/producto/EG6500CXS", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("EG6500CXS", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Chasis abierto")],
        kits=[KitOption("EG6500CXS-STD", "Generador con arranque manual y eléctrico en chasis tubular", "No aplica", "No aplica", ["Chasis protector", "Batería"])],
        commercial_offers=[CommercialOffer("Distribuidor Oficial Honda", "Mercado Libre", "https://meli.la/1sxNfJ5", 2890000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["No es insonorizado; nivel sonoro propio de motor 4T de 390 cc en escape abierto."],
        primary_sources=[{"label": "Ficha oficial Honda EG6500CXS", "url": "https://pf.honda.com.ar/producto/EG6500CXS"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="gamma-inverter-2kw",
        brand="Gamma",
        commercial_name="Gamma Inverter 2 kW G2301AR",
        mpn="G2301AR",
        category="generadores",
        summary="Grupo electrógeno inverter de 2,0 kW nominales y 17 kg para camping y emergencias.",
        primary_use="Camping, náutica y emergencias domésticas",
        power_source="Nafta 4 tiempos",
        specs={
            "potencia_nominal": make_spec("potencia_nominal", "Potencia nominal", "2,0 kW (2000 W)", "kW", 2.0, "kW", "Continuo", "G2301AR", "Ficha oficial Gamma Inverter 2kW", "https://www.gammaherramientas.com.ar/producto/grupo-electrogeno-inverter-2kw/", "pág. 1", "declarado"),
            "potencia_maxima": make_spec("potencia_maxima", "Potencia de pico", "2,2 kW (2200 W)", "kW", 2.2, "kW", "Máxima", "G2301AR", "Ficha oficial Gamma Inverter 2kW", "https://www.gammaherramientas.com.ar/producto/grupo-electrogeno-inverter-2kw/", "pág. 1", "declarado"),
            "tanque_combustible": make_spec("tanque_combustible", "Capacidad de tanque", "4 L", "L", 4.0, "L", "Nafta", "G2301AR", "Ficha oficial Gamma Inverter 2kW", "https://www.gammaherramientas.com.ar/producto/grupo-electrogeno-inverter-2kw/", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso neto", "17 kg", "kg", 17.0, "kg", "Balanza", "G2301AR", "Ficha oficial Gamma Inverter 2kW", "https://www.gammaherramientas.com.ar/producto/grupo-electrogeno-inverter-2kw/", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("G2301AR", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Inverter maletín")],
        kits=[KitOption("G2301AR-STD", "Generador maletín con cables 12V y llave de bujía", "No aplica", "No aplica", ["Cables 12V", "Llave bujía"])],
        commercial_offers=[CommercialOffer("Distribuidor Gamma", "Mercado Libre", "https://meli.la/1B4sjDN", 699000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Generador monofásico 220 V; no conectar herramientas que requieran onda trifásica."],
        primary_sources=[{"label": "Ficha oficial Gamma Inverter 2 kW", "url": "https://www.gammaherramientas.com.ar/producto/grupo-electrogeno-inverter-2kw/"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="lusqtoff-lgi3-8",
        brand="Lüsqtoff",
        commercial_name="Lüsqtoff LGI3.8-8 Inverter (3,8 kW)",
        mpn="LGI3.8-8",
        category="generadores",
        summary="Generador inverter de 3,5 kW continuos y 3,8 kW de pico con tanque de 8 L y 28 kg.",
        primary_use="Alimentación de herramientas y eventos al aire libre",
        power_source="Nafta 4 tiempos",
        specs={
            "potencia_nominal": make_spec("potencia_nominal", "Potencia nominal", "3,5 kW", "kW", 3.5, "kW", "Continuo", "LGI3.8-8", "Ficha técnica Lüsqtoff LGI3.8-8", "https://www.lusqtoff.com.ar/ver-producto/LGI3.8-8", "pág. 1", "declarado"),
            "potencia_maxima": make_spec("potencia_maxima", "Potencia máxima", "3,8 kW", "kW", 3.8, "kW", "Pico", "LGI3.8-8", "Ficha técnica Lüsqtoff LGI3.8-8", "https://www.lusqtoff.com.ar/ver-producto/LGI3.8-8", "pág. 1", "declarado"),
            "tanque_combustible": make_spec("tanque_combustible", "Capacidad de tanque", "8 L", "L", 8.0, "L", "Nafta", "LGI3.8-8", "Ficha técnica Lüsqtoff LGI3.8-8", "https://www.lusqtoff.com.ar/ver-producto/LGI3.8-8", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso neto", "28 kg", "kg", 28.0, "kg", "Neto", "LGI3.8-8", "Ficha técnica Lüsqtoff LGI3.8-8", "https://www.lusqtoff.com.ar/ver-producto/LGI3.8-8", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("LGI3.8-8", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Inverter 3.8")],
        kits=[KitOption("LGI3.8-8-STD", "Generador inverter con ruedas y manija extensible", "No aplica", "No aplica", ["Ruedas", "Manija telescópica"])],
        commercial_offers=[CommercialOffer("Distribuidor Oficial", "Mercado Libre", "https://meli.la/2LGI38", 990000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["No confundir con el modelo LGIS3.8-8 motosoldadora."],
        primary_sources=[{"label": "Ficha oficial Lüsqtoff LGI3.8-8", "url": "https://www.lusqtoff.com.ar/ver-producto/LGI3.8-8"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="pektra-gpk980",
        brand="Pektra",
        commercial_name="Pektra GPK980 (720W)",
        mpn="GPK980",
        category="generadores",
        summary="Grupo electrógeno ultraliviano de 2 tiempos con 650 W nominales y 720 W de pico.",
        primary_use="Iluminación básica, pesca y emergencias mínimas",
        power_source="Nafta con mezcla de aceite 2T (50:1)",
        specs={
            "potencia_nominal": make_spec("potencia_nominal", "Potencia nominal", "650 W", "W", 650.0, "W", "Continuo", "GPK980", "Ficha comercial Frávega / Pektra", "https://www.fravega.com/p/grupo-electrogeno-pektra-gpk980-720w-63-cc-310651/", "pág. 1", "declarado"),
            "potencia_maxima": make_spec("potencia_maxima", "Potencia máxima", "720 W (0,72 kVA)", "W", 720.0, "W", "Pico", "GPK980", "Ficha comercial Frávega / Pektra", "https://www.fravega.com/p/grupo-electrogeno-pektra-gpk980-720w-63-cc-310651/", "pág. 1", "declarado"),
            "motor": make_spec("motor", "Tipo de motor", "2 tiempos (63 cc)", "tipo", 0.0, "tipo", "Requiere mezcla de nafta y aceite 2T", "GPK980", "Ficha comercial Frávega / Pektra", "https://www.fravega.com/p/grupo-electrogeno-pektra-gpk980-720w-63-cc-310651/", "pág. 1", "declarado"),
            "tanque_combustible": make_spec("tanque_combustible", "Capacidad de tanque", "4 L", "L", 4.0, "L", "Mezcla", "GPK980", "Ficha comercial Frávega / Pektra", "https://www.fravega.com/p/grupo-electrogeno-pektra-gpk980-720w-63-cc-310651/", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("GPK980", "Argentina", "220 V / 50 Hz", "IRAM 2073", "2 tiempos")],
        kits=[KitOption("GPK980-STD", "Generador con cables de carga 12V y vaso medidor de aceite", "No aplica", "No aplica", ["Vaso medidor", "Cables 12V"])],
        commercial_offers=[CommercialOffer("Tienda Pektra", "Mercado Libre", "https://meli.la/2jcLSy1", 169000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Motor 2 tiempos: exige mezcla exacta de aceite 2T; no apto para heladeras o bombas con alto consumo de arranque."],
        primary_sources=[{"label": "Ficha comercial Pektra GPK980", "url": "https://www.fravega.com/p/grupo-electrogeno-pektra-gpk980-720w-63-cc-310651/"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="philco-ge-ph2500alp",
        brand="Philco",
        commercial_name="Philco GE-PH2500ALP (2500W)",
        mpn="GE-PH2500ALP",
        category="generadores",
        summary="Generador naftero 4T de 2500 W continuos con tanque de 15 L y regulación AVR.",
        primary_use="Respaldo del hogar en cortes de luz",
        power_source="Nafta 4 tiempos",
        specs={
            "potencia_nominal": make_spec("potencia_nominal", "Potencia nominal", "2500 W", "W", 2500.0, "W", "Continuo", "GE-PH2500ALP", "Ficha técnica Philco Argentina", "https://www.mercadolibre.com.ar/generador-electrico-philco-2500w-65hp-196cc-tanque-15l/p/MLA29450496", "pág. 1", "declarado"),
            "potencia_maxima": make_spec("potencia_maxima", "Potencia máxima", "2800 W", "W", 2800.0, "W", "Pico", "GE-PH2500ALP", "Ficha técnica Philco Argentina", "https://www.mercadolibre.com.ar/generador-electrico-philco-2500w-65hp-196cc-tanque-15l/p/MLA29450496", "pág. 1", "declarado"),
            "tanque_combustible": make_spec("tanque_combustible", "Capacidad de tanque", "15 L", "L", 15.0, "L", "Autonomía aprox. 10 horas", "GE-PH2500ALP", "Ficha técnica Philco Argentina", "https://www.mercadolibre.com.ar/generador-electrico-philco-2500w-65hp-196cc-tanque-15l/p/MLA29450496", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("GE-PH2500ALP", "Argentina", "220 V / 50 Hz", "IRAM 2073", "4 tiempos con AVR")],
        kits=[KitOption("GE-PH2500ALP-STD", "Generador con llave sacabujías y patas de goma", "No aplica", "No aplica", ["Llave bujía", "Patas antivibratorias"])],
        commercial_offers=[CommercialOffer("Distribuidor Philco", "Mercado Libre", "https://meli.la/1nUAUuv", 450000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Regulación por AVR estándar; apto para electrodomésticos convencionales; para electrónica muy delicada se aconseja tecnología inverter."],
        primary_sources=[{"label": "Ficha comercial Philco GE-PH2500ALP", "url": "https://www.mercadolibre.com.ar/generador-electrico-philco-2500w-65hp-196cc-tanque-15l/p/MLA29450496"}],
        last_reviewed="2026-10-01"
    )
]
