"""Datos técnicos de 20 modelos de Taladros y Rotomartillos en Argentina."""

from tallerlab_data.catalog_data.common import make_spec
from tallerlab_data.models import (
    CommercialOffer,
    ContradictionRecord,
    KitOption,
    RegionalVariant,
    TechnicalTool,
)

TALADROS_TOOLS = [
    TechnicalTool(
        slug="bosch-gsb-550-re",
        brand="Bosch",
        commercial_name="GSB 550 RE Professional",
        mpn="06011A15H0",
        category="taladros",
        summary="Taladro percutor con cable de 550 W, mandril de 13 mm (1/2\") con llave y velocidad variable reversible.",
        primary_use="Perforación en mampostería, metal y madera",
        power_source="Red eléctrica (220 V)",
        specs={
            "potencia": make_spec("potencia", "Potencia absorbida", "550 W", "W", 550.0, "W", "Nominal", "06011A15H0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gsb-550-06011A15H0", "pág. 1", "declarado"),
            "velocidad_vacio": make_spec("velocidad_vacio", "Velocidad de giro en vacío", "0–2.800 rpm", "rpm", 2800.0, "rpm", "Variable continua", "06011A15H0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gsb-550-06011A15H0", "pág. 1", "declarado"),
            "frecuencia_impactos": make_spec("frecuencia_impactos", "Número de impactos a velocidad nominal", "0–41.800 gpm", "gpm", 41800.0, "gpm", "Modo percusión", "06011A15H0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gsb-550-06011A15H0", "pág. 1", "declarado"),
            "capacidad_mandril": make_spec("capacidad_mandril", "Capacidad de sujeción del mandril", "1,5–13 mm (1/2\")", "mm", 13.0, "mm", "Mandril de corona dentada con llave", "06011A15H0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gsb-550-06011A15H0", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso sin cable", "1,3 kg", "kg", 1.3, "kg", "Balanza", "06011A15H0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gsb-550-06011A15H0", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("06011A15H0", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Monofásico")],
        kits=[KitOption("06011A15H0-BOX", "Taladro GSB 550 RE con empuñadura auxiliar y tope de profundidad", "No aplica", "No aplica", ["Empuñadura auxiliar", "Tope de profundidad", "Llave de mandril"])],
        commercial_offers=[CommercialOffer("Distribuidor Bosch", "Mercado Libre", "https://meli.la/18iubWD", 115000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["La percusión mecánica es adecuada para ladrillo macizo y hueco; no sustituye un rotomartillo electroneumático en vigas de hormigón armado."],
        primary_sources=[{"label": "Ficha oficial Bosch GSB 550 RE", "url": "https://www.bosch-professional.com/ar/es/products/gsb-550-06011A15H0"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="bosch-gsb-18v-50",
        brand="Bosch",
        commercial_name="GSB 18V-50 Brushless",
        mpn="06019H51E0",
        category="taladros",
        summary="Taladro percutor a batería de 18V con motor sin escobillas y mandril metálico de 13 mm.",
        primary_use="Instalaciones, carpintería y montaje en obra",
        power_source="Batería 18 V Li-Ion (Bosch Professional)",
        specs={
            "torque_maximo": make_spec("torque_maximo", "Torque máximo (duro / blando)", "50 / 28 Nm", "Nm", 50.0, "Nm", "ISO 5393 a 18V", "06019H51E0", "Ficha técnica oficial Bosch", "https://www.bosch-professional.com/ar/es/products/gsb-18v-50-06019H51E0", "pág. 1", "declarado"),
            "velocidad_vacio": make_spec("velocidad_vacio", "Velocidad en vacío (1.ª / 2.ª marcha)", "0–460 / 0–1.800 rpm", "rpm", 1800.0, "rpm", "Caja de engranajes metálica", "06019H51E0", "Ficha técnica oficial Bosch", "https://www.bosch-professional.com/ar/es/products/gsb-18v-50-06019H51E0", "pág. 1", "declarado"),
            "frecuencia_impactos": make_spec("frecuencia_impactos", "Número de impactos", "0–27.000 gpm", "gpm", 27000.0, "gpm", "Percusión", "06019H51E0", "Ficha técnica oficial Bosch", "https://www.bosch-professional.com/ar/es/products/gsb-18v-50-06019H51E0", "pág. 1", "declarado"),
            "mandril": make_spec("mandril", "Capacidad de mandril", "1,5–13 mm", "mm", 13.0, "mm", "Metálico autoajustable Röhm", "06019H51E0", "Ficha técnica oficial Bosch", "https://www.bosch-professional.com/ar/es/products/gsb-18v-50-06019H51E0", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso sin batería", "1,1 kg", "kg", 1.1, "kg", "Solo herramienta", "06019H51E0", "Ficha técnica oficial Bosch", "https://www.bosch-professional.com/ar/es/products/gsb-18v-50-06019H51E0", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("06019H51E0", "Argentina", "18 V CC", "Bosch Professional 18V", "Brushless")],
        kits=[KitOption("06019H51E0-KIT", "Incluye 2 baterías GBA 18V 2.0Ah, cargador GAL 18V-20 y maletín L-Case", "2x 18V 2.0 Ah", "GAL 18V-20", ["2 baterías 2.0Ah", "Cargador", "Maletín L-Case"])],
        commercial_offers=[CommercialOffer("Distribuidor Bosch", "Mercado Libre", "https://meli.la/2GSB18V50", 419000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["El torque de 50 Nm corresponde a atornillado duro bajo norma ISO 5393; el torque blando sostenido es de 28 Nm."],
        primary_sources=[{"label": "Ficha oficial Bosch GSB 18V-50", "url": "https://www.bosch-professional.com/ar/es/products/gsb-18v-50-06019H51E0"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="bosch-gbh-220",
        brand="Bosch",
        commercial_name="GBH 220 Professional (SDS Plus)",
        mpn="06112A60H0",
        category="taladros",
        summary="Rotomartillo electroneumático de 720 W con 2,0 Joules de impacto para hormigón hasta 22 mm.",
        primary_use="Perforación en hormigón, ladrillo y demolición ligera",
        power_source="Red eléctrica (220 V)",
        specs={
            "potencia": make_spec("potencia", "Potencia absorbida", "720 W", "W", 720.0, "W", "Nominal", "06112A60H0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gbh-220-06112A60H0", "pág. 1", "declarado"),
            "energia_impacto": make_spec("energia_impacto", "Energía de impacto por percusión", "2,0 J", "J", 2.0, "J", "Medición según norma EPTA 05/2016", "06112A60H0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gbh-220-06112A60H0", "pág. 1", "declarado"),
            "frecuencia_impactos": make_spec("frecuencia_impactos", "Número de impactos a velocidad nominal", "0–4.800 gpm", "gpm", 4800.0, "gpm", "Régimen nominal", "06112A60H0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gbh-220-06112A60H0", "pág. 1", "declarado"),
            "diametro_hormigon": make_spec("diametro_hormigon", "Diámetro de perforación en hormigón", "4–22 mm", "mm", 22.0, "mm", "Brocas de rotomartillo SDS Plus", "06112A60H0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gbh-220-06112A60H0", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso", "2,3 kg", "kg", 2.3, "kg", "Balanza", "06112A60H0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gbh-220-06112A60H0", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("06112A60H0", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Encastre SDS Plus")],
        kits=[KitOption("06112A60H0-MALETIN", "GBH 220 en maletín de transporte con empuñadura auxiliar y tope", "No aplica", "No aplica", ["Maletín de transporte", "Empuñadura", "Tope"])],
        commercial_offers=[CommercialOffer("Distribuidor Bosch", "Mercado Libre", "https://meli.la/2cRLSJx", 249000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Para cincelado prolongado o apertura de zanjas pesadas en hormigón de losa se recomienda subir al segmento de 3 Joules (GBH 2-26 o 2-28)."],
        primary_sources=[{"label": "Ficha oficial Bosch GBH 220", "url": "https://www.bosch-professional.com/ar/es/products/gbh-220-06112A60H0"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="bosch-gbh-2-26-dre",
        brand="Bosch",
        commercial_name="GBH 2-26 DRE Professional",
        mpn="06112537H0",
        category="taladros",
        summary="Rotomartillo SDS Plus de 800 W y 2,7 Joules con embrague de seguridad y tres modos de trabajo.",
        primary_use="Obra pesada, hormigón y rozas",
        power_source="Red eléctrica (220 V)",
        specs={
            "potencia": make_spec("potencia", "Potencia absorbida", "800 W", "W", 800.0, "W", "Nominal", "06112537H0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gbh-2-26-dre-06112537H0", "pág. 1", "declarado"),
            "energia_impacto": make_spec("energia_impacto", "Energía de impacto", "2,7 J", "J", 2.7, "J", "EPTA 05/2016", "06112537H0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gbh-2-26-dre-06112537H0", "pág. 1", "declarado"),
            "diametro_hormigon": make_spec("diametro_hormigon", "Capacidad máx. en hormigón", "26 mm", "mm", 26.0, "mm", "Broca helicoidal SDS Plus", "06112537H0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gbh-2-26-dre-06112537H0", "pág. 1", "declarado"),
            "embrague_seguridad": make_spec("embrague_seguridad", "Embrague de seguridad mecánico", "Presente", "tipo", 0.0, "tipo", "Desacopla el giro si la broca se atasca", "06112537H0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gbh-2-26-dre-06112537H0", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso neto", "2,7 kg", "kg", 2.7, "kg", "Balanza", "06112537H0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gbh-2-26-dre-06112537H0", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("06112537H0", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Con embrague de sobrecarga")],
        kits=[KitOption("06112537H0-STD", "GBH 2-26 DRE en maletín de transporte profesional", "No aplica", "No aplica", ["Maletín de transporte", "Empuñadura", "Tope de profundidad"])],
        commercial_offers=[CommercialOffer("Distribuidor Bosch", "Mercado Libre", "https://meli.la/16mozwd", 399000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Incluye función de bloqueo de giro para cincelar (DRE); no confundir con modelo DFR que incluye mandril intercambiable cilíndrico."],
        primary_sources=[{"label": "Ficha oficial Bosch GBH 2-26 DRE", "url": "https://www.bosch-professional.com/ar/es/products/gbh-2-26-dre-06112537H0"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="bosch-gbh-180-li",
        brand="Bosch",
        commercial_name="GBH 180-LI Brushless (18V)",
        mpn="06119111E0",
        category="taladros",
        summary="Rotomartillo a batería 18V SDS Plus con 2,0 J y motor Brushless libre de mantenimiento.",
        primary_use="Montajes en altura, electricidad y obra sin cables",
        power_source="Batería 18 V Li-Ion (Bosch Professional)",
        specs={
            "energia_impacto": make_spec("energia_impacto", "Energía de impacto", "2,0 J", "J", 2.0, "J", "EPTA 05/2016", "06119111E0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gbh-180-li-06119111E0", "pág. 1", "declarado"),
            "frecuencia_impactos": make_spec("frecuencia_impactos", "Número de impactos", "0–5.100 gpm", "gpm", 5100.0, "gpm", "Nominal", "06119111E0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gbh-180-li-06119111E0", "pág. 1", "declarado"),
            "diametro_hormigon": make_spec("diametro_hormigon", "Capacidad máx. en hormigón", "20 mm", "mm", 20.0, "mm", "Brocas SDS Plus", "06119111E0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gbh-180-li-06119111E0", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso sin batería", "2,3 kg", "kg", 2.3, "kg", "Solo herramienta", "06119111E0", "Ficha oficial Bosch Professional Argentina", "https://www.bosch-professional.com/ar/es/products/gbh-180-li-06119111E0", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("06119111E0", "Argentina", "18 V CC", "Bosch Professional 18V", "Brushless")],
        kits=[KitOption("06119111E0-KIT", "Incluye 2 baterías 4.0Ah, cargador rápido GAL 18V-40 y maletín", "2x 18V 4.0 Ah", "GAL 18V-40", ["2 baterías 4.0Ah", "Cargador", "Maletín"])],
        commercial_offers=[CommercialOffer("Distribuidor Bosch", "Mercado Libre", "https://meli.la/29WzeN7", 495000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Para rendimiento óptimo continuo en brocas de 16–20 mm se recomienda usar baterías ProCORE18V de 4.0 Ah o superior."],
        primary_sources=[{"label": "Ficha oficial Bosch GBH 180-LI", "url": "https://www.bosch-professional.com/ar/es/products/gbh-180-li-06119111E0"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="bosch-gdr-120-li",
        brand="Bosch",
        commercial_name="GDR 120-LI Impact Driver",
        mpn="06019F00H0",
        category="taladros",
        summary="Atornillador de impacto compacto de 12V con 100 Nm de torque y encastre hexagonal de 1/4\".",
        primary_use="Atornillado en madera, fijaciones metálicas y carpintería",
        power_source="Batería 12 V Li-Ion",
        specs={
            "torque_maximo": make_spec("torque_maximo", "Torque máximo", "100 Nm", "Nm", 100.0, "Nm", "Atornillado duro ISO 5393", "06019F00H0", "Ficha técnica oficial Bosch", "https://www.bosch-professional.com/ar/es/products/gdr-120-li-06019F00H0", "pág. 1", "declarado"),
            "portaherramientas": make_spec("portaherramientas", "Portaherramientas", "Hexágono interior de 1/4\"", "encastre", 0.0, "encastre", "Con encastre rápido", "06019F00H0", "Ficha técnica oficial Bosch", "https://www.bosch-professional.com/ar/es/products/gdr-120-li-06019F00H0", "pág. 1", "declarado"),
            "frecuencia_impactos": make_spec("frecuencia_impactos", "Frecuencia de impactos", "0–3.200 ipm", "ipm", 3200.0, "ipm", "Mecanismo tangencial", "06019F00H0", "Ficha técnica oficial Bosch", "https://www.bosch-professional.com/ar/es/products/gdr-120-li-06019F00H0", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso sin batería", "1,05 kg", "kg", 1.05, "kg", "Balanza", "06019F00H0", "Ficha técnica oficial Bosch", "https://www.bosch-professional.com/ar/es/products/gdr-120-li-06019F00H0", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("06019F00H0", "Argentina", "12 V CC", "Bosch Professional 12V", "Compacto")],
        kits=[KitOption("06019F00H0-KIT", "Incluye 2 baterías 12V 2.0Ah y cargador en maletín", "2x 12V 2.0 Ah", "GAL 12V-20", ["2 baterías 2.0Ah", "Cargador", "Maletín plástico"])],
        commercial_offers=[CommercialOffer("Distribuidor Bosch", "Mercado Libre", "https://meli.la/2BGDR120", 225000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["No tiene embrague de torque regulable para durlock o tornillos pequeños; el apriete se controla por gatillo sensible."],
        primary_sources=[{"label": "Ficha oficial Bosch GDR 120-LI", "url": "https://www.bosch-professional.com/ar/es/products/gdr-120-li-06019F00H0"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="dewalt-dcd776",
        brand="DeWalt",
        commercial_name="DeWalt DCD776 Percutor 20V",
        mpn="DCD776",
        category="taladros",
        summary="Taladro percutor de 20V MAX con mandril autoajustable de 13 mm y 42 Nm de torque.",
        primary_use="Instalaciones eléctricas, carpintería y mantenimiento",
        power_source="Batería 20 V MAX Li-Ion",
        specs={
            "torque_maximo": make_spec("torque_maximo", "Torque máximo", "42 Nm", "Nm", 42.0, "Nm", "Nominal", "DCD776", "Ficha técnica DeWalt Argentina", "https://ar.dewalt.global/producto/dcd776c2-ar/taladro-percutor-de-12-13mm-20v-max", "pág. 1", "declarado"),
            "velocidad_vacio": make_spec("velocidad_vacio", "Velocidad sin carga", "0–450 / 0–1.500 rpm", "rpm", 1500.0, "rpm", "2 velocidades mecánicas", "DCD776", "Ficha técnica DeWalt Argentina", "https://ar.dewalt.global/producto/dcd776c2-ar/taladro-percutor-de-12-13mm-20v-max", "pág. 1", "declarado"),
            "impactos_minuto": make_spec("impactos_minuto", "Golpes por minuto", "0–7.650 / 0–25.500 gpm", "gpm", 25500.0, "gpm", "Percusión", "DCD776", "Ficha técnica DeWalt Argentina", "https://ar.dewalt.global/producto/dcd776c2-ar/taladro-percutor-de-12-13mm-20v-max", "pág. 1", "declarado"),
            "mandril": make_spec("mandril", "Mandril", "13 mm (1/2\")", "mm", 13.0, "mm", "Autoajustable", "DCD776", "Ficha técnica DeWalt Argentina", "https://ar.dewalt.global/producto/dcd776c2-ar/taladro-percutor-de-12-13mm-20v-max", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("DCD776C2-AR", "Argentina", "20 V MAX", "DeWalt 20V MAX", "Kit con cargador 220V")],
        kits=[KitOption("DCD776C2-AR", "Incluye 2 baterías de 1.3Ah o 1.5Ah y cargador en maletín", "2x 20V 1.3 Ah", "DCB107", ["2 baterías", "Cargador", "Maletín"])],
        commercial_offers=[CommercialOffer("Distribuidor DeWalt", "Mercado Libre", "https://meli.la/2DCD776", 365000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Motor con carbones reemplazables; no es la línea Brushless XR."],
        primary_sources=[{"label": "Ficha oficial DeWalt DCD776C2-AR", "url": "https://ar.dewalt.global/producto/dcd776c2-ar/taladro-percutor-de-12-13mm-20v-max"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="dewalt-dch273",
        brand="DeWalt",
        commercial_name="DeWalt DCH273B SDS Plus XR 20V",
        mpn="DCH273B",
        category="taladros",
        summary="Rotomartillo a batería 20V MAX XR Brushless con 2,1 J de impacto y control de vibraciones SHOCKS.",
        primary_use="Hormigón, tabiquería y anclajes mecánicos",
        power_source="Batería 20 V MAX Li-Ion",
        specs={
            "energia_impacto": make_spec("energia_impacto", "Energía de impacto", "2,1 J", "J", 2.1, "J", "EPTA 05/2016", "DCH273B", "Ficha técnica oficial DeWalt", "https://www.dewalt.com/en-us/product/dch273b/20v-max-xr-1-brushless-cordless-sds-plus-l-shape-rotary-hammer-tool-only", "pág. 1", "declarado"),
            "velocidad_vacio": make_spec("velocidad_vacio", "Velocidad en vacío", "0–1.100 rpm", "rpm", 1100.0, "rpm", "Variable", "DCH273B", "Ficha técnica oficial DeWalt", "https://www.dewalt.com/en-us/product/dch273b/20v-max-xr-1-brushless-cordless-sds-plus-l-shape-rotary-hammer-tool-only", "pág. 1", "declarado"),
            "frecuencia_impactos": make_spec("frecuencia_impactos", "Impactos por minuto", "0–4.600 gpm", "gpm", 4600.0, "gpm", "Nominal", "DCH273B", "Ficha técnica oficial DeWalt", "https://www.dewalt.com/en-us/product/dch273b/20v-max-xr-1-brushless-cordless-sds-plus-l-shape-rotary-hammer-tool-only", "pág. 1", "declarado"),
            "sistema_antivibracion": make_spec("sistema_antivibracion", "Control de vibración", "SHOCKS Active Vibration Control", "sistema", 0.0, "sistema", "Empuñadura desacoplada mecánicamente", "DCH273B", "Ficha técnica oficial DeWalt", "https://www.dewalt.com/en-us/product/dch273b/20v-max-xr-1-brushless-cordless-sds-plus-l-shape-rotary-hammer-tool-only", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso sin batería", "2,6 kg", "kg", 2.6, "kg", "Balanza", "DCH273B", "Ficha técnica oficial DeWalt", "https://www.dewalt.com/en-us/product/dch273b/20v-max-xr-1-brushless-cordless-sds-plus-l-shape-rotary-hammer-tool-only", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("DCH273B", "Argentina", "20 V MAX", "DeWalt 20V MAX", "Herramienta sola")],
        kits=[KitOption("DCH273B-SOLO", "Herramienta sola sin batería ni cargador con gancho para cinturón", "No incluye", "No incluye", ["Empuñadura 360", "Tope", "Gancho"])],
        commercial_offers=[CommercialOffer("Distribuidor DeWalt", "Mercado Libre", "https://meli.la/1uYbzCV", 520000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Sufijo B indica 'Bare tool' (herramienta sola); verificar disponibilidad de batería y cargador en la publicación."],
        primary_sources=[{"label": "Ficha oficial DeWalt DCH273B", "url": "https://www.dewalt.com/en-us/product/dch273b/20v-max-xr-1-brushless-cordless-sds-plus-l-shape-rotary-hammer-tool-only"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="dewalt-dch133",
        brand="DeWalt",
        commercial_name="DeWalt DCH133B D-Handle 20V",
        mpn="DCH133B",
        category="taladros",
        summary="Rotomartillo 20V MAX Brushless con empuñadura trasera en D y 2,6 Joules de impacto.",
        primary_use="Perforación descendente en pisos y losas",
        power_source="Batería 20 V MAX Li-Ion",
        specs={
            "energia_impacto": make_spec("energia_impacto", "Energía de impacto", "2,6 J", "J", 2.6, "J", "EPTA 05/2016", "DCH133B", "Ficha oficial DeWalt", "https://www.dewalt.com/en-us/product/dch133b/20v-max-1-brushless-cordless-sds-plus-d-handle-rotary-hammer-tool-only", "pág. 1", "declarado"),
            "frecuencia_impactos": make_spec("frecuencia_impactos", "Impactos por minuto", "0–5.550 gpm", "gpm", 5550.0, "gpm", "Nominal", "DCH133B", "Ficha oficial DeWalt", "https://www.dewalt.com/en-us/product/dch133b/20v-max-1-brushless-cordless-sds-plus-d-handle-rotary-hammer-tool-only", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso sin batería", "2,3 kg", "kg", 2.3, "kg", "Balanza", "DCH133B", "Ficha oficial DeWalt", "https://www.dewalt.com/en-us/product/dch133b/20v-max-1-brushless-cordless-sds-plus-d-handle-rotary-hammer-tool-only", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("DCH133B", "Argentina", "20 V MAX", "DeWalt 20V MAX", "Diseño D-Handle")],
        kits=[KitOption("DCH133B-SOLO", "Herramienta sola con empuñadura lateral de 360 grados", "No incluye", "No incluye", ["Empuñadura", "Tope de profundidad"])],
        commercial_offers=[CommercialOffer("Distribuidor DeWalt", "Mercado Libre", "https://meli.la/2DCH133", 449000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Ficha estadounidense: confirmar código exacto, kit y garantía del importador local en Argentina."],
        primary_sources=[{"label": "Ficha oficial DeWalt DCH133B", "url": "https://www.dewalt.com/en-us/product/dch133b/20v-max-1-brushless-cordless-sds-plus-d-handle-rotary-hammer-tool-only"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="dewalt-d25333",
        brand="DeWalt",
        commercial_name="DeWalt D25333K SDS Plus 950W",
        mpn="D25333K-QS",
        category="taladros",
        summary="Rotomartillo demoledor con cable de 950 W con 3,5 Joules de impacto para perforaciones de hasta 30 mm.",
        primary_use="Perforación pesada en hormigón de alta resistencia",
        power_source="Red eléctrica (230 V)",
        specs={
            "potencia": make_spec("potencia", "Potencia absorbida", "950 W", "W", 950.0, "W", "Nominal", "D25333K-QS", "Ficha técnica DeWalt Francia", "https://www.dewalt.fr/fr-fr/produit/d25333k-qs/perforateur-burineur-sds-plus-950-w-35-j", "pág. 1", "declarado"),
            "energia_impacto": make_spec("energia_impacto", "Energía de impacto", "3,5 J", "J", 3.5, "J", "EPTA 05/2016", "D25333K-QS", "Ficha técnica DeWalt Francia", "https://www.dewalt.fr/fr-fr/produit/d25333k-qs/perforateur-burineur-sds-plus-950-w-35-j", "pág. 1", "declarado"),
            "capacidad_hormigon": make_spec("capacidad_hormigon", "Capacidad máx. en hormigón", "4–30 mm", "mm", 30.0, "mm", "Broca SDS Plus", "D25333K-QS", "Ficha técnica DeWalt Francia", "https://www.dewalt.fr/fr-fr/produit/d25333k-qs/perforateur-burineur-sds-plus-950-w-35-j", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso neto", "3,7 kg", "kg", 3.7, "kg", "Balanza", "D25333K-QS", "Ficha técnica DeWalt Francia", "https://www.dewalt.fr/fr-fr/produit/d25333k-qs/perforateur-burineur-sds-plus-950-w-35-j", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("D25333K-QS", "Europa / Argentina", "230 V / 50 Hz", "IRAM 2073 / Schuko", "Variante QS")],
        kits=[KitOption("D25333K-STD", "D25333 con maletín TSTAK", "No aplica", "No aplica", ["Maletín TSTAK", "Empuñadura antivibración"])],
        commercial_offers=[CommercialOffer("Distribuidor Industrial", "Mercado Libre", "https://meli.la/2D25333", 690000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Variante europea QS de 230 V; no trasladar capacidades a otro sufijo regional sin contrastar manual."],
        primary_sources=[{"label": "Ficha oficial DeWalt D25333K-QS", "url": "https://www.dewalt.fr/fr-fr/produit/d25333k-qs/perforateur-burineur-sds-plus-950-w-35-j"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="dewalt-dcf887",
        brand="DeWalt",
        commercial_name="DeWalt DCF887B XR 20V",
        mpn="DCF887B",
        category="taladros",
        summary="Atornillador de impacto 20V MAX XR Brushless de 205 Nm con selector de 3 velocidades.",
        primary_use="Estructuras de madera, tornillería pesada y fijaciones",
        power_source="Batería 20 V MAX Li-Ion",
        specs={
            "torque_maximo": make_spec("torque_maximo", "Torque máximo", "205 Nm", "Nm", 205.0, "Nm", "Nominal en velocidad 3", "DCF887B", "Ficha técnica oficial DeWalt", "https://ar.dewalt.global/producto/dcf887b/atornillador-de-impacto-de-14-635mm-20v-max-xr", "pág. 1", "declarado"),
            "velocidades": make_spec("velocidades", "Velocidad sin carga (3 modos)", "0–1.000 / 0–2.800 / 0–3.250 rpm", "rpm", 3250.0, "rpm", "Selector digital", "DCF887B", "Ficha técnica oficial DeWalt", "https://ar.dewalt.global/producto/dcf887b/atornillador-de-impacto-de-14-635mm-20v-max-xr", "pág. 1", "declarado"),
            "frecuencia_impactos": make_spec("frecuencia_impactos", "Impactos por minuto", "0–3.800 ipm", "ipm", 3800.0, "ipm", "Mecanismo tangencial", "DCF887B", "Ficha técnica oficial DeWalt", "https://ar.dewalt.global/producto/dcf887b/atornillador-de-impacto-de-14-635mm-20v-max-xr", "pág. 1", "declarado"),
            "portaherramientas": make_spec("portaherramientas", "Encastre", "1/4\" (6,35 mm) hexagonal", "encastre", 0.0, "encastre", "Con liberación rápida de 1 mano", "DCF887B", "Ficha técnica oficial DeWalt", "https://ar.dewalt.global/producto/dcf887b/atornillador-de-impacto-de-14-635mm-20v-max-xr", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("DCF887B", "Argentina", "20 V MAX", "DeWalt 20V MAX", "Solo")],
        kits=[KitOption("DCF887B-SOLO", "Atornillador de impacto con gancho para cinturón y soporte magnético", "No incluye", "No incluye", ["Gancho cinturón", "Soporte magnético puntas"])],
        commercial_offers=[CommercialOffer("Distribuidor DeWalt", "Mercado Libre", "https://meli.la/2DCF887", 299000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Exige puntas de atornillar de calidad Impact Ready; las puntas estándar de acero al cromo se fracturan por el golpe de 205 Nm."],
        primary_sources=[{"label": "Ficha oficial DeWalt DCF887B", "url": "https://ar.dewalt.global/producto/dcf887b/atornillador-de-impacto-de-14-635mm-20v-max-xr"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="makita-hp333d",
        brand="Makita",
        commercial_name="Makita HP333D CXT 12V",
        mpn="HP333D",
        category="taladros",
        summary="Taladro atornillador percutor compacto a batería de 12V con mandril de 10 mm y 30 Nm de torque.",
        primary_use="Instalación de muebles, durlock y trabajos en espacios reducidos",
        power_source="Batería 12 V CXT Li-Ion",
        specs={
            "torque_maximo": make_spec("torque_maximo", "Torque máximo (duro / blando)", "30 / 14 Nm", "Nm", 30.0, "Nm", "ISO 5393", "HP333D", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 24", "declarado"),
            "velocidad_vacio": make_spec("velocidad_vacio", "Velocidad en vacío (baja / alta)", "0–450 / 0–1.700 rpm", "rpm", 1700.0, "rpm", "2 marchas mecánicas", "HP333D", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 24", "declarado"),
            "frecuencia_impactos": make_spec("frecuencia_impactos", "Impactos por minuto", "0–25.500 gpm", "gpm", 25500.0, "gpm", "Percusión", "HP333D", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 24", "declarado"),
            "capacidad_mandril": make_spec("capacidad_mandril", "Mandril", "0,8–10 mm (3/8\")", "mm", 10.0, "mm", "Autoajustable", "HP333D", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 24", "declarado"),
            "peso": make_spec("peso", "Peso con batería", "1,1 kg", "kg", 1.1, "kg", "Balanza con BL1016", "HP333D", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 24", "declarado"),
        },
        variants=[RegionalVariant("HP333DWE", "Argentina", "12 V CXT", "Makita CXT", "Kit con 2 baterías")],
        kits=[KitOption("HP333DWE", "Incluye 2 baterías 12V 1.5Ah, cargador DC10WD y maletín", "2x 12V 1.5 Ah", "DC10WD", ["2 baterías 1.5Ah", "Cargador", "Maletín"])],
        commercial_offers=[CommercialOffer("Distribuidor Makita", "Mercado Libre", "https://meli.la/2MHP333", 269000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Mandril de 10 mm no acepta mechas con zanco cilíndrico superior a esa medida sin rebajar."],
        primary_sources=[{"label": "Catálogo Makita Argentina 2025", "url": "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="makita-dhp453",
        brand="Makita",
        commercial_name="Makita DHP453 18V LXT",
        mpn="DHP453",
        category="taladros",
        summary="Taladro percutor a batería de 18V LXT con mandril de 13 mm y 42 Nm de torque.",
        primary_use="Construcción, mantenimiento y perforación general",
        power_source="Batería 18 V Li-Ion (Makita LXT)",
        specs={
            "torque_maximo": make_spec("torque_maximo", "Torque máximo (duro / blando)", "42 / 27 Nm", "Nm", 42.0, "Nm", "ISO 5393", "DHP453", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 28", "declarado"),
            "velocidad_vacio": make_spec("velocidad_vacio", "Velocidad en vacío", "0–400 / 0–1.300 rpm", "rpm", 1300.0, "rpm", "2 velocidades", "DHP453", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 28", "declarado"),
            "frecuencia_impactos": make_spec("frecuencia_impactos", "Impactos por minuto", "0–6.000 / 0–19.500 gpm", "gpm", 19500.0, "gpm", "Percusión", "DHP453", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 28", "declarado"),
            "capacidad_mandril": make_spec("capacidad_mandril", "Mandril", "1,5–13 mm (1/2\")", "mm", 13.0, "mm", "Autoajustable", "DHP453", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 28", "declarado"),
            "peso": make_spec("peso", "Peso con batería", "1,7 kg", "kg", 1.7, "kg", "Con batería BL1830B", "DHP453", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 28", "declarado"),
        },
        variants=[RegionalVariant("DHP453RFE", "Argentina", "18 V CC", "Makita LXT", "Kit 18V")],
        kits=[KitOption("DHP453RFE", "Incluye 2 baterías 18V 3.0Ah, cargador DC18RC y maletín", "2x 18V 3.0 Ah", "DC18RC", ["2 baterías 3.0Ah", "Cargador rápido", "Maletín"])],
        commercial_offers=[CommercialOffer("Distribuidor Makita", "Mercado Libre", "https://meli.la/2MDHP453", 485000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Modelo de motor con escobillas tradicionales de carbón; no es la línea Brushless BL."],
        primary_sources=[{"label": "Catálogo Makita Argentina 2025", "url": "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="makita-hr2470",
        brand="Makita",
        commercial_name="Makita HR2470 SDS Plus (780W)",
        mpn="HR2470",
        category="taladros",
        summary="Rotomartillo electroneumático de 780 W con 2,4 Joules de impacto y tres modos de operación.",
        primary_use="Instalaciones, hormigón y mampostería",
        power_source="Red eléctrica (220 V)",
        specs={
            "potencia": make_spec("potencia", "Potencia absorbida", "780 W", "W", 780.0, "W", "Nominal", "HR2470", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 44", "declarado"),
            "energia_impacto": make_spec("energia_impacto", "Energía de impacto", "2,4 J", "J", 2.4, "J", "EPTA 05/2016", "HR2470", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 44", "declarado"),
            "capacidad_hormigon": make_spec("capacidad_hormigon", "Capacidad máx. en hormigón", "24 mm", "mm", 24.0, "mm", "Broca SDS Plus", "HR2470", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 44", "declarado"),
            "frecuencia_impactos": make_spec("frecuencia_impactos", "Impactos por minuto", "0–4.500 gpm", "gpm", 4500.0, "gpm", "Nominal", "HR2470", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 44", "declarado"),
            "peso": make_spec("peso", "Peso neto", "2,9 kg", "kg", 2.9, "kg", "Balanza", "HR2470", "Catálogo Makita Argentina 2025", "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf", "pág. 44", "declarado"),
        },
        variants=[RegionalVariant("HR2470", "Argentina", "220 V / 50 Hz", "IRAM 2073", "3 modos")],
        kits=[KitOption("HR2470-STD", "HR2470 en maletín con empuñadura y tope", "No aplica", "No aplica", ["Maletín", "Empuñadura lateral", "Tope profundidad"])],
        commercial_offers=[CommercialOffer("Distribuidor Makita", "Mercado Libre", "https://meli.la/2MHR2470", 389000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Mecanismo de cambio de sentido por puente de carbones que mantiene la misma potencia en reversa."],
        primary_sources=[{"label": "Catálogo Makita Argentina 2025", "url": "https://makita.com.ar/wp-content/uploads/2025/09/CATALOGO-2025-v2.pdf"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="einhell-te-cd-18-40",
        brand="Einhell",
        commercial_name="TE-CD 18/40 Li Inalámbrico",
        mpn="4513887",
        category="taladros",
        summary="Taladro atornillador a batería 18V Power X-Change de 40 Nm con engranajes de 2 velocidades.",
        primary_use="Hogar, bricolaje y carpintería",
        power_source="Batería 18 V Li-Ion (Power X-Change)",
        specs={
            "torque_maximo": make_spec("torque_maximo", "Torque máximo", "40 Nm", "Nm", 40.0, "Nm", "Ajuste de 21 posiciones", "4513887", "Ficha técnica oficial Einhell", "https://www.einhell.com.ar/p/4513887-te-cd-18-40-li-solo/", "pág. 1", "declarado"),
            "velocidad_vacio": make_spec("velocidad_vacio", "Velocidad en vacío (1.ª / 2.ª marcha)", "0–400 / 0–1.500 rpm", "rpm", 1500.0, "rpm", "Engranaje metálico", "4513887", "Ficha técnica oficial Einhell", "https://www.einhell.com.ar/p/4513887-te-cd-18-40-li-solo/", "pág. 1", "declarado"),
            "capacidad_mandril": make_spec("capacidad_mandril", "Mandril", "13 mm", "mm", 13.0, "mm", "Monocasquillo autoajustable", "4513887", "Ficha técnica oficial Einhell", "https://www.einhell.com.ar/p/4513887-te-cd-18-40-li-solo/", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso sin batería", "1,07 kg", "kg", 1.07, "kg", "Balanza", "4513887", "Ficha técnica oficial Einhell", "https://www.einhell.com.ar/p/4513887-te-cd-18-40-li-solo/", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("4513887", "Argentina", "18 V CC", "Power X-Change", "Solo")],
        kits=[KitOption("4513887-SOLO", "Herramienta sola en caja de cartón sin batería", "No incluye", "No incluye", ["Clip para cinturón"])],
        commercial_offers=[CommercialOffer("Tienda Oficial Einhell", "Mercado Libre", "https://meli.la/2EINHTECD", 89999.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["No cuenta con función de percusión mecánica; apto para atornillado y perforación en madera/metal sin percusión."],
        primary_sources=[{"label": "Ficha oficial Einhell TE-CD 18/40 Li Solo", "url": "https://www.einhell.com.ar/p/4513887-te-cd-18-40-li-solo/"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="einhell-te-hd-18-li",
        brand="Einhell",
        commercial_name="TE-HD 18 Li SDS Plus (18V)",
        mpn="4513812",
        category="taladros",
        summary="Rotomartillo electro-neumático ultra compacto a batería de 18V con 1,2 Joules para fijaciones rápidas.",
        primary_use="Fijaciones en pared, tacos fisher y trabajo ligero",
        power_source="Batería 18 V Li-Ion (Power X-Change)",
        specs={
            "energia_impacto": make_spec("energia_impacto", "Energía de impacto", "1,2 J", "J", 1.2, "J", "Mecanismo neumático", "4513812", "Ficha técnica oficial Einhell", "https://www.einhell.com.ar/p/4513812-te-hd-18-li-solo/", "pág. 1", "declarado"),
            "velocidad_vacio": make_spec("velocidad_vacio", "Velocidad en vacío", "0–1.100 rpm", "rpm", 1100.0, "rpm", "Variable", "4513812", "Ficha técnica oficial Einhell", "https://www.einhell.com.ar/p/4513812-te-hd-18-li-solo/", "pág. 1", "declarado"),
            "capacidad_hormigon": make_spec("capacidad_hormigon", "Capacidad máx. en hormigón", "12 mm", "mm", 12.0, "mm", "Broca SDS Plus", "4513812", "Ficha técnica oficial Einhell", "https://www.einhell.com.ar/p/4513812-te-hd-18-li-solo/", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso sin batería", "1,39 kg", "kg", 1.39, "kg", "Balanza", "4513812", "Ficha técnica oficial Einhell", "https://www.einhell.com.ar/p/4513812-te-hd-18-li-solo/", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("4513812", "Argentina", "18 V CC", "Power X-Change", "Solo")],
        kits=[KitOption("4513812-SOLO", "Rotomartillo compacto sin batería con luz LED integrada", "No incluye", "No incluye", ["Adaptador para puntas"])],
        commercial_offers=[CommercialOffer("Tienda Oficial Einhell", "Mercado Libre", "https://meli.la/2EINHTEHD", 135000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["1,2 Joules son suficientes para tacos de 6 y 8 mm; no indicado para anclajes pesados de 14 mm o demolición."],
        primary_sources=[{"label": "Ficha oficial Einhell TE-HD 18 Li Solo", "url": "https://www.einhell.com.ar/p/4513812-te-hd-18-li-solo/"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="lusqtoff-tbl16-7",
        brand="Lüsqtoff",
        commercial_name="TBL16-7 de Banco (16 mm)",
        mpn="TBL16-7",
        category="taladros",
        summary="Taladro de banco vertical con motor de 375 W (0,5 HP), mandril de 16 mm y 5 velocidades mecánicas por polea.",
        primary_use="Taller de herrería, carpintería y mecanizado",
        power_source="Red eléctrica (220 V)",
        specs={
            "potencia": make_spec("potencia", "Potencia del motor", "375 W (0,5 HP)", "W", 375.0, "W", "Inducción", "TBL16-7", "Ficha oficial Lüsqtoff TBL16-7", "https://lusqtoff.com.ar/ver-producto/TBL16-7", "pág. 1", "declarado"),
            "capacidad_mandril": make_spec("capacidad_mandril", "Mandril de sujeción", "3–16 mm (B16)", "mm", 16.0, "mm", "Cono Morse / B16", "TBL16-7", "Ficha oficial Lüsqtoff TBL16-7", "https://lusqtoff.com.ar/ver-producto/TBL16-7", "pág. 1", "declarado"),
            "velocidades": make_spec("velocidades", "Número de velocidades", "5 velocidades", "escalones", 5.0, "escalones", "Por correa en poleas escalonadas", "TBL16-7", "Ficha oficial Lüsqtoff TBL16-7", "https://lusqtoff.com.ar/ver-producto/TBL16-7", "pág. 1", "declarado"),
            "recorrido_husillo": make_spec("recorrido_husillo", "Recorrido del mandril", "50 mm", "mm", 50.0, "mm", "Bajada de husillo", "TBL16-7", "Ficha oficial Lüsqtoff TBL16-7", "https://lusqtoff.com.ar/ver-producto/TBL16-7", "pág. 1", "declarado"),
            "peso": make_spec("peso", "Peso neto", "19 kg", "kg", 19.0, "kg", "Con mesa de hierro fundido", "TBL16-7", "Ficha oficial Lüsqtoff TBL16-7", "https://lusqtoff.com.ar/ver-producto/TBL16-7", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("TBL16-7", "Argentina", "220 V / 50 Hz", "IRAM 2073", "De banco")],
        kits=[KitOption("TBL16-7-STD", "Taladro de banco con mesa inclinable, llave de mandril y protector", "No aplica", "No aplica", ["Mesa inclinable", "Protector de virutas", "Llave mandril"])],
        commercial_offers=[CommercialOffer("Distribuidor Lüsqtoff", "Mercado Libre", "https://meli.la/2ehG4uD", 279000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Para cambiar velocidad hay que aflojar el tensor de la correa manualmente y moverla de escalón."],
        primary_sources=[{"label": "Ficha oficial Lüsqtoff TBL16-7", "url": "https://lusqtoff.com.ar/ver-producto/TBL16-7"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="lusqtoff-tbl710-9d",
        brand="Lüsqtoff",
        commercial_name="TBL710-9D Digital de Banco",
        mpn="TBL710-9D",
        category="taladros",
        summary="Taladro de banco con motor de 710 W, display digital de velocidad y luz láser de centrado.",
        primary_use="Taller moderno de precisión",
        power_source="Red eléctrica (220 V)",
        specs={
            "potencia": make_spec("potencia", "Potencia", "710 W", "W", 710.0, "W", "Universal con display", "TBL710-9D", "Ficha oficial Lüsqtoff TBL710-9D", "https://lusqtoff.com.ar/ver-producto/TBL710-9D", "pág. 1", "declarado"),
            "velocidad_variable": make_spec("velocidad_variable", "Rango de velocidad", "500–2.600 rpm", "rpm", 2600.0, "rpm", "Electrónica con display digital", "TBL710-9D", "Ficha oficial Lüsqtoff TBL710-9D", "https://lusqtoff.com.ar/ver-producto/TBL710-9D", "pág. 1", "declarado"),
            "capacidad_mandril": make_spec("capacidad_mandril", "Mandril", "1,5–13 mm", "mm", 13.0, "mm", "Autoajustable", "TBL710-9D", "Ficha oficial Lüsqtoff TBL710-9D", "https://lusqtoff.com.ar/ver-producto/TBL710-9D", "pág. 1", "declarado"),
            "laser_centrado": make_spec("laser_centrado", "Guía de cruz láser", "Presente", "tipo", 0.0, "tipo", "Proyección en cruz", "TBL710-9D", "Ficha oficial Lüsqtoff TBL710-9D", "https://lusqtoff.com.ar/ver-producto/TBL710-9D", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("TBL710-9D", "Argentina", "220 V / 50 Hz", "IRAM 2073", "Digital")],
        kits=[KitOption("TBL710-9D-STD", "Taladro con mordaza de fijación rápida y base de aluminio", "No aplica", "No aplica", ["Mordaza rápida", "Guía paralela", "Base"])],
        commercial_offers=[CommercialOffer("Distribuidor Oficial", "Mercado Libre", "https://meli.la/1MCEYGV", 359000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Motor universal con escobillas: mayor ruido en altas revoluciones comparado con motores a inducción tradicionales de polea."],
        primary_sources=[{"label": "Ficha oficial Lüsqtoff TBL710-9D", "url": "https://lusqtoff.com.ar/ver-producto/TBL710-9D"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="omaha-ab550161k",
        brand="Omaha",
        commercial_name="Omaha AB550161K (550W)",
        mpn="AB550161K",
        category="taladros",
        summary="Taladro de banco de 550 W (3/4 HP) con mandril de 16 mm y morsa plana de 3\" incluida.",
        primary_use="Taller metalúrgico y mantenimiento",
        power_source="Red eléctrica (220 V)",
        specs={
            "potencia": make_spec("potencia", "Potencia declarada", "550 W (3/4 HP)", "W", 550.0, "W", "Inducción", "AB550161K", "Ficha técnica Frávega / Omaha", "https://www.fravega.com/p/taladro-de-banco-16mm-3-4hp-perforador-agujereadora-550w-velocidad-variable-morza-990039049/", "pág. 1", "declarado"),
            "capacidad_mandril": make_spec("capacidad_mandril", "Mandril", "16 mm", "mm", 16.0, "mm", "Corona dentada", "AB550161K", "Ficha técnica Frávega / Omaha", "https://www.fravega.com/p/taladro-de-banco-16mm-3-4hp-perforador-agujereadora-550w-velocidad-variable-morza-990039049/", "pág. 1", "declarado"),
            "velocidades": make_spec("velocidades", "Velocidades por polea", "5 velocidades", "escalones", 5.0, "escalones", "Transmisión por correa", "AB550161K", "Ficha técnica Frávega / Omaha", "https://www.fravega.com/p/taladro-de-banco-16mm-3-4hp-perforador-agujereadora-550w-velocidad-variable-morza-990039049/", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("AB550161K", "Argentina", "220 V / 50 Hz", "IRAM 2073", "De banco")],
        kits=[KitOption("AB550161K-KIT", "Taladro de banco equipado con morsa plana de 3 pulgadas", "No aplica", "No aplica", ["Morsa plana 3 pulgadas", "Llave mandril"])],
        commercial_offers=[CommercialOffer("Tienda Omaha", "Mercado Libre", "https://meli.la/2Znq55m", 289000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Verificar que la morsa plana asiente correctamente sin juegos en las ranuras de la mesa."],
        primary_sources=[{"label": "Ficha comercial Omaha AB550161K", "url": "https://www.fravega.com/p/taladro-de-banco-16mm-3-4hp-perforador-agujereadora-550w-velocidad-variable-morza-990039049/"}],
        last_reviewed="2026-10-01"
    ),
    TechnicalTool(
        slug="ingco-cidli20668-4",
        brand="Ingco",
        commercial_name="Ingco CIDLI20668-4 Brushless 20V",
        mpn="CIDLI20668-4",
        category="taladros",
        summary="Taladro percutor de 20V con motor Brushless de 66 Nm de torque y mandril metálico.",
        primary_use="Construcción, obra y carpintería",
        power_source="Batería 20 V Li-Ion",
        specs={
            "torque_maximo": make_spec("torque_maximo", "Torque máximo", "66 Nm", "Nm", 66.0, "Nm", "Declarado en ficha del fabricante", "CIDLI20668-4", "Ficha técnica SuperTools Ingco", "https://supertoolsbd.com/product/ingco-20v-brushless-impact-drill-66nm/", "pág. 1", "declarado"),
            "capacidad_mandril": make_spec("capacidad_mandril", "Mandril metálico", "13 mm (1/2\")", "mm", 13.0, "mm", "Metálico autoajustable", "CIDLI20668-4", "Ficha técnica SuperTools Ingco", "https://supertoolsbd.com/product/ingco-20v-brushless-impact-drill-66nm/", "pág. 1", "declarado"),
            "velocidad_vacio": make_spec("velocidad_vacio", "Velocidad sin carga", "0–500 / 0–2.000 rpm", "rpm", 2000.0, "rpm", "2 velocidades", "CIDLI20668-4", "Ficha técnica SuperTools Ingco", "https://supertoolsbd.com/product/ingco-20v-brushless-impact-drill-66nm/", "pág. 1", "declarado"),
        },
        variants=[RegionalVariant("CIDLI20668-4", "Argentina", "20 V CC", "Ingco 20V", "Brushless")],
        kits=[KitOption("CIDLI20668-4-KIT", "Kit con 2 baterías de 2.0Ah, cargador y juego de mechas/puntas", "2x 20V 2.0 Ah", "Cargador rápido 220V", ["2 baterías 2.0Ah", "Cargador", "Accesorios"])],
        commercial_offers=[CommercialOffer("Distribuidor Ingco", "Mercado Libre", "https://meli.la/2xvJRJp", 265000.0, "2026-10-01", "nuevo", "pendiente_relevamiento")],
        contradictions=[],
        limits_and_warnings=["Sufijo -4 difiere del -3 en la electrónica del gatillo y configuración del cargador; no tratar como intercambiables."],
        primary_sources=[{"label": "Ficha oficial Ingco CIDLI20668", "url": "https://supertoolsbd.com/product/ingco-20v-brushless-impact-drill-66nm/"}],
        last_reviewed="2026-10-01"
    )
]
