const assert = require('node:assert/strict');
const {calculate, checkReadiness} = require('./assets/decision-tools.js');

assert.match(calculate('air', {supply:98,supplyPressure:7,demand:85,demandPressure:7}).body, /13 L\/min/);
assert.match(calculate('air', {supply:98,supplyPressure:7,demand:85,demandPressure:6}).title, /no coinciden/);
assert.match(calculate('air', {supply:98,supplyPressure:7,demand:100,demandPressure:7}).title, /por debajo/);
assert.match(calculate('rpm', {tool:33000,accessory:25000}).title, /por debajo/);
assert.match(calculate('rpm', {tool:25000,accessory:33000}).body, /8.000 rpm/);
assert.match(calculate('water', {flow:5.5,minutes:10}).title, /55 litros/);
assert.match(calculate('weight', {battery:.6}).title, /2,3 kg/);
assert.match(calculate('cut', {thickness:64}).body, /GKS 150/);
assert.doesNotMatch(calculate('cut', {thickness:64}).body, /CSL1500/);
assert.match(calculate('cut', {thickness:66}).title, /Supera/);
assert.match(calculate('hammer', {diameter:24}).body, /GBH 2-26/);
assert.doesNotMatch(calculate('hammer', {diameter:24}).body, /GBH 220/);
assert.match(calculate('jigsaw', {thickness:9,material:'steel'}).body, /TE-JS 100/);
assert.doesNotMatch(calculate('jigsaw', {thickness:9,material:'steel'}).body, /TC-JS 85/);
assert.match(calculate('jigsaw', {thickness:6,material:'steel'}).body, /TC-JS 85: máximo/);
assert.doesNotMatch(calculate('jigsaw', {thickness:6,material:'steel'}).body, /BES603-B2: máximo/);
assert.match(calculate('jigsaw', {thickness:6,material:'steel'}).body, /no se evalúa para acero/);
assert.match(calculate('jigsaw', {thickness:65,material:'wood'}).body, /BES603-B2: máximo 65/);
assert.doesNotMatch(calculate('jigsaw', {thickness:66,material:'wood'}).body, /BES603-B2: máximo/);
assert.match(calculate('jigsaw', {thickness:6,material:'metal'}).title, /Elegí madera o acero/);
assert.match(calculate('cost', {priceA:100,shippingA:10,extrasA:5,priceB:90,shippingB:20,extrasB:10}).title, /115.*120/);
assert.match(calculate('cost', {priceA:0,shippingA:0,extrasA:0,priceB:90,shippingB:0,extrasB:0}).title, /Ingresá/);
assert.match(calculate('house', {}, [{name:'Luces',run:'100',start:'100'},{name:'Motor',run:'200',start:'600'},{name:'',run:'',start:''}]).title, /300 W.*700 W/);
assert.match(calculate('house', {}, [{name:'Motor',run:'200',start:''}]).title, /Faltan/);
assert.match(calculate('house', {}, [{name:'Motor',run:'200',start:'100'}]).title, /Faltan/);
assert.match(calculate('house', {}, []).title, /Agregá/);
assert.match(calculate('water', {flow:Infinity,minutes:10}).title, /Revisá/);
assert.match(calculate('water', {flow:-1,minutes:10}).title, /Revisá/);
assert.match(calculate('water', {flow:'',minutes:10}).title, /Revisá/);
assert.match(calculate('mitre', {width:120,height:55}).body, /TC-MS 2112/);
assert.match(calculate('mitre', {width:120,height:60}).body, /TC-SM 2131/);
assert.doesNotMatch(calculate('mitre', {width:120,height:60}).body, /TC-MS 2112/);
assert.match(calculate('mitre', {width:121,height:50}).body, /TC-SM 2131/);
assert.doesNotMatch(calculate('mitre', {width:121,height:50}).body, /TC-MS 2112/);
assert.match(calculate('mitre', {width:310,height:62}).title, /entra/);
assert.match(calculate('mitre', {width:311,height:50}).title, /supera/);
assert.match(calculate('mitre', {width:100,height:63}).title, /supera/);
assert.match(calculate('mitre', {width:0,height:55}).title, /Revisá/);
assert.match(calculate('mitre', {width:100,height:undefined}).title, /Revisá/);
assert.match(calculate('blind-hole', {board:18,depth:12}).title, /6 mm/);
assert.match(calculate('blind-hole', {board:18,depth:18}).title, /iguala o supera/);
assert.match(calculate('blind-hole', {board:18,depth:19}).body, /− 19 = -1 mm/);
assert.match(calculate('blind-hole', {board:18,depth:''}).title, /Revisá/);
assert.match(calculate('blind-hole', {board:18,depth:12}).body, /punta central/);
const checks = [['Presión de consumo', 'Documento'], ['Salida a igual presión', 'Documento']];
assert.match(checkReadiness(checks, []).body, /Presión de consumo.*Salida a igual presión/);
assert.match(checkReadiness(checks, [true,false]).title, /1 de 2/);
assert.doesNotMatch(checkReadiness(checks, [true,false]).body, /Pendientes: Presión de consumo/);
assert.match(checkReadiness(checks, [true,true]).body, /No certifica compatibilidad/);
assert.match(checkReadiness(checks, ['true',true]).title, /1 de 2/);
console.log('OK: cálculos, límites, pendientes, materiales de caladora y ausencia de certificación automática.');
