"""Catálogo maestro de 30 modelos y configuración de ofertas del Observatorio."""

import json
from dataclasses import asdict, dataclass
from typing import Dict, List, Optional


def validate_gtin(code: Optional[str]) -> bool:
    """Verifica el dígito de control GS1 (GTIN-8, 12, 13, 14). Retorna True si es válido."""
    if not code:
        return False
    s = str(code).strip()
    if not s.isdigit() or len(s) not in (8, 12, 13, 14):
        return False
    total = sum(int(d) * (3 if i % 2 == 0 else 1) for i, d in enumerate(reversed(s[:-1])))
    check = (10 - (total % 10)) % 10
    return check == int(s[-1])



@dataclass(frozen=True)
class CatalogProduct:
    id: str
    category: str
    brand: str
    model_name: str
    mpn: str
    gtin_ean: Optional[str]
    voltage: str
    specs: Dict[str, str]
    kit_content: str
    item_condition: str
    guide_url: str

    def to_dict(self) -> Dict:
        d = asdict(self)
        d["specs_json"] = json.dumps(d.pop("specs"), ensure_ascii=False)
        return d


# Cohorte inicial prioritaria de 10 modelos para validación temprana
VALIDATION_COHORT_10: List[str] = [
    "COMP-LUSQ-LC2550B",
    "COMP-GAMMA-G2802",
    "COMP-EINHELL-TEAC270",
    "COMP-LUSQ-LC0122",
    "COMP-LUSQ-MCL150",
    "HIDRO-KARCH-K2",
    "HIDRO-KARCH-K4PC",
    "HIDRO-LUSQ-HL100",
    "HIDRO-LUSQ-HL120",
    "HIDRO-GAMMA-G130",
]

# Catálogo completo de 30 modelos exactos
CATALOG_PRODUCTS: List[CatalogProduct] = [
    # COMPRESORES (14 modelos)
    CatalogProduct(
        id="COMP-LUSQ-LC2550B",
        category="compresores",
        brand="Lüsqtoff",
        model_name="LC2550B-8",
        mpn="LC2550B-8",
        gtin_ean=None,
        voltage="220 V",
        specs={"tanque": "50 L", "potencia": "2,5 HP", "caudal": "206 L/min", "tipo": "Lubricado por aceite"},
        kit_content="Compresor 50 L con ruedas, pie de apoyo y filtro de aire",
        item_condition="nuevo",
        guide_url="/compresores/50-litros/",
    ),
    CatalogProduct(
        id="COMP-LUSQ-LC2550VS",
        category="compresores",
        brand="Lüsqtoff",
        model_name="LC-2550VS",
        mpn="LC-2550VS",
        gtin_ean=None,
        voltage="220 V",
        specs={"tanque": "50 L vertical", "potencia": "2,5 HP", "caudal": "206 L/min", "tipo": "Vertical lubricado"},
        kit_content="Compresor vertical con ruedas de transporte",
        item_condition="nuevo",
        guide_url="/compresores/50-litros/",
    ),
    CatalogProduct(
        id="COMP-LUSQ-LCS50",
        category="compresores",
        brand="Lüsqtoff",
        model_name="LCS50-8",
        mpn="LCS50-8",
        gtin_ean=None,
        voltage="220 V",
        specs={"tanque": "50 L", "potencia": "2,0 HP", "ruido": "Silencioso 65 dB", "tipo": "Sin aceite (Silent)"},
        kit_content="Compresor libre de aceite con motor silencioso",
        item_condition="nuevo",
        guide_url="/compresores/lusqtoff-50-litros/",
    ),
    CatalogProduct(
        id="COMP-LUSQ-LC3550BK",
        category="compresores",
        brand="Lüsqtoff",
        model_name="LC-3550BK",
        mpn="LC-3550BK",
        gtin_ean=None,
        voltage="220 V",
        specs={"tanque": "50 L", "potencia": "3,5 HP", "cilindros": "Bicilíndrico en V", "tipo": "Alta recuperación"},
        kit_content="Compresor bicilíndrico con kit de acoples",
        item_condition="nuevo",
        guide_url="/compresores/50-litros/",
    ),
    CatalogProduct(
        id="COMP-LUSQ-LC0122",
        category="compresores",
        brand="Lüsqtoff",
        model_name="LC-0122",
        mpn="LC-0122",
        gtin_ean=None,
        voltage="220 V",
        specs={"tanque": "24 L", "potencia": "1,0 HP", "ruido": "Ultra silencioso", "tipo": "Sin aceite"},
        kit_content="Compresor 24 L sin aceite",
        item_condition="nuevo",
        guide_url="/compresores/sin-aceite/",
    ),
    CatalogProduct(
        id="COMP-LUSQ-LC30100",
        category="compresores",
        brand="Lüsqtoff",
        model_name="LC-30100",
        mpn="LC-30100",
        gtin_ean=None,
        voltage="220 V",
        specs={"tanque": "100 L", "potencia": "3,0 HP (2200 W)", "transmision": "Correa", "tipo": "Bicilíndrico taller"},
        kit_content="Compresor 100 L de taller con protector de correa",
        item_condition="nuevo",
        guide_url="/compresores/100-litros/",
    ),
    CatalogProduct(
        id="COMP-LUSQ-LC40100",
        category="compresores",
        brand="Lüsqtoff",
        model_name="LC-40100",
        mpn="LC-40100",
        gtin_ean="7798144214010",
        voltage="220 V",
        specs={"tanque": "100 L", "potencia": "4,0 HP", "transmision": "Directa", "tipo": "Monofásico de alta entrega"},
        kit_content="Compresor 100 L con regulador de salida",
        item_condition="nuevo",
        guide_url="/compresores/100-litros/",
    ),
    CatalogProduct(
        id="COMP-LUSQ-MCL150",
        category="compresores",
        brand="Lüsqtoff",
        model_name="MCL150-8",
        mpn="MCL150-8",
        gtin_ean=None,
        voltage="12 V",
        specs={"presion": "150 PSI máx.", "display": "Digital", "tipo": "Inflador portátil para auto"},
        kit_content="Inflador 12 V con conector a encendedor, linterna y picos adaptadores",
        item_condition="nuevo",
        guide_url="/compresores/para-auto/",
    ),
    CatalogProduct(
        id="COMP-GAMMA-G2801",
        category="compresores",
        brand="Gamma",
        model_name="G2801AR",
        mpn="G2801AR",
        gtin_ean=None,
        voltage="220 V",
        specs={"tanque": "24 L", "potencia": "2,0 HP", "caudal": "195 L/min", "tipo": "Lubricado monofásico"},
        kit_content="Compresor 24 L monofásico con manómetro",
        item_condition="nuevo",
        guide_url="/compresores/24-litros/",
    ),
    CatalogProduct(
        id="COMP-GAMMA-G2802",
        category="compresores",
        brand="Gamma",
        model_name="G2802AR",
        mpn="G2802AR",
        gtin_ean=None,
        voltage="220 V",
        specs={"tanque": "50 L", "potencia": "2,0 HP", "caudal": "206 L/min", "tipo": "Lubricado monofásico"},
        kit_content="Compresor 50 L con ruedas y tapón de purga",
        item_condition="nuevo",
        guide_url="/compresores/50-litros/",
    ),
    CatalogProduct(
        id="COMP-GAMMA-G2803",
        category="compresores",
        brand="Gamma",
        model_name="G2803AR",
        mpn="G2803AR",
        gtin_ean=None,
        voltage="220 V",
        specs={"tanque": "100 L", "potencia": "3,0 HP", "transmision": "Correa", "tipo": "Bicilíndrico"},
        kit_content="Compresor 100 L con cabezal bicilíndrico en línea",
        item_condition="nuevo",
        guide_url="/compresores/100-litros/",
    ),
    CatalogProduct(
        id="COMP-EINHELL-TEAC270",
        category="compresores",
        brand="Einhell",
        model_name="TE-AC 270/50 Silent",
        mpn="4020610",
        gtin_ean="4006825652505",
        voltage="220 V",
        specs={"tanque": "50 L", "potencia": "1500 W", "ruido": "54 dB(A)", "tipo": "Libre de aceite silencioso"},
        kit_content="Compresor Silent 50 L con doble pistón",
        item_condition="nuevo",
        guide_url="/compresores/50-litros/",
    ),
    CatalogProduct(
        id="COMP-EINHELL-TCAC190",
        category="compresores",
        brand="Einhell",
        model_name="TC-AC 190/24/8",
        mpn="4007325",
        gtin_ean="4006825615715",
        voltage="220 V",
        specs={"tanque": "24 L", "potencia": "1500 W", "presion": "8 bar", "tipo": "Sin aceite"},
        kit_content="Compresor 24 L compacto libre de aceite",
        item_condition="nuevo",
        guide_url="/compresores/24-litros/",
    ),
    CatalogProduct(
        id="COMP-NICTOM-IE01",
        category="compresores",
        brand="Nictom",
        model_name="IE01",
        mpn="IE01",
        gtin_ean=None,
        voltage="Batería / USB",
        specs={"presion": "150 PSI máx.", "caudal": "16 L/min anunciados", "tipo": "Inflador a batería portátil"},
        kit_content="Inflador portátil recargable con manguera roscada y picos",
        item_condition="nuevo",
        guide_url="/compresores/para-auto/",
    ),

    # HIDROLAVADORAS (12 modelos)
    CatalogProduct(
        id="HIDRO-KARCH-K2",
        category="hidrolavadoras",
        brand="Kärcher",
        model_name="K2",
        mpn="1.673-220.0",
        gtin_ean="4039784961555",
        voltage="220 V",
        specs={"presion_max": "110 bar", "caudal": "360 L/h", "potencia": "1400 W", "tipo": "Agua fría"},
        kit_content="Pistola G 120 Q, lanza simple, lanza turbo y manguera de 4 m",
        item_condition="nuevo",
        guide_url="/hidrolavadoras/karcher-k2/",
    ),
    CatalogProduct(
        id="HIDRO-KARCH-K3",
        category="hidrolavadoras",
        brand="Kärcher",
        model_name="K3",
        mpn="1.601-812.0",
        gtin_ean="4039784961562",
        voltage="220 V",
        specs={"presion_max": "120 bar", "caudal": "380 L/h", "potencia": "1600 W", "tipo": "Agua fría"},
        kit_content="Pistola Quick Connect, lanza Vario Power, lanza turbo y manguera de 6 m",
        item_condition="nuevo",
        guide_url="/hidrolavadoras/karcher-k3/",
    ),
    CatalogProduct(
        id="HIDRO-KARCH-K4PC",
        category="hidrolavadoras",
        brand="Kärcher",
        model_name="K4 Power Control",
        mpn="1.324-030.0",
        gtin_ean="4054278604084",
        voltage="220 V",
        specs={"presion_max": "130 bar", "caudal": "420 L/h", "potencia": "1800 W", "motor": "Inducción refrigerado por agua"},
        kit_content="Pistola Power Control G 160 Q, lanza Vario Power y manguera de 8 m",
        item_condition="nuevo",
        guide_url="/hidrolavadoras/karcher-k4/",
    ),
    CatalogProduct(
        id="HIDRO-KARCH-K5PC",
        category="hidrolavadoras",
        brand="Kärcher",
        model_name="K5 Power Control",
        mpn="1.324-550.0",
        gtin_ean="4054278604121",
        voltage="220 V",
        specs={"presion_max": "145 bar", "caudal": "500 L/h", "potencia": "2100 W", "motor": "Inducción refrigerado por agua"},
        kit_content="Pistola Power Control, lanza Vario Power, fresadora de suciedad y manguera 10 m",
        item_condition="nuevo",
        guide_url="/hidrolavadoras/karcher-k5/",
    ),
    CatalogProduct(
        id="HIDRO-LUSQ-HL100",
        category="hidrolavadoras",
        brand="Lüsqtoff",
        model_name="HL100-7",
        mpn="HL100-7",
        gtin_ean=None,
        voltage="220 V",
        specs={"presion_max": "100 bar", "presion_nom": "70 bar", "caudal": "5,5 L/min", "potencia": "1200 W"},
        kit_content="Pistola rociadora, lanza con boquilla regulable y manguera de 3 m",
        item_condition="nuevo",
        guide_url="/hidrolavadoras/lusqtoff/",
    ),
    CatalogProduct(
        id="HIDRO-LUSQ-HL120",
        category="hidrolavadoras",
        brand="Lüsqtoff",
        model_name="HL-120",
        mpn="HL-120",
        gtin_ean=None,
        voltage="220 V",
        specs={"presion_max": "120 bar", "presion_nom": "80 bar", "caudal": "6,0 L/min", "potencia": "1400 W"},
        kit_content="Pistola con traba de seguridad, lanza, depósito para jabón y manguera 5 m",
        item_condition="nuevo",
        guide_url="/hidrolavadoras/lusqtoff-hl-120/",
    ),
    CatalogProduct(
        id="HIDRO-LUSQ-HL145",
        category="hidrolavadoras",
        brand="Lüsqtoff",
        model_name="HL-145",
        mpn="HL-145",
        gtin_ean=None,
        voltage="220 V",
        specs={"presion_max": "145 bar", "caudal": "6,5 L/min", "potencia": "1600 W", "tipo": "Uso doméstico intensivo"},
        kit_content="Pistola ergonómica, lanza regulable, dosificador de espuma y manguera 5 m",
        item_condition="nuevo",
        guide_url="/hidrolavadoras/lusqtoff/",
    ),
    CatalogProduct(
        id="HIDRO-GAMMA-G130",
        category="hidrolavadoras",
        brand="Gamma",
        model_name="G130",
        mpn="G1902AR",
        gtin_ean="7793253001902",
        voltage="220 V",
        specs={"presion_max": "130 bar", "caudal": "6,0 L/min", "potencia": "1600 W", "sistema": "Auto-stop"},
        kit_content="Pistola de alta presión, lanza con boquilla regulable y manguera 5 m",
        item_condition="nuevo",
        guide_url="/hidrolavadoras/gamma-130/",
    ),
    CatalogProduct(
        id="HIDRO-GAMMA-G150",
        category="hidrolavadoras",
        brand="Gamma",
        model_name="G150",
        mpn="G1903AR",
        gtin_ean=None,
        voltage="220 V",
        specs={"presion_max": "150 bar", "caudal": "6,7 L/min", "potencia": "2000 W", "motor": "Inducción"},
        kit_content="Pistola con boquilla turbo, rociador de detergente y manguera reforzada 5 m",
        item_condition="nuevo",
        guide_url="/hidrolavadoras/gamma-150/",
    ),
    CatalogProduct(
        id="HIDRO-BOSCH-EA100",
        category="hidrolavadoras",
        brand="Bosch",
        model_name="EasyAquatak 100",
        mpn="06008A7E00",
        gtin_ean="3165140935661",
        voltage="220 V",
        specs={"presion_max": "100 bar", "caudal": "300 L/h", "potencia": "1200 W", "tipo": "Diseño 360 compacto"},
        kit_content="Pistola orientable a 360°, manguera de 3 m y boquilla con depósito de detergente",
        item_condition="nuevo",
        guide_url="/hidrolavadoras/bosch/",
    ),
    CatalogProduct(
        id="HIDRO-BOSCH-EA120",
        category="hidrolavadoras",
        brand="Bosch",
        model_name="EasyAquatak 120",
        mpn="06008A7900",
        gtin_ean="3165140935616",
        voltage="220 V",
        specs={"presion_max": "120 bar", "caudal": "350 L/h", "potencia": "1500 W", "bomba": "Totalmente metálica"},
        kit_content="Pistola de alta presión, boquilla de chorro plano y rotativa, manguera 5 m",
        item_condition="nuevo",
        guide_url="/hidrolavadoras/bosch/",
    ),
    CatalogProduct(
        id="HIDRO-BD-BEPW1600",
        category="hidrolavadoras",
        brand="Black+Decker",
        model_name="BEPW1600",
        mpn="BEPW1600-AR",
        gtin_ean="885911797825",
        voltage="220 V",
        specs={"presion_max": "110 bar", "caudal": "396 L/h", "potencia": "1300 W", "bomba": "Aluminio"},
        kit_content="Pistola ergonómica, lanza de pulverización y manguera de 3 m",
        item_condition="nuevo",
        guide_url="/hidrolavadoras/black-decker/",
    ),

    # GENERADORES (4 modelos con cobertura representativa)
    CatalogProduct(
        id="GEN-HONDA-EU22I",
        category="generadores",
        brand="Honda",
        model_name="EU22i",
        mpn="EU22i",
        gtin_ean="4945943202950",
        voltage="220 V",
        specs={"potencia_nom": "1,8 kVA", "potencia_max": "2,2 kVA", "tecnologia": "Inverter", "motor": "Honda GXR120 4T"},
        kit_content="Generador inverter insonorizado con cables para carga de batería 12 V",
        item_condition="nuevo",
        guide_url="/generadores/comparativa-general/",
    ),
    CatalogProduct(
        id="GEN-GAMMA-GE3480",
        category="generadores",
        brand="Gamma",
        model_name="GE3480AR (3000V)",
        mpn="GE3480AR",
        gtin_ean=None,
        voltage="220 V",
        specs={"potencia_nom": "2,5 kW", "potencia_max": "2,8 kW", "regulacion": "AVR", "motor": "4 tiempos 6,5 HP"},
        kit_content="Generador con bastidor de acero, voltímetro analógico y corte térmico",
        item_condition="nuevo",
        guide_url="/generadores/comparativa-general/",
    ),
    CatalogProduct(
        id="GEN-PHILCO-GEPH25",
        category="generadores",
        brand="Philco",
        model_name="GE-PH2500ALP",
        mpn="GE-PH2500ALP",
        gtin_ean=None,
        voltage="220 V",
        specs={"potencia_nom": "2500 W", "potencia_max": "2800 W", "tanque": "15 L", "motor": "196 cc 6,5 HP"},
        kit_content="Generador monofásico a nafta con indicador de nivel de combustible",
        item_condition="nuevo",
        guide_url="/generadores/a-nafta/",
    ),
    CatalogProduct(
        id="GEN-PEKTRA-GPK980",
        category="generadores",
        brand="Pektra",
        model_name="GPK980",
        mpn="GPK980",
        gtin_ean=None,
        voltage="220 V",
        specs={"potencia_nom": "650 W", "potencia_max": "720 W", "motor": "2 tiempos 63 cc", "tanque": "4,2 L"},
        kit_content="Generador compacto 2T con asa superior y patas antivibratorias",
        item_condition="nuevo",
        guide_url="/generadores/chicos/",
    ),
]

PRODUCTS_BY_ID = {p.id: p for p in CATALOG_PRODUCTS}
